iTwin/iTwinUI

- .gitattributes
Ignoring all html files using [github linguist](https://github.com/github/linguist/blob/master/docs/overrides.md) syntax to reclassify this repo as SCSS
> Ignore html files from github linguist

- src/style/mixins.scss
Setting `scrollbar-width: thin` provides the added benefit of removing those nasty scrollbar arrows (which are currently masked by the `transparent` scrollbar track)
Before:
After:
> Add scrollbar-width: thin for firefox

- src/style/mixins.scss
- src/tooltip/tooltip.scss
- Removed frosted glass effect from tooltips because unable to find a solution to blurry text issues described in #43.
- Reduced drop shadow from elevation 24 to 8 to have less effect on elements underneath.
**Before:**
**After:**
> Fix tooltip visual issues

- src/button/button.scss
- src/user-icon/classes.scss
Repeating the class name slightly increases the specificity (which got reduced after we removed `.iui-medium` in #34).
This is important because the `.iui-icon` class (which is applied to children of `IconButton` in react) overrides the default dimensions of user icon. We can see this happen in https://github.com/iTwin/iTwinUI-react/pull/45 where we need to put a `UserIcon` inside `IconButton` and it messes up the size.
> Increase specificity of default user icon

- .github/workflows/build.yml
- backstop/tests/button.html
- package.json
- yarn.lock
CI report for test results does not seem to work (maybe format is not proper) so that step is removed.
> junitparser.junitparser.JUnitXmlError: Only one result allowed per test case.
---
Also added `continue-on-error` to `yarn audit` while we wait for dependencies to update postcss. See info in #64 (abandoned)
> Remove CI report and ignore yarn audit in build.yml

- CHANGELOG.md
- src/classes.scss
- src/index.scss
Added header import in global index.scss and classes.scss. This will also make sure it gets included in all.css
> Add missing header imports in barrel

- package.json
- scripts/copyrightLinter.js
- scripts/createComponent.js
Added script to create the following files ("component" refers to component name in kebab-case):
- src/component/component.scss
- src/component/index.scss
- src/component/classes.scss
- backstop/tests/component.html
- backstop/scenarios/component.js
and append barrel import to the following files:
- src/index.scss
- src/classes.scss
Run `yarn createComponent [component]`
e.g. `yarn createComponent side-navigation`
- copyright headers were exported from copyrightLinter.js for reuse
- `makeDir`, `writeFile` and `appendFile` were copied from [iTwinUI-react/scripts/createComponent.js](https://github.com/iTwin/iTwinUI-react/blob/main/scripts/createComponent.js)
> Add createComponent.js for automating boilerplate

- src/header/header.scss
`>` is unnecessary and prevents us from wrapping elements around it. See https://github.com/iTwin/iTwinUI-react/pull/45#discussion_r631998227 (also see #55)
> Fix chevron selector in header

- CHANGELOG.md
- backstop/tests/header.html
- package.json
- src/header/header.scss
Based off of this guide: https://www.aditus.io/patterns/breadcrumbs/
Had to add a few rules to `nav` to preserve layout of children.
> Add nav and aria attributes to header breadcrumbs

- src/style/theme.scss
Tackles this deprecation warning:
> DEPRECATION WARNING: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables. Consider adding `$fallback: null` at the root of the stylesheet.
> 
> 616 │   $fallback: true !global;
>
> Declare $fallback before using it

- yarn.lock
Updated ws to fix https://nvd.nist.gov/vuln/detail/CVE-2021-32640
> Updated vulnerable ws package

- backstop/tests/expandable-block.html
- src/expandable-block/block.scss
The `.iui-content` class name is too generic and has led to multiple problems already, so I've changed it to `iui-expandable-content`.
> Rename expandable block content

- .github/workflows/build.yml
Needed for external PRs to be able to be merged
> Continue pipeline even if Pages deploy fails

- .github/workflows/build.yml
`continue-on-error` still marks the job as failed, so the step should be skipped for PRs coming from forks
> Disable Pages deploy for forked workflows

- .github/workflows/build.yml
Similar to #134. Need to skip this step for PRs created from forks.
> Skip creating Check for forked workflows

- src/side-navigation/side-navigation.scss
Sidenav buttons should have a specificity higher than that of default button so that the order of imports won't matter (to fix #125). This PR increases the specificity by adding redundant selectors in a few places.
> Increase specificity of sidenav-button selectors

- package.json
- yarn.lock
Fixes https://github.com/advisories/GHSA-7p7h-4mm5-852v and https://github.com/advisories/GHSA-ww39-953v-wcq6
> Updated vulnerable packages

- package.json
- yarn.lock
Fixes https://github.com/advisories/GHSA-w7q9-p3jq-fmhm
> Bump jpeg-js to 0.4.3

- src/inputs/checkbox-radio.scss
Added :focus-visible selector to prevent adding focus ring for mouse clicks. Rule will be ignored for unsupported browsers (IE, Safari).
_Could not use `iui-focus` mixin because styles are not set on the focused element (hidden input)._
> Add `focus-visible` to checkbox

- src/table/table.scss
Changed `display: none`/`block` to use `opacity: 0`/`1`. This makes the resizer always be present in the DOM tree, allowing activating it when moving mouse from right to left.
After this, I was able to set z-index to 1 (the resizer needs to be on top of the next column which comes later in the tree).
Can't remove it completely because then it won't be activable when moving from right side:
> Fix column resizer activation

- src/tabs/tabs.scss
Previously (after #10), the user could just pass an svg to pill tabs without needing to provide size or class. After #156, this behavior was changed.
To avoid breaking user apps, I've added back the svg selector with a deprecation note.
> Add svg selector to tab icons for backwards compatibility

- src/code/codeblock.scss
- src/style/typography.scss
- Added system font fallback options for `$iui-sans`.
- Added system font fallback options for `$iui-monospace` and changed the order slightly.
- Codeblock now uses `$iui-monospace` correctly. 
Created in response to [this PR comment in iTwinUI-React](https://github.com/iTwin/iTwinUI-react/issues/182#issuecomment-875758633). Used [this blog post](https://qwtel.com/posts/software/the-monospaced-system-ui-css-font-stack/), [this blog post](https://infinnie.github.io/blog/2017/systemui.html), & [this blog post](https://markdotto.com/2018/02/07/github-system-fonts/#the-stack) to come up with the correct stack.  We removed `system-ui` so that tests would pass, plan to re-add it back when we bundle Open Sans.
> Add font family fallback options

- src/tabs/tabs.scss
After https://github.com/iTwin/iTwinUI-react/pull/181, there is no need for the `svg` selector, as we are forcing users to use our component (which applies the class automatically).
> Remove svg selector from tabs

- backstop/tests/breadcrumbs.html
- src/breadcrumbs/breadcrumbs.scss
- src/breadcrumbs/classes.scss
- Last breadcrumb is no longer an anchor link, is instead a span.
- Reduced specificity across the board.
> Use span instead of anchor for current location within breadcrumb

- backstop/tests/badge.html
- src/badge/badge.scss
Forcing inline background-color style increases specificity, so I've changed the approach to use a new inline css variable instead (`--badge-color`).
Passing an inline background-color is still possible but this allows extra flexibility.
> Use css variable for badge color

- src/style/typography.scss
Declared new fallback variable to use system fonts in the iui-font-family mixin, in response to https://github.com/iTwin/iTwinUI-react/issues/182#issuecomment-892181370
> Update fallback fonts in iui-font-family mixin

- .github/workflows/pr.yml
- .github/workflows/publish.yml
- .github/workflows/release-please.yml
- CONTRIBUTING.md
Added two new workflows:
- `release-please.yml`: uses the [release-please](https://github.com/googleapis/release-please) action to automatically create a release PR and update changelog.
- `pr.yml`: uses a custom script to ensure that PR title follows the conventional commits spec.
Updated:
- `publish.yml`: the release-please action includes the package name in release title, so I'm removing it.
- `CONTRIBUTING.md`: removed details about changelog.
> ci: Add workflow for release automation

- .github/workflows/pr.yml
Previously, the link included the parentheses and period:
> ci: Fix link in pr.yml

- .github/workflows/build.yml
Caching is now supported in [`actions/setup-node`](https://github.com/actions/setup-node/releases/tag/v2.2.0) so I've replaced `actions/cache`.
Also changed `yarn audit:ci` to `yarn audit`.
> ci: Update `actions/setup-node` to use built-in caching

- .github/workflows/pr.yml
- .github/workflows/release-please.yml
Correct param is `release_id` not `id`.
Refs: https://github.com/iTwin/iTwinUI/actions/runs/1151405731 and https://octokit.github.io/rest.js/v18#repos-update-release
> ci: fix typo in release title workflow

- src/wizard/wizard.scss
- src/wizard/workflow.scss
Changed `:last-child` selectors to `:last-of-type` because tooltips are normally placed after last step in the DOM.
Before (with `:last-child`):
After (with `:last-of-type`):
> fix(Wizard): allow placing tooltip inside wizard wrapper

- src/tabs/tabs.scss
Before:
After applying `white-space: nowrap`:
> fix(Tabs): vertical tabs shouldn't wrap

- backstop/scenarios/wizard.js
- backstop/tests/wizard.html
- src/wizard/wizard.scss
Moved focus selectors and tabindex from iui-wizard-circle into iui-wizard-step.
Kept styling on circle.
Removed aria-selected attribute from html.
> fix(Wizard): focus is now applied on step, not circle

- yarn.lock
Fixes https://github.com/advisories/GHSA-qq89-hq3f-393p
> chore(deps): Bump tar from 6.1.3 to 6.1.11

- src/inputs/checkbox-radio.scss
#232 broke loading checkboxes:
After fix:
> fix(Checkbox): loading checkmark is now styled correctly

- .github/workflows/build.yml
- backstop/tests/alert.html
Disabled `Host test results on gh pages` to prevent hosting test results for failed builds on main branch (because build should never fail for legit reasons on main branch).
The problem was happening because `github.event.number` is undefined on main branch and it was putting the test results in the root folder. If we really want to host the test results for main branch, we could change target folder.
> ci: Fix index.html getting removed on failed builds

- src/menu/menu.scss
`iui-focused` class can now be applied on menu item to emulate focus styling when it is not possible to *actually* set focus on the item.
Will be used in typeahead/combobox component. Notice how input is focused but menu item has emulated focus:
> feat(MenuItem): Add `iui-focused` class to emulate focus styling

- src/slider/slider.scss
If no min / max label or icon are present the slider would get a height of 0. Added `min-height` to force a height.
> fix(Slider): Add min-height

- src/menu/menu.scss
Moved text color from iui-menu-item into iui-menu so that it can be inherited by iui-menu-content as well.
Fixes #368
> fix(Menu): Apply text color on menu root

- backstop/tests/table.html
- src/style/mixins.scss
- src/table/table.scss
Adds `iui-scroll-snapping` mixin to `.iui-table-body` to enable Y-axis scroll snapping. Closes #378.
> feat(Table): Add scroll snapping

- src/inputs/classes.scss
- src/inputs/labeled-inputs.scss
Improvements to `iui-input-label`:
- Set default `display` to `block`, because it was placing inline elements next to it.
- Before (span in pink, should have been in next line):
- Changed to `display: inline-flex` when iui-inline is set, and fixed alignment.
- Before:
- Added left margin to the required asterisk pseudo-element.
- Without margin, space is not respected in inline display:
> fix(Label): Change display style according to modifier

- src/button/button-group.scss
- src/table/paginator.scss
Changed z-index approach to rely on `display: flex` instead of `position: relative` to fix this weird bug:
Also changed logic a little to give focus priority over hover, and added correct focus-visible behavior.
> fix(ButtonGroup): Use flex instead of position to set z-index

- src/button/button-group.scss
Added `position: relative` to child selector to fix the issue in storybook (#418 didn't fix it). Previously it was set on hover/focus/disabled states but now it's always set regardless, and it seems to fix the issue in Chrome 96
> fix(ButtonGroup): Add back position: relative to fix z-index issue

- src/button/button-group.scss
- src/table/paginator.scss
Reset base transition-duration to disable _exit_ animation on hover/focus to prevent border flicker when moving between buttons. Added back transition-duration for hover/focus to enable _enter_ animation.
Before:
After (slowed down):
> fix(ButtonGroup): Disable exit animation to prevent flicker

- src/button/button-group.scss
- src/table/paginator.scss
Now using owl selector (* + *) instead of last-child to lower specificity. Flipped from margin-right to margin-left.
> chore(button-group): Reduce specificity of negative margin

- backstop/tests/menu.html
2 of the dropdown buttons within `menu.html` were missing the `.iui-default` class.
> fix(Menu): Add missing class name for button dropdowns

- src/tree/tree.scss
Fixed focus on tree nodes, removed focus outline that showed when selecting and unselecting tree nodes.
Before:
After:
> fix(Tree): Fix tree focus

- src/table/table.scss
After adding VirtualScroll https://github.com/iTwin/iTwinUI-react/pull/236, some styles broke as noticed in https://github.com/iTwin/iTwinUI-react/pull/236#discussion_r793049030
After checking the selectors, I think only Zebra rows were looking for direct children.
Changed this one which should fix the issue.
> fix(Table): Zebra row selector change

- src/classes.scss
- src/index.scss
- src/popover/classes.scss
- src/popover/index.scss
- src/popover/popover.scss
It is meant to be used only in React as it helps to easily hide tooltips, menus and other these kind of components when they are out of view.
This should help to fix https://github.com/iTwin/iTwinUI-react/issues/529
> fix: Added Popover helper class

- src/button/button.scss
There was a huge accessibility oversight in #166 as it completely breaks focus styles in older versions of Safari and IE. `outline: none` should almost never be used except inside `:focus-visible` sometimes. I've removed it so that the default focus outline is shown in older browsers which dont support `@supports selector`.
> fix(Button): Show default outline as fallback

- src/inputs/radio.scss
Apparently, [it is possible](https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate#:~:text=%3Cinput%20type%3D%22radio%22%3E%20elements%2C%20when%20all%20radio%20buttons%20with%20the%20same%20name%20value%20in%20the%20form%20are%20unchecked) for radio inputs to be in the indeterminate state, so in the current implementation they get the unchecked svg.
This change will explicitly set the mask image to use a blank svg.
> fix(Radio): Set blank svg for indeterminate state

- src/color-picker/color-picker.scss
Not sure how it was working in color-palette before, without any positioning specified.
Before:
After:
> fix(ColorSwatch): Fix absolute positioning when used in button

- .github/workflows/build.yml
This should fix the failing build in main branch.
> ci: Exclude main branch when creating check

- backstop/tests/carousel.html
- src/carousel/carousel.scss
Instead of trying to dynamically calculate the `translateX` value in JS, I'm now using scroll snapping with a hidden scrollbar. The transition is handled using `smooth` scrolling.
Scroll snapping provides tons of benefits:
- free support for dragging on touch devices
- automatically scroll to the focused slide (no need to disable focusing for hidden slides)
- allow showing multiple slides (not possible previously because `translateX` was relying on % width)
From JS part, scroll can be triggered by simply calling `scrollIntoView`, but for synchronizing the auto-scroll cases mentioned above, I think we would need IntersectionObserver or something. 🤔
> feat(Carousel): Use scroll-snap instead of transform

- src/carousel/carousel.scss
Using `display: none` removes the dot from accessibility tree so I'm now using visually hidden styles. Also removed the background-color as it's not necessary when the dot is not even visible.
> fix(Carousel): Make invisible dot visually hidden

- src/alert/alert.scss
- src/inputs/labeled-inputs.scss
- src/progress-indicator/linear.scss
- src/style/global.scss
- src/style/mixins.scss
- src/table/table.scss
- src/toast-notification/categories.scss
These components use `::selection`:
- Alert
- Labeled inputs
- Progress indicator
- Table
- Toast notification
This PR adds `@mixin iui-text-selection;` so the opacity is always in sync across components.
> chore(Styles): Add text selection mixin

- src/inputs/radio.scss
The `iui-checkbox` mixin already includes the wrapper smixin so it doesn't need to be included again.
> fix(Radio): Remove redudant wrapper styles

- .github/workflows/publish-npm.yml
- .github/workflows/release-please.yml
Moved npm publish into separate file so that it's possible to trigger it manually using `workflow_dispatch`.
Also now reusing that workflow in release-please through the `workflow_call` trigger.
> ci: Allow publishing to npm manually

- .github/workflows/release-please.yml
The recent auto-publishing to npm failed: https://github.com/iTwin/iTwinUI/runs/5644297298?check_suite_focus=true
The error message suggesting adding checkout, so my hope is that this will be enough to fix it.
> ci: Add checkout to release workflow

- .github/workflows/build.yml
- backstop/tests/alert.html
Using `always()` allows the step to be called when there is a failure in a preceeding step. This will fix the gh-pages link not getting posted after #497.
> ci: Fix gh-pages link using `always()` in if condition

- src/information-panel/information-panel.scss
Using `visibility: hidden` makes the content inside non-focusable. Fixes #478
> fix(InformationPanel): Prevent focusing hidden panel content

- .github/workflows/build.yml
- src/alert/alert.scss
Just revert the script to previous code.
If my guess is right, we would have only issue when failed tests are rerun and we have deploy step marked as red.
But if this fixes our current deployed pages issues, I think it is fine for now.
> ci: revert build script

- src/date-picker/date-picker.scss
As I removed explicit width from DatePicker and we have `fit-content` in all our css, I didnt notice that this will happen...
Switched to `inline-grid` to fix this.
> fix(DatePicker): Make element inline

- .github/workflows/release-please.yml
According to [this doc](https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow), calling workflow should be done directly within the job, not steps.
So hopefully, this fixes
https://github.com/iTwin/iTwinUI/runs/5716829567?check_suite_focus=true
> chore: fix reusing workflow syntax

- .github/workflows/publish-npm.yml
- .github/workflows/release-please.yml
So our auto release is failing and the guess is that it needs auth token to be passed explicitly to the reused workflow.
> chore: Pass auth token on auto release

- src/tree/tree.scss
Closes #567 
I needed to increase margin left to child icon, after switching from padding to margin for the icon itself.
> fix(Tree): Fix spacing for tree node icon

- src/color-picker/color-picker.scss
- Add `forced-color-adjust: none;` on color swatches, color field, and slider rails.
Before:
After:
> fix(ColorPicker): Add `forced-colors` support.

- src/toast-notification/classes.scss
Increased z-index to the same value as we have for popover as toasts were not visible in modal frontstage in itwin.js.
Ideally, I think we should reuse Popover for toasts, modals, so we are sure our components are always visible.
> fix(Toast): Increase z-index

- scripts/generateCss.js
Added `fs.existsSync` to check if `classes.scss` is present before trying to compile it. Fixes #599
If the compilation does fail for some reason, then the path will be shown.
> chore: Improve build script and error handling

- src/radio-tile/radio-tile.scss
Previously, the `svg` selectors only targetted the children of `iui-radio-tile-icon`, which worked for icon web components used in the css demo pages, but not for regular `svg` components used in React. 
This fix works for both cases while keeping the maximum specificity at `(0, 3, 0)`.
> fix(RadioTile): Icon `svg` selector for regular svgs

- backstop/tests/breadcrumbs.html
- src/breadcrumbs/breadcrumbs.scss
- src/breadcrumbs/classes.scss
Both `.iui-breadcrumbs-item-overrides > *` and `.iui-button` selectors have the same specificity, so `.iui-button` props are placed after the `.iui-breadcrumbs-item-overrides > *` props in CSS because of alphabetical order. This does not happen in React.
The only prop that `.iui-button` overrides is `color`. `iui-breadcrumbs-item-overrides` is temporary and will be removed once we have implemented `iui-breadcrumbs-button`.
> fix(Breadcrumbs): `color` is not updating

- src/file-upload/file-upload.scss
- src/information-panel/information-panel.scss
- src/radio-tile/radio-tile.scss
- src/slider/slider.scss
- src/table/table.scss
- src/tile/tile.scss
- src/toggle-switch/toggle-switch.scss
These are the following components I looked at when modifying z-index values
**button-group.scss**
- z-index values are used for prioritizing overlapping borders for disabled, hovered, and focused buttons
- **Solution:** I left this alone.
**file-upload.scss**
- z-index value was used so that `cursor: pointer` is applied to `iui-browse-input`, but the size of the element is really small and I'm not sure why it isn't `0 x 0`.
- **Solution:** Removed z-index.
**information-panel.scss**
- z-index was used to make sure the information panel was in front of the column resizer. However, since the information panel comes after the table in the HTML I don't see a need for it.
- **Solution:** Removed z-index for both information panel and table resizer.
**radio-tile.scss**
- Similar to button …
> chore: Clean up z-index values

- src/table/table.scss
My sticky columns PR apparently broke Table resizing that after some point header wouldn't reduce in size while body still can:
> fix(Table): Allows to resize table header as before

- .github/workflows/publish-npm.yml
- packages/itwinui-variables/package.json
Syntax was invalid previously. `inputs` should go under triggers and `type: string` is required.
Manually dispatching the workflow will now show a dropdown:
Successfully tested publishing a dev version of itwinui-variables: https://github.com/iTwin/iTwinUI/actions/runs/2637306789
Calling the workflow from other workflows also supports passing the `package` input.
> ci: Fix `inputs` syntax for npm publish

- package.json
- yarn.lock
`yarn audit` found that `glob-parent` is vulnerable and needs update.
> chore: Updated vulnerable glob-parent

- packages/itwinui-css/src/table/table.scss
> fix(Table): Zebra stripes content no longer goes on top of stick column

- .github/workflows/publish-npm.yml
From https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#example
> ci: Fix npm publish not detecting package

- packages/itwinui-css/backstop/tests/menu.html
- packages/itwinui-css/src/menu/menu.scss
- Add `--iui-menu-max-height` to `.iui-scroll` modifier.  Variable is unset in SCSS, value is set in demo `<head>`.
- Use `:where` to keep specificity at 0,1,0.
Closes #733.
> feat(Menu): Add CSS variable for max-height on scrollable menu

- packages/itwinui-css/src/style/global.scss
- packages/itwinui-css/src/utils/classes.scss
- packages/itwinui-css/src/utils/index.scss
- packages/itwinui-css/src/utils/mixins.scss
- packages/itwinui-css/src/utils/visually-hidden/classes.scss
- packages/itwinui-css/src/utils/visually-hidden/index.scss
- packages/itwinui-css/src/utils/visually-hidden/visually-hidden.scss
Was working on global styles when i noticed that `iui-visually-hidden` is just sitting in `global.scss` for no reason, so I've moved it to utils.
Also noticed that `iui-display-none` is not used anywhere so removed it.
> feat: Move visually-hidden from global to utils

- packages/itwinui-css/src/table/table.scss
I changed all `visibility: hidden` to `opacity: 0` and all `visibility: visible` to `opacity: revert`. This helps to solve the problem of keyboard navigation in the table in the react repo.
I tried to use `iui-visually-hidden` and `iui-visually-hidden-revert`, but it negatively affected the look of the table. I thought this was the better solution to 1) keeping the button in the DOM, 2) keeping the button dimensions the same throughout, and 3) allowing keyboard navigation.
Goes with https://github.com/iTwin/iTwinUI-react/pull/802
> fix(Table): Keyboard Navigation Support

- packages/itwinui-css/src/checkbox/checkbox.scss
Visibility checkboxes only require `outline-width: 1px` due to no visible border.  Was inheriting `outline-width: 2px` from non-visibility checkboxes.
**Before:**
**After:**
> fix(Checkbox): Change `outline-width` for visibility checkboxes

- packages/itwinui-css/backstop/tests/dialog.html
- packages/itwinui-css/src/dialog/classes.scss
- packages/itwinui-css/src/dialog/dialog.scss
1. Changed from `position: relative` to `position: fixed` and added a modifier `data-iui-relative` for `position: absolute`
2. Removed sizing rules from draggable dialog because they are already set in default dialog
After spending some time on it, I was unable to remove default placement rules from draggable dialog because the JS (in itwinui-react) relies on it to calculate the initial position.
> fix: Make dialog positioned and remove unneeded styles

- package.json
Closes #748
* Added aliases for commands in `CONTRIBUTING.md` with no specified folder to run in (so users assume to run in root):
* [`createComponent`](https://github.com/iTwin/iTwinUI/blob/main/CONTRIBUTING.md#adding-a-new-component)
* [`approve`](https://github.com/iTwin/iTwinUI/blob/main/CONTRIBUTING.md#how-to-run-tests)
* [`clean:images`](https://github.com/iTwin/iTwinUI/blob/main/CONTRIBUTING.md#how-to-run-tests)
> chore: Added aliases in root for commands in css package

- packages/itwinui-css/backstop/scenarios/footer.js
- packages/itwinui-css/backstop/tests/assets/demo.css
- packages/itwinui-css/backstop/tests/assets/theme.js
- Add ability to switch the `<body>` background color between 1 & 2 from within `theme.js`.
- Updated visual styling within `theme.js`.
- Page settings button is now fixed top right of the viewport to prevent needing to scroll to the top of the page to adjust settings.
- Hiding the page settings button in `footer.js` test images.
I found this useful when working on #762.
> chore: Add demo page background color switcher

- packages/shared/copyrightLinter.js
Our build was causing this warning:
```
@charset must precede all other statements.
```
So I've modified the copyright linter to insert the comment *after* the `@charset` rule.
> chore: Fix `@charset` warning caused by copyright banner

- packages/itwinui-css/src/utils/input-container/input-container.scss
Fixes #794.
In the following snippet:
```css
height: calc(100% - 4px);
margin-right: 2px;
border-radius: var(--iui-border-radius-1);
```
- The `-4px` in height prevents it from overlapping the top and bottom outlines.
- The 2px right margin prevents it from overlapping the right outline.
- The border radius prevents it from clipping the rounded corners.
> fix(Select, ComboBox): Fix icon to not overlap outline

- packages/itwinui-css/backstop/tests/alert.html
- packages/itwinui-css/src/alert/alert.scss
- packages/itwinui-css/src/alert/classes.scss
- **Use `class="iui-alert" data-iui-status="informational"`.** In #623 we changed from using `.iui-alert .iui-informational` to `.iui-alert-informational` to achieve lower specificity.  We want to keep the base `.iui-alert` for targeting regardless of status.
- **Use `class="iui-alert" data-iui-variant="sticky"`**.
Specificity is under 0, 3, 0 & `alert.css` went from 406 lines to 310.
> feat(Alert): Use data attributes

- packages/itwinui-css/backstop/tests/index.html
- packages/itwinui-css/package.json
- packages/itwinui-variables/package.json
This will allow modern tools to import using the following paths:
```js
import '@itwin/itwinui-css';
import '@itwin/itwinui-css/all';
import '@itwin/itwinui-css/global';
import '@itwin/itwinui-variables';
```
The `./*` is used to allow internal imports.
```js
import '@itwin/itwinui-css/css/all.css';
import '@itwin/itwinui-css/css/alert.css';
import '@itwin/itwinui-variables/index.css';
import '@itwin/itwinui-variables/os.css';
```
The build is passing and the pages are displaying correctly which means it's working. We are using a lot of different combinations of the above in our html pages. I changed one of the imports to `import '@itwin/itwinui-css/global'` just to double confirm.
> feat!: Add export maps

- packages/itwinui-css/src/utils/notification-marker/classes.scss
- packages/itwinui-css/src/utils/notification-marker/notification-marker.scss
- packages/itwinui-variables/src/index.scss
`:root` and `[data-iui-theme=light]` selectors can be combined to reduce duplication.
Also noticed that sass was complaining about `white` (apparently it thinks it's the color white) so I added quotes around it.
> fix(variables): Combine `:root` and light theme selector

- packages/itwinui-css/scripts/createComponent.js
- `yarn createComponent` now appends the component's classes to `all.scss` instead of `src/classes.scss`. 
- `yarn createComponent` no longer appends the component's index to `src/index.scss`.
- Removed excess slashes
Closes #776
> chore(createComponent): Targets `all.scss` instead of `classes.scss`

- package.json
- yarn.lock
Fixes npm audit failing from https://github.com/advisories/GHSA-w573-4hg7-7wgq.
Turns out we were force resolving the wrong minor version of `braces`. Removing it from resolutions makes it resolve to minor version `3` which does not have a vulnerable dependency on `decode-uri-component`.
> chore(dev-deps): Bump `braces`

- packages/itwinui-css/backstop/tests/progress-indicator.html
- packages/itwinui-css/src/progress-indicator/classes.scss
- packages/itwinui-css/src/progress-indicator/overlay.scss
Main code change: removed `pointer-events: none`. Not sure why we had it before.
Also:
- removed tabindex and focus rule from overlay
- added `inert` attribute to content to fix focus, with polyfill for firefox
- moved `iui-overlay-exiting` class to `classes.scss` (unrelated change, because it was confusing me when reading the mixin)
Fixes #826
> fix: Progress overlay should intercept clicks

- packages/itwinui-css/src/code/code.scss
Removed `user-select: all` because it is bad from a usability perspective. It breaks lots of expected behaviors like being able to select part of the text or triple-click to select the whole line.
Also removed `iui-reset` because most of those delcarations are unnecessary (either they are the default or they are being overridden or both).
> fix(Code): Remove `user-select: all` and extra declarations

- packages/itwinui-css/vite.config.ts
Reverts iTwin/iTwinUI#853
excluding it from the componentList results in the file not even being generated, so https://itwin.github.io/iTwinUI is currently 404ing
> Revert "chore: Remove `index.html` anchor from demo page"

- packages/itwinui-react/jest.config.js
Fixes #874 by ignoring telling jest to ignore the test files built by swc.
Also fixed formatting of jest config to remove extra newlines.
> chore: Fix jest trying to run transformed test files

- apps/website/package.json
- package.json
- packages/itwinui-css/package.json
- playgrounds/astro/package.json
- yarn.lock
After #868, `astro-playground` and `website` were failing with cryptic errors.
These errors were happening because:
1. we force resolve `node-fetch` to `2.6.7` to fix a vulnerability (#453)
2. astro relies on `node-fetch` version `3` when using node 16. so it was trying to use `node-fetch` v2 as if it was v3, which of course doesn't work.
So to fix this, all I really did is updated a bunch of deps, most important one being `backstopjs`. Previously, we were on backstopjs `6.0.4` which uses puppeteer `12` which has a hard dependency on `node-fetch` version `2.6.5` (hence the need for force resolution). Upgrading backstopjs to `6.0.5` bumps puppeteer to `14` which no longer uses `node-fetch`, so the force resolution is not needed. This means astro can safely use `node-fetch` version `3`. …
> chore: Fix errors in astro workspaces

- LICENSE.md
- packages/itwinui-css/LICENSE.md
- packages/itwinui-react/LICENSE.md
- packages/itwinui-variables/LICENSE.md
Legally this should not be a requirement (some _very_ popular packages like [react](https://unpkg.com/react/LICENSE) don't include the year), but it's "policy" so I've added the year range in all licenses.
This is now one more thing we need to update every year, in addition to the footer (#945)
> chore: Update copyright notice year in all licenses

- .editorconfig
- .stylelintrc.json
- .vscode/settings.json
- packages/configs/package.json
- packages/configs/prettier-scss-config.js
- packages/itwinui-css/backstop/engine_scripts/puppet/browserActionsHelper.js
- packages/itwinui-css/backstop/scenarioHelper.js
- packages/itwinui-css/backstop/scenarios/dialog.js
- packages/itwinui-css/backstop/tests/assets/demo.css
- packages/itwinui-css/backstop/tests/assets/theme.js
- packages/itwinui-css/package.json
- packages/itwinui-css/scripts/pushDocker.js
- packages/itwinui-css/scripts/watchScss.mjs
- packages/itwinui-css/vite.config.ts
Before #868, we were relying on `editorconfig` which sets a line length of 120. This is now set in prettier.
This will fix the unintentional formatting changes we saw in https://github.com/iTwin/iTwinUI/pull/935#discussion_r1057810187 and https://github.com/iTwin/iTwinUI/pull/860#discussion_r1060937554
Also noticed and fixed stylelint was missing from fixOnSave (bad merge in #868).
> chore: Fix prettier config in itwinui-css

- packages/itwinui-css/vite.config.ts
Closes #744 
* Removed `index` anchor link from the HTML demo page.
* Unrelated change: removed unused `lightningCssPlugin()` from `vite.config.ts` since after #935, lightningcss postprocessing is done in the watch script instead of a vite plugin.
- ~[ ]~ Add meaningful unit tests for your component (verify that all lines are covered)
- ~[ ]~ Add component features demo in Storybook (different stories)
- ~[ ]~ Approve test images for new stories
- ~[ ]~ Add screenshots of the key elements of the component
> chore: Remove `index` anchor from html demo page

- .github/workflows/build.yml
Build/tests should run on all PRs, not just those created against `main`.
In addition to the "v1" case mentioned in https://github.com/iTwin/iTwinUI/pull/977#discussion_r1065024847, this could also be useful for:
- chained PRs (branches based on other branches based on `main`)
- backporting fixes to legacy branches
N/A
N/A
> Run CI on all PRs

- packages/itwinui-react/src/core/Avatar/Avatar.tsx
* When going through `Avatar.tsx`, I noticed that the JSDocs for the `image` props was rendering the `<img>` element. So this is a small fix to render it as a codeblock.
* I also searched other similar places using the regex `\*.*<[a-z]+` and found none.
N/A
N/A
> chore(Avatar): Show `<img>` in JSDocs as a codeblock

- packages/itwinui-react/src/core/utils/components/Icon.tsx
forwardRef was missed in original PR. It is useful for DOM manipulation and adding things like tooltips.
Not needed, it is standard in many components.
No changeset needed because Icon is not released yet.
> Add missing `forwardRef` in Icon

- .github/workflows/changeset-release.yml
Looks like #1000 didn't do it. Token might need to be used for the checkout step too. https://github.com/changesets/action/issues/187#issuecomment-1228413850
N/A. Will need to wait for CI to run on #996.
N/A
> Use PAT for changeset workflow checkout

- packages/itwinui-css/backstop/tests/header.html
- packages/itwinui-css/backstop/tests/menu.html
I noticed that some images for [`header.html`](https://itwin.github.io/iTwinUI/css/header.html) were showing as broken. This happened only on the deployed version but not on the localhost version, not sure why. This PR makes small fixes to the image path.
I also searched for `../assets/` and found two occurrences in `menu.html`. Corrected the path there too.
I verified that the images show correctly in the deploy preview for the PR.
N/A
> Fix broken links on html demo pages

- .github/workflows/changeset-release.yml
Reverts #1001 because it is not working and the changeset workflow fails entirely 😔. Will need to figure something else out.
> Revert "Use PAT for changeset workflow checkout"

- .github/workflows/changeset-release.yml
Reverts #1009. In other words, reintroduces #1001.
Recently, I made two changes: #1000 and #1001.
After merging #1000, I noticed that it didn't fix the issue. It was updating the release PR (#996) but not running the build and tests. So I created #1001.
After merging #1001, I noticed that the changeset workflows were failing, so #996 was not being updated anymore.
So I reverted #1001 in #1009 but it didn't change anything.
Then I guessed that the token was bad, so I asked @FlyersPh9 to reauthorize SSO. After that, I re-ran the workflows at two different points and found that #1001 does work correctly! Tests automatically run.
But it's using the wrong username (because @FlyersPh9 created the PAT), so to fix that I'm trying to see if setting the committer name/email manually works. …
> Use PAT for changeset workflow checkout (again)

- apps/website/src/components/LeftSidebar.astro
- apps/website/src/examples/Alert.sticky.tsx
- apps/website/src/examples/Blockquote.main.tsx
- apps/website/src/examples/DropdownMenu.main.tsx
- apps/website/src/examples/Keyboard.main.tsx
- apps/website/src/examples/NonIdealState.main.tsx
- apps/website/src/examples/ProgressLinear.main.tsx
- apps/website/src/examples/RadioTile.main.tsx
- apps/website/src/examples/Slider.main.tsx
- apps/website/src/examples/Surface.main.tsx
- apps/website/src/examples/Table.main.tsx
- apps/website/src/examples/Tabs.main.tsx
- apps/website/src/examples/Tree.main.tsx
- apps/website/src/pages/docs/alert.mdx
- apps/website/src/pages/docs/carousel.mdx
- apps/website/src/pages/docs/combobox.mdx
- apps/website/src/pages/index.astro
- Added some fixes to examples (styling, width, padding)
- Fixes `Icons` link in home page
We need to re-think LiveExamples to not include inline styles.
Open pages and check how it looks.
N/A
> website: Example hotfixes

- .changeset/kind-zoos-boil.md
- packages/itwinui-react/src/core/Buttons/DropdownButton/DropdownButton.test.tsx
- packages/itwinui-react/src/core/Buttons/DropdownButton/DropdownButton.tsx
- packages/itwinui-react/src/core/DropdownMenu/DropdownMenu.tsx
Added `dropdownMenuProps` to give user full control over the `DropdownMenu` which wraps the button. Closes #1028.
We are going to get rid of `tippy.js` so this prop will be removed in the next major release, but it's pretty useful to have right now.
Basic unit test added. Didn't add visual test. This doesn't need extensive testing because it is not really a new feature, it's just propagating the props.
Changeset added.
> DropdownButton: Add dropdownMenuProps

- packages/iTwinUI-react/CHANGELOG.md
- packages/iTwinUI-react/src/core/utils/hooks/useIntersection.tsx
same as #1024
changelog entry has been manually added and simplified.
> backport "the one that fixes useIntersection cleanup for react 18"

- .github/workflows/build.yml
- .github/workflows/changeset-release.yml
- .github/workflows/publish-npm.yml
- .github/workflows/publish-storybook.yml
- CONTRIBUTING.md
- apps/storybook/package.json
- yarn.lock
Node 16 is no longer the active LTS version. When you go to https://nodejs.org, it prompts you to install Node 18, not 16.
Storybook does not work out of the box with Node 18 because it uses some old version of webpack internally. See issues: https://github.com/storybookjs/storybook/issues/20482 and https://github.com/storybookjs/storybook/issues/20209
This is possible to work around by using `NODE_OPTIONS=--openssl-legacy-provider`.
It's a bit silly that the latest stable version of storybook does not work with the latest stable version of node. Apparently this will be fixed in storybook 7, which won't be released until March this year. This workaround will avoid issues with new contributors in the meantime.
Also, node 16 users are unaffected.
Tested locally by switching to node 18.
I've …
> use node 18

- .github/workflows/changeset-release.yml
Instead of @FlyersPh9's PAT, changesets will now use the PAT for the @imodeljs-admin account. It is provided to us as an organization-level secret.
Will only be able to test after merging this PR and waiting for changesets to do its thing.
N/A
> Replace personal PAT with org PAT

- apps/website/src/components/variables/SizesDemo.astro
"foreground-primary" doesn't exist anymore (this page was made before the v2 release), replaced with "text-accent".
Before:
After
N/A
> website: Fix color in SizesDemo

- .changeset/nice-toys-collect.md
- packages/itwinui-react/src/core/Table/TablePaginator.test.tsx
- packages/itwinui-react/src/core/Table/TablePaginator.tsx
Specify type='button' to prevent postbacks when pager is used in forms.
Fixes issue #1053 
Copy/pasted sample from https://codesandbox.io/s/paging-page-refresh-w0bpoh?file=/App.tsx in vite playground to verify pager buttons no longer postback.
N/A
> Specify type='button' on paginator buttons

- .github/workflows/build.yml
Currently if "optional" steps fail (such as uploading test results to github-pages or posting a link to it) for any reason, then it fails the whole step, which is not ideal. The failure often happens due to issues with permissions (e.g. bot user or external contributor).
This PR will make them not be marked as failures (big prominent ❌).
When the actual tests fail, they will still be marked as failures (❌).
N/A. Will need to wait and see how CI behaves..
N/A
> CI: do not error when publishing test results fails

- .github/workflows/build.yml
`merge_group` alone does not currently work so added `gh-readonly-queue/main/*` branch filtering. Based on [community suggestion](https://github.com/orgs/community/discussions/46757#discussioncomment-4908280).
N/A
N/A
> Run CI on pushes to gh-merge queue branches

- .changeset/clever-moons-clap.md
- packages/itwinui-react/src/core/utils/components/VirtualScroll.tsx
React 18 automatically batches all updates, but React 17 doesn't. We can opt into this by using `unstable_batchedUpdates`, which fixes #1050.
Yes, this is an "unstable" API, but it will be around for the forseeable future and I've added a noop fallback just in case. See https://github.com/reactwg/react-18/discussions/21
Tested by manually replicating this sandbox in vite playground: https://codesandbox.io/s/itwinui-react-example-forked-qk7dyt?file=/src/index.tsx
> fix VirtualScroll minHeight update for react 17

- .github/workflows/build.yml
- Removed `gh-readonly-queue` filter from `push` trigger. This was previously added because the `merge_group` trigger was broken.
- Added extra filtering to the gh-pages deploy job, so that it will be skipped for the `merge_group` trigger. This will prevent CI from failing (see [failure](https://github.com/iTwin/iTwinUI/actions/runs/4145520173)).
TBD
N/A
> Skip gh-pages deploy for merge queues

- .changeset/thirty-bugs-clean.md
- packages/itwinui-css/src/checkbox/checkbox.scss
Flex centering is not necessary on checkbox labels. It breaks inline elements, especially at narrow widths, so I've removed it.
Fixes #845
All existing tests should pass.
Also manually tested this code from the linked issue description:
```html
<label class="iui-checkbox-wrapper">
<input class="iui-checkbox" type="checkbox" />
<span class="iui-checkbox-label">I agree to the <a href="#" class="iui-anchor">terms of service</a>.</span>
</label>
```
It wraps correctly.
Changeset added.
> Remove flex centering from checkbox labels

- .github/workflows/build.yml
Our css tests often time out and keep running indefinitely.
So I'm now using [`nick-fields/retry`](https://github.com/nick-fields/retry) to retry if tests are still running after 15 mins.
CI should pass in this PR. In general, we'll have to observe how this behaves after it's merged.
N/A
> Retry css tests if timeout

- .changeset/brave-dragons-sparkle.md
- packages/itwinui-react/src/core/Table/hooks/useColumnDragAndDrop.tsx
Fixed a bug which gave users an unexpected column order when columns were hidden, reordered, and then shown
Fixes #892 
Before:
After:
N/A
> fix(Table): Fixed reordering column behavior when columns are hidden

- .changeset/violet-ligers-itch.md
- packages/itwinui-css/src/tooltip/tooltip.scss
I was trying out something in a sandbox, when I noticed that the tooltip opacity makes it really hard to read when there is text behind the tooltip. So I'm making the background blurry.
Looks perfectly fine in my testing on M1 Macbook and personal Windows PC.
I believe we had this 2 years ago but removed it because it was causing some blurry text (in react, not css). See #43. So I would like other Windows users to verify.
> blurred background on tooltip

- .changeset/heavy-ligers-marry.md
- packages/itwinui-react/src/core/ComboBox/ComboBox.test.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBox.tsx
Solves #1115 
Updated `getSelectedIndexes` to check if user provided index is valid (exists in options).
To test this copy-paste user provided example and run our test app.
Added unit test for this case.
N/A
> Update combobox to not crash

- .changeset/loud-hats-perform.md
- packages/itwinui-react/src/core/Header/HeaderLogo.test.tsx
- packages/itwinui-react/src/core/Header/HeaderLogo.tsx
Closes #920
`as` prop will allow rendering the HeaderLogo as a link, with correct hover states. Also removed some extra code that is not necessary - previously we were always rendering a `<div>` and doing extra work to turn it into button when `onClick` was passed.
The `as` prop will now default to `div` when no `onClick` passed, and `button` when one is passed.
Updated existing unit tests and added new unit test for `as` prop.
Also inspected dom in stories/playground and it was rendering the correct element.
> add `as` prop to HeaderLogo

- .changeset/afraid-zoos-double.md
- packages/itwinui-css/src/table/table.scss
Noticed an issue where the Table header was misaligned with Table body in firefox. We actually already had a workaround for Firefox in place, but it was only partially working because it was occupying invisible space. So I've updated it to have a background-color.
Before this change, this is how it looks in Firefox:
After this change, this is how it looks in Firefox:
> fix Table header misalignment in firefox

- .changeset/odd-trees-return.md
- packages/itwinui-css/backstop/tests/tile.html
- packages/itwinui-css/src/tile/classes.scss
- packages/itwinui-css/src/tile/tile.scss
- packages/itwinui-react/src/core/Tile/Tile.tsx
Before this change, when using arrow key navigation in screenreaders, all the content in the thumbnail area would be announced before the name of the Tile. This is not ideal.
So now, `iui-tile-name` will now be the first thing inside tile (in the DOM) with no changes to visuals. This is done using flex `order`.
I left the folder tile unchanged because it was getting complicated and it's less important - there isn't much stuff there in the thumbnail area.
No new tests needed. Existing tests all pass because there are no visual changes.
> update Tile order so name comes first

- packages/itwinui-css/src/tile/tile.scss
In #1117, we introduced css grid. This looked fine in chrome/firefox but was breaking in safari. Affected elements: thumbnail buttons and more-options button.
After investigating, I found the cause to be the use of `position: absolute` together with grid. These were left behind because we don't want the "overlaying" parts to occupy space. I was able to easily remove it from thumbnail buttons, but removing it from more-options was causing layout shift (because it now occupies space) so I had to get a bit creative.
The more-options button now uses `grid-row: -1` together with the metadata (both are considered "last row") and also uses `display: grid` to get rid of any excess line height. And for folder tiles, this is not enough for (there is no metadata region there) so I've removed it from …
> fix grid positioning in safari

- packages/itwinui-css/src/tile/tile.scss
- packages/itwinui-css/src/utils/mixins.scss
This PR basically undoes #1132 because it was causing layout shift in Chrome/Firefox when Tile didn't have metadata.  It is now replaced with hardcoded absolute positioning specifically for safari (as a final resort after spending way too much time trying to make it work in a cross-browser way).
This is achieved by targeting safari using `@supports (-apple-pay-button-style: inherit)` which i've put in a mixin.
Before:
https://user-images.githubusercontent.com/9084735/225394169-1582488d-9a45-4f8e-a9ba-1e7bdc6c52b5.mov
After:
https://user-images.githubusercontent.com/9084735/225395385-18c73166-fa3a-4c16-a866-32b6330087ea.mov
Additionally, I've also tried to go through and hover over every single Tile to make sure there is nothing left.
N/A
> fix grid positioning in safari (again)

- .changeset/lazy-buses-cross.md
- packages/itwinui-react/src/core/Slider/Slider.test.tsx
- packages/itwinui-react/src/core/Slider/Thumb.tsx
There is no need to manually maintain tooltip state because tippy already has a way of handling this. Hopefully should fix https://github.com/iTwin/iTwinUI/discussions/1122
Tested in existing stories.
Updated unit test to use userEvent.
also tested in iTwin.js sandbox: see https://github.com/iTwin/iTwinUI/discussions/1122#discussioncomment-5326566
> remove manual tooltip state from slider

- packages/itwinui-css/src/tile/tile.scss
In #959, `z-index: 1` was added on the tile-name to allow clicking on the thumbnail region to activate the action. But this broke all the other buttons on the tile, such as the quick-action/type-indicator (on the top-left/top-right of the tile) and the more-options (bottom-right).
So I've changed tile-name to have `z-index: 0`, and everything that needs to be on top of it to have `z-index: 1`. This ensures that clicking on *most* of the tile will perform the default action (such as navigation or selecting the Tile) and clicking on these specific regions will perform the contextual action (such as opening a dropdown).
Tested working correctly by clicking/hovering on all the different parts of tiles in the html test pages (under the "Default" section) as well as storybook (the "Actionable" …
> fix z-index issues with actionable tiles

- apps/website/src/examples/Avatar.groupoverflowtooltip.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/avatar.mdx
I added the storybook example for avatar group with tooltip to the website. I also edited some of the text to reflect the addition, and corrected the statement that the maximum amount of avatars is six.
I made sure the website example worked as intended.
N/A
> doc(Avatar): Added avatar group with tooltip example

- packages/itwinui-css/src/tile/tile.scss
#1141 was only working on firefox, so this change makes it work on chrome too.
same as #1141 but made sure to click on thumbnail area in chrome and safari too.
Before:
https://user-images.githubusercontent.com/9084735/226354345-48920c2d-ec5e-4c93-beb6-192a1ea3e413.mov
After:
https://user-images.githubusercontent.com/9084735/226354490-76c2ec04-e27b-400e-b9a3-251a7f0b22aa.mov
(results might vary by operating system)
N/A
> fix z-index issues with actionable tiles (again)

- .changeset/cuddly-cherries-build.md
- packages/itwinui-react/src/core/utils/hooks/useTheme.ts
Added new internal hook called in `useTheme` (and thus called in every component) to show a console error in development mode if the root font size was overridden. This will help avoid surprises for users who might notice that our component sizes have unexpectedly changed.
Confirmed warning appearing by overriding root font size in dev tools.
Added new section to migration guide: https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v2-migration-guide#relative-font-size
> warn if root font size was overridden

- apps/website/astro.config.ts
- apps/website/src/components/HeadSEO.astro
Astro requires the [`site`](https://docs.astro.build/en/reference/configuration-reference/#site) property to be specified in config to generate correct sitemaps. This property is then also used to generate canonical urls for SEO.
Tested correct urls showing up in build output. (Previously it was not even generating sitemap and was using localhost in some of the meta tags)
N/A
> fix site url for seo

- apps/website/src/examples/Tag.basic.tsx
- apps/website/src/examples/Tag.default.tsx
- apps/website/src/examples/TagContainer.main.tsx
- apps/website/src/examples/TagContainer.scroll.tsx
- apps/website/src/examples/TagContainer.truncate.tsx
- apps/website/src/examples/TagContainer.wrap.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/tag.mdx
> website: Tags

- .changeset/weak-carrots-cheat.md
- packages/itwinui-css/src/toast/toast.scss
Added css that allows toast messages to break rather than overflow as in this example: https://stackblitz.com/edit/react-ts-tyyqu4?file=App.tsx
Before: 
After: 
Tested that long words and short words behave as expected in the toast. The long words should break if necessary but short words should not unecessarily.
Added changeset
> fix(Toast): Allow toast message to break

- .changeset/nasty-news-dress.md
- packages/itwinui-css/src/alert/alert.scss
Added css that allows alert messages to break rather than overflow as mentioned in the similar PR for toast: https://github.com/iTwin/iTwinUI/pull/1169
Before: 
After: 
Tested that long words and short words behave as expected in the alert. The long words should break if necessary but short words should not unecessarily.
Added changeset
> fix(Alert): Allow alert message to break

- apps/website/src/examples/Checkbox.indeterminate.tsx
- apps/website/src/examples/Checkbox.inputgroup.tsx
- apps/website/src/examples/Checkbox.loading.tsx
- apps/website/src/examples/Checkbox.statuses.tsx
- apps/website/src/examples/Checkbox.visibility.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/checkbox.mdx
- Add checkbox demos for the different options.
- Update documentation, include adding hyperlinks to other mentioned components.
> website: Update checkbox documentation & demos

- .changeset/bright-mails-exist.md
- packages/itwinui-react/src/core/utils/components/Resizer.tsx
- packages/itwinui-react/src/core/utils/hooks/useDragAndDrop.tsx
Replaced `document` with `ownerDocument` when removing the `pointermove` event listener. Hopefully fixes https://github.com/iTwin/appui/issues/236.
Tested in playground with this code:
<details>
<summary>App.tsx</summary>
```tsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Button, Dialog, ThemeProvider } from '@itwin/itwinui-react';
const App = () => {
const [popout, setPopout] = React.useState<Window>();
return (
<>
<Button
onClick={() => {
setPopout(openNewWindow());
}}
>
Open popup
</Button>
{popout &&
ReactDOM.createPortal(<DraggableDialog />, popout.document.body)}
</>
);
};
const openNewWindow = () => {
const popout = window.open()!;
document.head.querySelectorAll('link, style').forEach((style) => {
popout.document.head.appendChild(style.cloneNode(true)); …
```
> fix draggable/resizable dialogs in popup windows

- .changeset/changelog-github.cjs
- .changeset/config.json
Updated changesets config to use a custom script instead of [`@changesets/changelog-git`](https://github.com/changesets/changesets/blob/main/packages/changelog-git/src/index.ts).
Two main changes:
- will show PR number instead of commit number
- hopefully will not show duplicate entries for updated dependencies
Tested by running `yarn changeset version` before today's release.
N/A
> fix changesets format

- apps/website/src/components/RelatedComponents.astro
- apps/website/src/pages/docs/buttongroup.mdx
Added component to show related components cards list. Currently added only to ButtonGroup.
Visual testing, also voiceOver testing.
N/A
> website: Add related components section

- apps/website/src/components/Placeholder.astro
- apps/website/src/pages/_global.astro
- apps/website/src/pages/docs/_layout.astro
- Increased the spacing between sections by using a slightly larger value and by using `em` instead of `rem`.
- Fixed the colors so that heading text looks brighter than paragraph text.
- Updated the heading font size to use the fluid typography scale that we already have in place.
All of these changes help address https://github.com/iTwin/iTwinUI/issues/941#issuecomment-1500391356
Tested locally.
N/A
> improve website typography

- .changeset/lovely-pianos-fry.md
- packages/itwinui-react/src/core/LabeledSelect/LabeledSelect.tsx
- packages/itwinui-react/src/core/utils/components/InputContainer.tsx
`input.css` was missing so i changed to it from `select.css` (which is already imported through `Select.tsx`). Fixes #1194
Hard to test because can't repro. But the user was able to work around it with a manual import so the this fix _should_ work.
N/A
> fix css import missing in LabeledSelect

- .changeset/lovely-dingos-attack.md
- packages/itwinui-react/src/core/Dialog/DialogMain.tsx
Added back old visibility class handling because new one broke stuff.
Tested in vite app, docs website and storybook.
N/A just undoing bug we introduced.
> fix(Dialog): Making it visible

- apps/storybook/package.json
- yarn.lock
In #1188, a new `storybook` dependency was added, and `changesets` was getting confused by it (https://github.com/iTwin/iTwinUI/pull/1196#discussion_r1161773600). So I've replaced this dependency with `sb`.
Both of these packages are aliases to `@storybook/cli` and work identically.
Tested running storybook.
N/A
> fix sb cli conflicting with `storybook` workspace

- apps/website/src/examples/Anchor.asbutton.tsx
- apps/website/src/examples/Anchor.main.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/anchor.mdx
- Added demo for the "`as` Button" variant of Anchor
- Update documentation
- Anchor portion of #961  
N/A
N/A
> website: Update Anchor documentation

- .changeset/cuddly-moons-invite.md
- packages/itwinui-react/src/core/utils/components/Popover.tsx
Noticed that popovers were incorrectly getting `role='tooltip'` which is what Tippy.js defaults to, so removed it. Role must be manually specified for each case.
Tested by inspecting the DOM.
N/A
> remove default tooltip role from popover

- .changeset/lovely-dodos-sit.md
- packages/itwinui-css/src/menu/menu.scss
- packages/itwinui-react/src/core/ComboBox/ComboBox.test.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBox.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxInput.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxMenuItem.tsx
- Adjusted css so that disabled items have proper focus outline
- Adjusted react code so that onClickHandler will early return if the item is disabled
Both of these changes ensure that disabled items can be predictably focused but not selected. Fixes #1201 
Tested in storybook and also in playground, both with previous version (which doesn't have ListItem changes) and with new code.
https://user-images.githubusercontent.com/9084735/231842528-de7bf044-0c21-407f-a672-16e6b05b6692.mov
N/A
> fix combobox disabled items behavior

- .github/workflows/changeset-release.yml
This change will (hopefully) add provenance info to our npmjs.com page, linking back to our github repo/commits. Basically like a "verified" badge to prove that our github repo is actually where the package was published from.
See https://github.blog/2023-04-19-introducing-npm-package-provenance/
TBD. Will need to wait for next release to see if it actually works.
N/A
> enable provenance for npm publish

- CONTRIBUTING.md
- apps/portal/src/pages/index.astro
- package.json
- yarn.lock
Ignored cra playground path from workspaces field in package.json. This means cra will not be installed locally but will still be available for codesandbox.
This was done because cra is bloated with a lot of questionable dependencies that often have security vulnerabilites.
N/A
N/A
> remove cra playground from workspaces

- .changeset/witty-ties-dream.md
- packages/itwinui-css/src/utils/input-container/input-container.scss
- packages/itwinui-react/src/core/LabeledInput/LabeledInput.tsx
- packages/itwinui-react/src/core/LabeledTextarea/LabeledTextarea.tsx
- packages/itwinui-react/src/core/utils/components/InputContainer.tsx
- packages/itwinui-react/src/core/utils/hooks/useId.ts
Changed the internal DOM structure of `LabeledInput` and `LabeledTextarea` to prefer explicit association over implicit. The `<label>` is now associated with the input using `htmlFor`/`id` and the container is a generic div. To achieve this, I had to add some checks inside `InputContainer` and a prop to pass the id. I also left out `LabeledSelect` because there is no "input" in there to associate the label with; this can be addressed in a separate PR.
This change improves accessibility, with no API changes and no effect on visuals.
In the next major version, we can further improve `InputContainer` to reuse `Label` and `StatusMessage` components, and remove any duplicate CSS rules.
Tested by going through all stories and clicking on them and inspecting the dom.
N/A
> use implicit id association in LabeledInput & LabeledTextarea

- .changeset/sour-garlics-lay.md
- packages/itwinui-css/src/checkbox/checkbox.scss
- packages/itwinui-css/src/table/table.scss
Used `::before` element with negative inset to increase checkbox to 24x24 by default. Can be adjusted using the CSS variable `--iui-checkbox-target-size`.
In table, I'm using this variable to make it 32x32. This will prevent accidentally clicking on the row instead of the checkbox.
No visual changes.
Tested in demo pages / storybook.
See branch preview: https://itwin.github.io/iTwinUI/1245/react/?path=/story/core-table--selectable-multi
N/A
> increase checkbox touch target size

- .changeset/wet-eyes-drop.md
- packages/itwinui-css/src/global.scss
After #1245, a user reported some unexpected visible borders around checkboxes.
The border comes from v1 styles which were not being correctly targeted in the place where we globally revert all v1 styles, so I explicitly added selectors for `::before`/`::after` in that rule.
Tested with this code:
```jsx
import { Global } from '@emotion/react';
import { Checkbox, ThemeProvider } from '@itwin/itwinui-react';
export default () => {
return (
<div className='iui-body'>
<Global
styles={`
@layer test {
.iui-checkbox::before {
border: 1px solid hotpink;
}
}
`}
/>
<ThemeProvider theme='dark'>
<Checkbox label='Hello' />
</ThemeProvider>
</div>
);
};
```
Without this change:
With this change:
N/A
> revert v1 styles for psuedo elements too

- packages/itwinui-css/scripts/watchScss.mjs
leftover from #1251. The files are now `{component}.scss`, not `classes.scss`.
tested working correctly by starting dev server and modifying scss files.
> fix watchScss script

- .changeset/fluffy-dogs-vanish.md
- packages/itwinui-css/src/global.scss
Problem: https://stackblitz.com/edit/vitejs-vite-12mizp?file=src%2FApp.jsx
This was happening because the properties that are set on the internal svg elements (through html attributes) were being reverted.
Solution: Added an exception for `svg *` when reverting.
Before:
After:
N/A
> add exception for svg when reverting v1 styles

- .changeset/poor-bees-sneeze.md
- packages/itwinui-react/src/core/utils/components/Popover.tsx
Ported from https://github.com/iTwin/iTwinUI/pull/1265#issuecomment-1545755572 for release in v2. It could fix some of the issues with our Popover.
Fixes the weird edge cases that I was facing in #1265, and doesn't cause any existing tests to break, which is good.
N/A
> fix Popover controlled mode during first render

- .changeset/purple-beds-hammer.md
- packages/itwinui-react/src/core/ButtonGroup/ButtonGroup.tsx
Filtering out null/undefined children when mapping over children, because otherwise they get converted into `<div></div>` and break border-radius logic which relies on `:first-child`/`:last-child`.
Can be tested by simply doing this:
```jsx
<ButtonGroup>
<IconButton>
<SvgAdd />
</IconButton>
<IconButton>
<SvgEdit />
</IconButton>
{null}
</ButtonGroup>
```
Before:
After:
N/A
> filter out null children in buttongroup

- apps/website/src/examples/SearchBox.basic.tsx
- apps/website/src/examples/Searchbox.custom.tsx
- apps/website/src/examples/Searchbox.customopen.tsx
- apps/website/src/examples/Searchbox.expandable.tsx
- apps/website/src/examples/Searchbox.main.tsx
- apps/website/src/examples/Searchbox.size.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/searchbox.mdx
- packages/itwinui-react/src/core/SearchBox/SearchBox.tsx
Update jsdoc for ExpandButton and CollapseButton. Was still using open and close words.
N/A
Added examples and text in SearchBox documentation page.
> SearchBox documentation

- .changeset/spicy-tomatoes-leave.md
- packages/itwinui-react/src/core/FileUpload/FileUploadCard.tsx
- packages/itwinui-react/src/core/FileUpload/FileUploadTemplate.tsx
- Replaced `label` element with `Anchor` component, so css gets imported for it.
- Import missed css in `FileUploadCard`
- Use `VisuallyHidden` instead of class. Probably, this was also broken.
Before my change, this is the outcome for `FileUpload`
After:
Can use this code
```
<FileUpload onFileDropped={() => {}}>
<FileUploadTemplate>nothing</FileUploadTemplate>
</FileUpload>
```
Important thing I have noticed:
dev build in Vite (at least) includes all the css from all available components. I was pretty sure that was not the case some time ago... That means, that testing environment with dev build is not really isolated.
As a result, the same happens in all the code sandboxes in examples..
Storybook also has all the css included, so you would never reproduce it there.
This was not a bug …
> fix: `FileUpload` missing styles

- apps/website/src/components/LiveExample.astro
- examples/InputGroup.checkboxGroup.tsx
- examples/Select.disable.tsx
- examples/Select.icon.tsx
- examples/Select.statuses.tsx
- examples/Select.sublabels.tsx
- examples/Select.truncate.tsx
- examples/index.tsx
**What I did**: Changed `examples/index.tsx` so that all exports are wrapped in `<ThemeProvider>` using a HOC `withThemeProvider`. Also some examples were using (nonexistent) `args`, so removed those too.
**Why**: In #1351, toasts were not working on website because context was not being found somehow. I figured out it's because context [doesn't work](https://docs.astro.build/en/core-concepts/sharing-state/) in Astro between islands. (Previously, `ThemeProvider` and the examples were rendered in separate islands). Within the same island, context works fine.
Tested against #1351 and toasts are now correctly showing up!
https://github.com/iTwin/iTwinUI/assets/9084735/7c051747-caca-4548-8b0a-7b516960d03e
N/A
> wrap all website examples in ThemeProvider

- .github/workflows/build.yml
For some reason, the install job on windows keeps randomly failing everytime the lockfile changes, so now it will be retried upto 3 times.
N/A
N/A
> retry `yarn` on windows if failed

- .changeset/nasty-walls-juggle.md
- packages/itwinui-react/src/core/Avatar/Avatar.tsx
- packages/itwinui-react/src/core/Avatar/index.ts
- packages/itwinui-react/src/core/AvatarGroup/AvatarGroup.tsx
- packages/itwinui-react/src/core/AvatarGroup/index.ts
- packages/itwinui-react/src/core/Header/Header.tsx
- packages/itwinui-react/src/core/index.ts
yeet
N/A
added changeset.
updated migration guide. https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v3-migration-guide#usericon--usericongroup
> remove deprecated `UserIcon`

- .changeset/violet-laws-stare.md
- packages/itwinui-react/src/core/Tabs/Tabs.tsx
- packages/itwinui-react/src/core/Tabs/index.ts
- packages/itwinui-react/src/core/index.ts
yeet
N/A
Added changeset and updated [migration guide](https://github.com/iTwin/iTwinUI/wiki/iTwinUI-react-v3-migration-guide#tabs).
> remove deprecated `HorizontalTabs`/`VerticalTabs`

- .changeset/wet-planes-dance.md
- packages/itwinui-css/src/tabs/base.scss
this should partially fix the user-reported issue where tabs-list was growing when tabpanel content was not big enough.
this is the same as what we do in vertical tabs.
https://github.com/iTwin/iTwinUI/blob/d90b55239b5a14c6c2173ff11ec61597196893b6/packages/itwinui-css/src/tabs/base.scss#L181-L184
tested with a few different versions of custom css in codesandbox. also verified in user's app.
added changeset
> constrain tabs height to let content grow

- .changeset/ten-grapes-approve.md
- examples/ButtonGroup.input.tsx
- examples/ButtonGroup.main.tsx
- examples/ButtonGroup.overflow.tsx
- examples/ButtonGroup.usage.tsx
- examples/ButtonGroup.vertical.tsx
- packages/itwinui-react/src/core/ButtonGroup/ButtonGroup.tsx
Bringing `ButtonGroup` examples to a11y compliance. `ButtonGroup` component brought to compliance by removing `aria-orientation` attribute .
Unit testing & visual testing will be conducted. 
TBD
> button group a11y compliance

- .github/workflows/build.yml
The [gh-pages](https://github.com/iTwin/iTwinUI/tree/gh-pages) branch is kinda getting out of hand as it's full of thousands of images from test failures. This slows up deployments which take 2-5 mins to complete. Not publishing these images should speed things up.
The test image artifacts still get uploaded if somebody wants to download the zip.
N/A
N/A
> CI: dont publish test images

- .changeset/chatty-actors-attend.md
- packages/itwinui-react/src/core/Buttons/DropdownButton/DropdownButton.tsx
Pretty simple change in types, as all the code is already wired up correctly. Closes #1394
https://github.com/iTwin/iTwinUI/assets/9084735/b0903553-0846-4ff1-b578-e403b4a2216c
Not adding story or docs example, because we don't want to encourage this pattern everywhere. I believe we originally added the restriction on purpose, but multiple users have asked for this since then. /cc @FlyersPh9
> v2: allow `styleType='high-visibility'` in `DropdownButton`

- packages/itwinui-react/src/core/utils/functions/import.ts
webpack and vite both freak out when they encounter a dynamic import with a dynamic specifier, so ignoring them. the whole point of this syntax is to be lazy-loaded only when necessary, so it doesn't need to be optimized by bundlers.
no longer seeing these warnings
n/a
changeset not needed imo, because this file was only added in v3
> ignore webpack/vite errors with dynamic imports

- packages/itwinui-react/src/styles.js/vite.config.mjs
After #1359, the `styles.css` created within react would cause global side effects, so I've created a simple postcss plugin to dynamically scope the variables to only the hashed iui-root class.
The result:
1. `@itwin/itwinui-variables` is still usable without a class, only data attributes.
2. `@itwin/itwinui-react` is self-contained and no longer affects independent usage of `@itwin/itwinui-variables`.
Confirmed working by inspecting generated stylesheet.
changeset not needed, as this is a small, almost-invisible change in an unreleased feature.
i will work on docs for variables compatibility table later.
> scope variables within react stylesheet

- .github/workflows/build.yml
- apps/storybook/package.json
- apps/storybook/scripts/run-tests.js
- testing/a11y/package.json
- yarn.lock
- bumped `cypress`, pinned version
- changed cypress github-action's `install-command` to just `yarn` (without `--frozen-lockfile`)
I believe the problem was that Yarn v1, in their infinite wisdom, does not respect `resolutions` when running install from a subdirectory of the monorepo. So, when cypress tries to install from a subdirectory, the lockfile changes and it fails CI because of `--frozen-lockfile`
now correctly runs in CI. 🎉 https://github.com/iTwin/iTwinUI/actions/runs/5731719926/job/15533266054
| --- | --- |
| <img width="900" alt="" src="https://github.com/iTwin/iTwinUI/assets/9084735/23cc46ca-0aff-481d-9168-a059229be03a"> | <img width="1073" alt="" src="https://github.com/iTwin/iTwinUI/assets/9084735/cafa6dc5-0de0-4022-9d14-56df75d4c622"> |
N/A
> fix a11y ci failing at install step

- .changeset/hip-moose-flow.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.test.tsx
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
changed default value of `ThemeProvider`s `theme` prop to `"inherit"` (previously `"light"`).
improved the handling of `"inherit"` so that it does three things (in order):
1. try to read theme from context
2. try to read closest `data-iui-theme` attribute if no context found
3. fall back to light theme
as a result, developers will be able to use v3 `ThemeProvider` inside v2 `ThemeProvider` and it will automatically work. also, `data-iui-theme` can be set on the `<body>` (standalone `@itwin/itwinui-variables` usage) and it will automatically be respected.
tested in playground and updated unit tests.
added changeset.
> make `theme='inherit'` the default

- examples/Slider.labels.tsx
- examples/Slider.main.tsx
- examples/Slider.range.tsx
- examples/Slider.rangemultiple.tsx
- examples/Slider.thumbcustom.tsx
- examples/Slider.tooltipcustom.tsx
- examples/Slider.tooltipnone.tsx
- examples/Slider.vertical.tsx
Added `aria-label` prop to all thumbs in all `Slider` examples. But no change was needed in component code.
Ensured that the cypress tests for Slider reported no more violations.
N/A
> Fixed a11y violations for Slider examples

- playgrounds/vite/index.html
- playgrounds/vite/src/main.tsx
The `* { margin: 0 }` was overriding any margins from iTwinUI components, so moved it into a layer that comes before the `itwinui` layer. for more details, see https://github.com/iTwin/iTwinUI/wiki/Styling
before:
after:
n/a.
> move playground reset into layer

- apps/website/src/components/LeftSidebar.astro
- apps/website/src/components/LeftSidebarContent.astro
two changes to sidebar:
- increased separation between nav groups.
- used scroll snapping to scroll to the currently active link when page loads.
both of these were based on user feedback.
before:
https://github.com/iTwin/iTwinUI/assets/9084735/7f0a0191-59c3-4ffe-9a64-76d813f6d756
after:
https://github.com/iTwin/iTwinUI/assets/9084735/b3d4d1b8-def1-4aaf-940f-23e6a1678b37
n/a
> improve website sidebar

- apps/website/src/components/AlgoliaSearch.astro
The broken Algolia styles were because of some unnecessary astro scoping in the Algolia styles. I fixed this by adding [`is:global`](https://docs.astro.build/en/guides/styling/#global-styles).
|Old|New|
|-|-|
|![image](https://github.com/iTwin/iTwinUI/assets/45748283/cc287143-4c0c-4d01-914c-d0ce6849909a)|![image](https://github.com/iTwin/iTwinUI/assets/45748283/2b6d55d2-78fc-42a7-9d0c-67a1edd308ed)|
<details>
<summary>The problem was the unnecessary astro scoping</summary>
</details>
---
I am not sure why didn't this "missing styles" issue happen in the dev version. I suspect it has something to do with the bug in astro where importing styles into a layer also duplicates those styles outside the layer (as mentioned in https://github.com/iTwin/iTwinUI/pull/1365#discussion_r1262621490).
But …
> Fixed Algolia search box styling

- .changeset/mighty-fireants-check.md
- packages/itwinui-react/src/core/Tree/TreeNode.tsx
`aria-owns` expects a *space* separated list of ids ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-owns#values)). However, we were passing a *comma* separated list of ids. I corrected this mistake and added a short changeset.
Confirmed that the cypress-axe `TreeMainExample` test passes.
N/A
>  Fixed a11y violations for Tree examples

- .changeset/serious-mice-repair.md
- packages/itwinui-css/src/header/header.scss
- packages/itwinui-css/src/side-navigation/side-navigation.scss
removed safe area insets that were added for iphone notch support because they cause issues when used with RTL or vertical languages.
by default, applications do not fill up the full viewport, so they are already safe from getting clipped by the notch.
if a user wants to override the default behavior using `viewport-fit=cover`, they can also manually add the safe-area-insets to header/side-nav.
Was testing it together with @FlyersPh9 in https://github.com/iTwin/iTwinUI/pull/1489#discussion_r1293949164 and found two issues in vertical writing modes:
- when using physical padding (current approach) in header, it results in the header becoming too thick:
- when using logical properties, it results in extra gap at the bottom:
removing special handling of notch should avoid both issues.
n/a
> remove special handling for iphone notch

- .changeset/thirty-beds-mate.md
- packages/itwinui-react/scripts/generateStyles.mjs
Previously we were generating `cjs/styles.js` by hand. Turns out mixed default+named exports in CommonJS are complicated and need more work than simply using `module.exports=` and `exports.whatever=`. See [playground](https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA0utKMgvKlFISU1LLM0pUVAvycgsVgCikoxUmKC6NVcqRFVyfl5xiUJafr6CLUJlXmJuaoq6NQDsn8KpSQAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KHN2Dv0EIg6EYifMJGKoty9QCBtNr%2B%2FvDHOQZOEJ9%2FKWUAQkTCeuDCUXRKfwgBKK0hGFRLchqqpSrMwhI3aDwWSiAumlqLpPj16Aoz3hCPROaucmvP%2FpvQ2RCS6GqtVuMXgdZH1VbD%2BvTax%2F5JyqKi2We80wc85Fs92UPQa8RRXZPsXM%2FmJHxwBAAA%3D).
So now, I'm using `swc` to transform the ESM exports into CJS.
Unrelated: I'm auto-deleting the `styles.js` that gets left behind when switching between `dev`/`main` branches, as it messes up …
> use swc to generate cjs styles

- .changeset/odd-crabs-approve.md
- apps/storybook/src/Alert.stories.tsx
- apps/website/src/demos/Alert.demo.tsx
- examples/Alert.informational.tsx
- examples/Alert.inline.tsx
- examples/Alert.main.tsx
- examples/Alert.negative.tsx
- examples/Alert.positive.tsx
- examples/Alert.sticky.tsx
- examples/Alert.warning.tsx
- packages/itwinui-react/src/core/Alert/Alert.test.tsx
- packages/itwinui-react/src/core/Alert/Alert.tsx
similar to #1502, brought back the old Alert api, reverting the breaking change from #1247.
the following two snippets are now equivalent:
```jsx
<Alert
type='positive'
onClose={onClose}
clickableText='Click me'
clickableTextProps={{ href: '/' }}
>
This is an alert.
</Alert>
```
```jsx
<Alert.Wrapper type='positive'>
<Alert.Icon />
<Alert.Message>
This is an alert.
<Alert.Action href='/'>Click me</Alert.Action>
</Alert.Message>
<Alert.CloseButton onClick={onClose} />
</Alert.Wrapper>
```
Other notes:
- added missing `ButtonBase` (from #1461) to `Alert.Action`
- the `clickableText`, `clickableTextProps` and `onClose` props have been brought back but are still deprecated to encourage use of new api.
- the purpose of restoring the old api in this case is just to make migration easier. …
> restore old `Alert` api

- .changeset/nice-crabs-explode.md
- .changeset/yellow-shirts-fix.md
- packages/itwinui-css/backstop/tests/avatar.html
- packages/itwinui-css/backstop/tests/radio-tile.html
- packages/itwinui-css/backstop/tests/tooltip.html
- packages/itwinui-css/src/tooltip/tooltip.scss
- packages/itwinui-react/src/core/Buttons/IconButton/IconButton.tsx
- packages/itwinui-react/src/core/SideNavigation/SideNavigation.test.tsx
- packages/itwinui-react/src/core/Slider/Slider.test.tsx
- packages/itwinui-react/src/core/Slider/Thumb.tsx
- packages/itwinui-react/src/core/Stepper/Stepper.test.tsx
- packages/itwinui-react/src/core/Stepper/WorkflowDiagram.test.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.test.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
*This PR is a follow-up to #1311 and precursor to #1506.*
- Added new `ariaStrategy` prop to `Tooltip` to allow switching between `aria-describedby`, `aria-labelledby` and nothing (see https://github.com/iTwin/iTwinUI/pull/1311#pullrequestreview-1505237337).
- This prop is used in `IconButton` to replace the custom Popover-based tooltip implementation.
- This prop is also used in `Slider` thumb because (1) the tooltip value keeps updating but is not reflected in screen-readers, and (2) the slider already has its value exposed through `aria-valuenow`.
- Added `aria-hidden` to Tooltip to prevent duplicate announcements (the text should already be exposed through `aria-describedby`/`aria-labelledby`/visuallyhidden text) and removed `role=tooltip` because of [poor …
> add `ariaStrategy` prop to `Tooltip`

- examples/Input.button.tsx
similar to #1532 and #1533
Before:
After:
n/a
> add `label` to Input Button example

- apps/storybook/src/Table.stories.tsx
Solves part of #886 . Helper PR for #1514 .
Passing `{...args}` to `<Table>` in Table stories could hide TS errors (as mentioned in #886). Thus:
* Removed `{...args}` and Storybook controls from all Table Storybook stories.
Tested that all stories are still working as before.
N/A
> Removed `{...args}` from Table's Storybook file

- playgrounds/astro/tsconfig.json
After #1549, I noticed the below error in the Astro playground.
Thus, I set `jsx` to `react-jsx` in the tsconfig to fix this error.
Confirmed that the above error no longer shows. Also confirmed that `yarn build` in the astro-playground works without any errors.
N/A
> Fix `--jsx` flag not set error in astro-playground

- apps/storybook/src/ComboBox.stories.tsx
- apps/storybook/src/Label.stories.tsx
- examples/ComboBox.label.tsx
- examples/ComboBox.multipleSelect.tsx
- examples/ExpandableBlock.form.tsx
- examples/InformationPanel.main.tsx
- examples/Slider.labels.tsx
- examples/Slider.main.tsx
- examples/Slider.range.tsx
- examples/Slider.rangemultiple.tsx
- examples/Slider.tooltipcustom.tsx
- examples/Slider.tooltipnone.tsx
- examples/Stepper.layout.tsx
#1521 
Added InputGrid in the examples that uses Label.
Visual tests pass;
Unit tests pass;
a11y tests pass;
N/A
> Fix label bottom margin issue that was introduced with input container rewrite

- .changeset/famous-geese-approve.md
- packages/itwinui-react/src/core/DropdownMenu/DropdownMenu.tsx
- packages/itwinui-react/src/core/Menu/MenuItem.tsx
this PR fixes #1301 in two steps:
- added `iui-scroll` by default to regular `DropdownMenu`s and submenus.
- added 100ms delay to submenu.
in #1577: `iui-scroll` will be removed and the overflow css will be moved into base styling in v3.
| --- | --- |
| <img width="294" alt="" src="https://github.com/iTwin/iTwinUI/assets/9084735/9b0ff5ff-142f-4c1c-958d-d9b46ecea1b6"> | <img width="179" alt="" src="https://github.com/iTwin/iTwinUI/assets/9084735/f194459c-61ef-463c-b862-1e0b11275d79"> |
n/a
> make dropdown menus scrollable by default 

- .changeset/eighty-squids-protect.md
- packages/itwinui-css/src/toggle-switch/toggle-switch.scss
fixes #1584. don't ask why.
tested in vite playground using this code:
<details>
<summary>App.tsx</summary>
```tsx
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { Button, ThemeProvider, ToggleSwitch } from '@itwin/itwinui-react';
let childWindow: Window | null;
export default () => {
const [isPoppedOut, setIsPoppedOut] = React.useState(false);
return (
<>
<ToggleSwitch label='hello' />
<br />
<Button
disabled={isPoppedOut}
onClick={() => {
childWindow = window.open(
'',
'',
'menubar=no,resizable=yes,scrollbars=no,status=no,location=no',
);
if (!childWindow) return;
setIsPoppedOut(true);
copyStyles(childWindow!.document);
}}
>
Open window
</Button>
{isPoppedOut &&
ReactDOM.createPortal(
<ThemeProvider>
<ToggleSwitch label='world' />
<br />
<Button>button for …
```
> fix toggle-switch popout styles

- .changeset/early-hats-divide.md
- packages/itwinui-react/src/core/Modal/Modal.tsx
- packages/itwinui-react/src/core/Toast/Toaster.test.tsx
- packages/itwinui-react/src/core/Toast/Toaster.tsx
changed the portal container ids in v2 so that they don't conflict with v1. fixes #1582
reason: html `id`s need to be globally unique so if both v1 and v2 are used together with same ids, the v1 portal containers were being reused for v2 components and therefore not getting styled (since they are outside the "v2 boundary" created by ThemeProvider).
tested by recreating the sandbox from the bug report.
https://github.com/iTwin/iTwinUI/assets/9084735/675ba0f8-1f84-4904-98b0-11fb902cfbdc
n/a
> fix v2 modals/toasts conflicting with v1

- .changeset/bright-onions-draw.md
- packages/itwinui-react/src/core/Table/hooks/useScrollToRow.ts
Fixes `useScrollToRow` crash on property access of undefined `pageRef.current[scrollToIndex]` object
N/A
N/A
> Fix `useScrollToRow` crash on property access of undefined `pageRef.current[scrollToIndex]` object

- package.json
fixes pre-commit hook part of #1571
tested that html files can be committed without `no-verify`.
n/a
> don't run stylelint on html files

- packages/itwinui-react/src/core/Input/Input.tsx
- packages/itwinui-react/src/core/LabeledInput/LabeledInput.tsx
When working on https://github.com/iTwin/iTwinUI-migration-tool/pull/29, I noticed that although `setFocus` was removed from a few components in #1406, the `setFocus` prop was still used in some JSDocs examples.
This PR just updates or deletes those outdated examples.
N/A
N/A
> Removed `setFocus` from JSDocs

- .changeset/chatty-flowers-clean.md
- packages/itwinui-react/src/index.ts
added `"use client"` to barrel file, since this is the only place where components can be imported from.
this makes it possible to use our library in Nextjs App Router without hacks.
see https://react.dev/reference/react/use-client
while not all of our components (for example `Text`) necessarily need to be Client Components, we use context in every single one, so they kinda have to be.
n/a.
we can test it in migration tool once released.
n/a
> add `'use client'` directive

- packages/itwinui-react/src/core/LabeledSelect/LabeledSelect.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
Forwarded the ref in `Select` and `LabeledSelect`.
Reason: `setFocus` was removed in #1406 with the assumption that ref can be used to focus it, but it's not possible if the user cannot pass a `ref`.
for reviewing, turn off whitespace diff.
n/a.
not needed, as 3.0 is not available yet.
> allow setting ref in Select

- .changeset/cyan-mice-dress.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
- packages/itwinui-react/src/core/utils/hooks/useStyles.ts
fixes #1624 (v2 bug)
after debugging together with Gerardus, we found that the main problem was `loaded` being stored in a ref that gets initialized for every single component. this means `DropdownMenu` was calling `new CSSStyleSheet()` (from default `window`) and then trying to adopt it into the child window.
so i:
- moved loaded state out of the hook and into `ThemeProvider`, ensuring that it's shared across components.
- used [`document.defaultView`](https://developer.mozilla.org/en-US/docs/Web/API/Document/defaultView) to get child window and call `CSSStyleSheet()` from there.
slightly unrelated: i optimized ThemeContext value to be correctly memoized. This reduces the number of times the useEffect inside `useStyles` is called (and the number of re-renders in general).
tested with …
> fix styles being adopted from different window

- examples/Tile.avatar.tsx
added empty alt to ignore the image, because the tile already has the name of the user.
axe passes now
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/bf13dbe5-6a0a-4d1c-857d-47db753db931) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/638ef1c7-5a6b-43b9-9a66-e8ea77ab78cb) |
n/a
> add missing alt to Tile avatar example

- .changeset/dull-scissors-flash.md
- packages/itwinui-react/src/core/utils/hooks/useOverflow.test.tsx
- packages/itwinui-react/src/core/utils/hooks/useOverflow.tsx
Suggesting a fix for #1633.
Our `useOverflow` hook returns `visibleCount: 0` when item is bigger when space available. I think that should be '1'.
Using user provided code in vite sandbox.
Added unit test.
TBD
> useOverflow: fix visibleCount when item is too big for the space

- packages/itwinui-css/src/tile/tile.scss
- packages/itwinui-react/src/core/Tile/Tile.tsx
Added a check in Tile legacy to not render thumbnail area if thumbnail is not provided.
Changed name area to have top margin instead of thumbnail area bottom margin - keep the correct spacing even if thumbnail is not provided.
Visual tests pass
N/A
> Tile legacy: Thumbnail area is not rendered if no prop passed

- .changeset/four-cherries-wash.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.test.tsx
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
based on user feedback, `portalContainer` will now be inherited when `theme` is set to `"inherit"`.
unrelated: added `display: contents` to portal container div, to exclude it from layout. this is useful when setting something like `display: grid` on the root div.
added unit test.
also tested in vite playground with this code and inspected devtools to ensure that tooltip is portaled into outer ThemeProvider:
<details>
<summary>App.tsx</summary>
```tsx
import { Tooltip, ThemeProvider } from '@itwin/itwinui-react';
const App = () => {
return (
<>
<ThemeProvider data-inner>
<Tooltip content='world'>
<button>hello</button>
</Tooltip>
</ThemeProvider>
</>
);
};
export default App;
```
</details>
updated jsdocs and added changeset.
> make ThemeProvider inherit `portalContainer`

- .github/workflows/build.yml
any pushes to `main` branch were deleting the `legacy/v2` folder which hosts the v2 storybook.
found that this was because some typo in the workflow. the `.join('\n')` needs to be outside the array, not inside.
the `clean-exclude` option expects a newline separated list.
| --- | --- |
| `legacy,1,6,5,5` | `legacy\n1655` |
Tested by manually creating a dummy file in `gh-pages` branch inside [this PR's deployment folder](https://github.com/iTwin/iTwinUI/tree/gh-pages/1655), then pushing a commit to this PR to trigger CI.
the `legacy` folder was correctly preserved after automatic deployment.
n/a
> preserve legacy folder in `gh-pages`

- .changeset/fair-carpets-drum.md
- packages/itwinui-react/package.json
- packages/itwinui-react/src/core/Select/Select.tsx
- yarn.lock
fixes #1657
in react 17, `popover.refs.setFloating` was being called repeatedly on each render, thus causing more re-renders. so added early return.
~~bumped floating-ui as well, to ensure it's up-to-date.~~
tested by recreating react 17 sandbox from linked issue.
added changeset.
> fix infinite rerenders in `Select`

- yarn.lock
in #1663, `@floating-ui/react` was bumped then un-bumped, but `@floating-ui/utils` still managed to be bumped in the lockfile somehow. this resulted in an incompatible version of `@floating-ui/utils` being used by `@floating-ui/dom` (and `@floating-ui/core`), so those deps have now been updated as well.
tested that storybook is working correctly
n/a. doesn't affect user.
> fix lockfile

- .changeset/rich-spiders-draw.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.test.tsx
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
fixes #1653
the [`??=` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment) is being used to provide a conditional default value to `themeOptions.highContrast` when `theme` prop is set to `"inherit"`.
**note**: this fix will also be backported to v2.
tested this scenario in vite playground:
```tsx
<ThemeProvider theme='dark' themeOptions={{ highContrast: true }}>
<ThemeProvider>
[…]
</ThemeProvider>
</ThemeProvider>
```
updated one of the existing unit tests to also cover this scenario.
added changesets.
> fix `highContrast` theme not getting inherited

- .changeset/curly-peas-peel.md
- .changeset/new-wolves-jump.md
- apps/storybook/src/Table.stories.tsx
- packages/itwinui-react/src/core/Table/Table.test.tsx
- packages/itwinui-react/src/core/Table/actionHandlers/selectHandler.ts
* Ctrl + Shift click behavior matches that of Windows explorer
<details>
<summary>Screen recordings</summary>
Actions taken:
* Click row 0
* Ctrl click row 2
* Ctrl + Shift click row 6
* Ctrl click row 5
* Ctrl + Shift click row 3
Before:
[Before](https://github.com/iTwin/iTwinUI/assets/45748283/9d850e0b-34d0-413c-bbcc-f81e8304fa21)
After:
[After](https://github.com/iTwin/iTwinUI/assets/45748283/7c5781bf-897f-4328-9d98-1d56fdc9855e)
</details>
* Fix mismatch between Table state and the table that is shown (https://github.com/iTwin/iTwinUI/pull/1660#issuecomment-1791567011)
Updated unit test
Added changeset
> Table Ctrl+Shift click logic improved

- apps/website/src/pages/_global.css
not sure why these were added in the first place; the default scrollbars work fine.
my guess is the site was made before we had scoped styling support (`iui-root`), so iTwinUI scrollbars may have been messing up docs scrollbars, but now we are running into the opposite issue (https://github.com/iTwin/iTwinUI/issues/941#issuecomment-1492479881, https://github.com/iTwin/iTwinUI/pull/1656#discussion_r1382236355), so it's better to just use defaults.
tested that default scrollbars are appearing ok
n/a
> remove scrollbar styles from docs

- apps/website/src/demos/ComboBox.demo.tsx
In v3, passing `appendTo: 'parent'` in `dropdownMenuProps` is not needed. So removed it from the ComboBox demo on the home page.
Did a global search for `appendTo` and found no other matches.
N/A
> Remove unnecessary `appendTo: parent` from v3 Combobox demo code

- .changeset/curly-turtles-yawn.md
- packages/itwinui-react/src/core/Toast/Toaster.tsx
when working on the migration tool, i noticed `toaster` object was used in dependency arrays in multiple arrays, so it makes sense to memoize it.
no other code changes, so everything works the same.
n/a
> memoize toaster object

- .changeset/yellow-parrots-wonder.md
- packages/itwinui-react/setupTests.ts
- packages/itwinui-react/src/core/Overlay/Overlay.tsx
was trying to update the outdated jsdocs, when i noticed that the IIFE for `useInertPolyfill` was not actually being called, so fixed that.
a little hard to actually test because `inert` is now supported in all browsers, but the concept still applies.
the following does nothing:
```js
React.useEffect(() => {
async () => {
// …
}
}, []);
```
while the following calls it on mount:
```js
React.useEffect(() => {
(async () => {
// …
})();
}, []);
```
updated incorrect/insufficient jsdocs.
added changeset for code changes.
> fix Overlay polyfill and jsdocs

- .changeset/dry-ants-dress.md
- packages/itwinui-react/src/core/Menu/MenuItem.test.tsx
- packages/itwinui-react/src/core/Menu/MenuItem.tsx
fixes #1616 and #1617 (v2 bugs, can be reproduced in [v2 storybook](https://itwin.github.io/iTwinUI/legacy/v2/react/?path=/story/core-dropdownmenu--submenu))
the main problem was that the parent menu always has `overflow: auto` (after #1576), and we were appending sub-menus into the parent menu, thus causing clipping.
to fix this, i am now appending into the parent's parent (which will be some div that does not have `overflow: auto`).
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/b6d13154-c78b-4ade-b4e9-9a9cac5e3c32) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/0b4d5a49-59d4-4ccb-a458-e3de8944062a) |
the code for this component is very delicate, so i've arrived at this minimal solution after lots of iteration and playing around. …
> append nested submenus out of parent menu

- .changeset/lemon-kangaroos-brake.md
- packages/itwinui-react/src/core/Select/Select.test.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
I noticed that the basic Select usage shown in jsdocs and website was not updating state, so i've fixed that by adding internal uncontrolled state. Preference is given to user-passed `value` prop.
Tested that uncontrolled state works fine in playground and on docs website. Added unit test.
Although this behavior should be mentioned on docs page too, I didn't touch it because the whole thing needs some restructuring/rewriting.
> fix Select uncontrolled mode

- apps/website/src/components/AlgoliaSearch.astro
This fixes the website error by wrapping the `docsearch` initialization code in [`connectedCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#custom_element_lifecycle_callbacks), ensuring that it is always called at the correct time.
Unrelated: added missing `@layer components` in component css.
Verified that there is no console error.
N/A
> fix docsearch error on homepage

- .changeset/five-cheetahs-hang.md
- packages/itwinui-react/src/core/Carousel/Carousel.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBox.test.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBox.tsx
When working on the website, I noticed some hydration warnings in the console.
This was happening because we aren't using the `useId` hook in a couple components (these were coded before `useId` existed), so I've fixed them.
Confirmed that there is no hydration warning by visiting website.
N/A
> fix id hydration mismatch

- .changeset/rotten-tools-matter.md
- packages/itwinui-css/src/tree/tree.scss
This change makes it so that tree-node-content will fill up the size of the tree-node, and labels inside it will fill up the size of of the tree-node-content. This is necessary to be able to place right-aligned content in the nodes.
Tested in playground by placing right aligned content in TreeNode.
```tsx
<TreeNode
label={
<Flex>
{node.label}
<Flex.Spacer />
<ToggleSwitch size='small' />
</Flex>
}
{...rest}
/>
```
| --- | --- |
| ![](https://github.com/iTwin/iTwinUI/assets/9084735/6d9d8129-0c61-44c8-a652-7edf38eb71af) | ![](https://github.com/iTwin/iTwinUI/assets/9084735/bddc6c23-82bd-44f7-b336-0a4b93a921c9) |
N/A
> make tree nodes fill container width

- packages/itwinui-react/package.json
- packages/itwinui-react/src/core/ComboBox/ComboBox.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxInput.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
- yarn.lock
bumped `@floating-ui` to latest 0.26.x version. needed to make some changes:
- **Tooltip**: added `.nativeEvent` to event object for `reference` prop, because it was throwing an error (some floating-ui code relies on this property).
- **ComboBoxInput**: added a ref to freeze the previous state of `isOpen` for access inside `onClick`, because floating-ui was already opening the menu (on focus) before the click handler executed, causing the menu to immediately close after opening.
everything should work the same way. all tests pass.
n/a. didn't add changeset as this change should be "transparent" to the user.
> bump floating-ui

- CONTRIBUTING.md
I noticed that the warning to build the css-workshop before testing a particular component was missing. This PR adds that warning.
Confirmed that running `yarn build --filter=css-workshop` before `yarn workspace css-workshop --filter=table` fixes the stale testing images issue.
N/A
> Added "build css-workshop before testing particular component" warning

- .changeset/plenty-icons-cry.md
- packages/itwinui-react/package.json
This fix is intended for webpack users.
When using ESM, webpack will apply it's treeshaking too harshly sometimes.
This applies to imported css files too.
Possible webpack bug: https://github.com/webpack/webpack/issues/7094
Fixes #1737 
Added `styles.css` to `sideEffects` in `package.json`
"N/A"
"N/A"
> Added styles.css to sideEffects

- .changeset/forty-pets-warn.md
- packages/itwinui-react/src/core/Select/Select.tsx
- packages/itwinui-react/src/core/Slider/Slider.tsx
- packages/itwinui-react/src/core/Slider/Thumb.tsx
1. fixed types to allow `ref` in `triggerProps` and `thumbProps`.
2. fixed runtime JS to correctly merge refs
n/a.
n/a
> allow passing refs in Select and Slider

- .changeset/gentle-worms-dance.md
- packages/itwinui-react/package.json
- packages/itwinui-react/src/core/NonIdealState/ErrorPage.tsx
fixes https://github.com/iTwin/iTwinUI/pull/1742#discussion_r1430493256 which happens because `ErrorPage` is part of the barrel file (`index.js`), resulting in bundlers trying to resolve everything even if it's not used (it later gets tree-shaked)
first i tried `catch`ing these errors ([`a6c4039`](https://github.com/iTwin/iTwinUI/pull/1744/commits/a6c40392023184eeb05b10dbca013f5de4c56812)), but vite and nextjs don't respect this `catch`. so i've resorted to moving it from a peer dependency to direct dependency.
this effectively undoes the breaking change, so users have one less thing to worry about. and if `ErrorPage` is not used, this *should not* be part of the final bundle, so no real downside there.
no more errors! i've done preliminary testing locally, but I plan to test in sandboxes …
> add direct dependency on illustrations

- apps/website/src/content/docs/themeprovider.mdx
- Added new `/themeprovider` page
- Added detailed documentation and examples for all the intricacies of `ThemeProvider`.
It is an incredibly complex component and I could easily go into way more detail, but I think I found a nice middle-ground.
something to be documented in the future: standalone usage of variables without `ThemeProvider`.
n/a
These *are* docs!
> add docs for `ThemeProvider`

- minimal-sandbox/src/styles.css
When creating playgrounds ([v2](https://stackblitz.com/edit/github-wy4lfv?file=src%2FApp.tsx), [v3](https://stackblitz.com/edit/github-7obvbo?file=src%2FApp.tsx)) for https://github.com/iTwin/iTwinUI-migration-tool/pull/96, I felt that having the overflow style by default would be helpful. This PR just adds that overflow style.
|Before|After|
|-|-|
|<img width="526" alt="image" src="https://github.com/iTwin/iTwinUI/assets/45748283/0ca49fa3-1fe0-422c-b81a-68c6ddc6b2a9">|<img width="527" alt="image" src="https://github.com/iTwin/iTwinUI/assets/45748283/867448b0-c367-48bf-89bc-9edd8c666265">|
Tested that the minimal-sandbox still looks alright on Stackblitz.
N/A
> Added overflow style to `minimal-sandbox`

- .vscode/settings.json
- apps/website/.stylelintrc.json
- internal/configs/.stylelintrc.json
- internal/configs/package.json
- packages/itwinui-css/package.json
- packages/itwinui-css/src/backdrop/backdrop.scss
- packages/itwinui-css/src/button/base.scss
- packages/itwinui-css/src/color-picker/color-picker.scss
- packages/itwinui-css/src/dialog/dialog.scss
- packages/itwinui-css/src/expandable-block/expandable-block.scss
- packages/itwinui-css/src/header/header.scss
- packages/itwinui-css/src/information-panel/information-panel.scss
- packages/itwinui-css/src/keyboard/keyboard.scss
- packages/itwinui-css/src/mixins.scss
- packages/itwinui-css/src/skip-to-content/skip-to-content.scss
- packages/itwinui-css/src/stepper/stepper.scss
- packages/itwinui-css/src/toggle-switch/toggle-switch.scss
- packages/itwinui-css/src/utils/notification-marker.scss
- packages/itwinui-variables/src/themes/light-hc.scss
- packages/itwinui-variables/src/typography.scss
- yarn.lock
part of #1571
- `prettier` is now used for formatting all scss files, both in the editor and in the pre-commit hook.
- ran `prettier` on all scss files to avoid random annoyances in future PRs.
- `stylelint` is only used for non-stylistic linting.
- .scss files are now allowed in `website/` (needed for #1751), with unnecessary rules disabled.
tested that linting and formatting works in both IDE and precommit hooks. 
n/a
> replace stylelint formatting rules with prettier

- .changeset/nervous-chairs-grow.md
- packages/itwinui-react/src/core/Dialog/DialogMain.tsx
#1693 broke full page modal, so now excluding the `transform` style based on `styleType`.
before: https://itwin.github.io/iTwinUI/legacy/v2/react/?path=/story/core-modal--full-page-modal
after: https://itwin.github.io/iTwinUI/1765/react/?path=/story/core-modal--full-page-modal
added changeset
> v2: fix full page modal not showing up

- .changeset/lazy-dancers-applaud.md
- packages/itwinui-react/src/styles.js/classes.mjs
- packages/itwinui-react/src/styles.js/vite.config.mjs
Replaced the [`styles` object](https://unpkg.com/browse/@itwin/itwinui-react@3.2.1/esm/styles.js) with a proxy. The giant object is not needed, since we are not using a proper hash in our css modules scoping. The proxy simply transforms the class names at runtime.
In the future if we ever use proper hashing, we can bring back the object.
Note: I had to enable minification because we are now relying on a side-effect import to include all the styles. Without enabling minification, Vite will not tree-shake the giant object even if it's not exported or used anywhere.
Everything works the same. All tests pass.
Verified that the bundle size is actually reduced. The difference is ~20KB (or ~4KB compressed).
| --- | --- |
| …
> use a proxy for styles object to reduce bundle size

- .changeset/metal-starfishes-juggle.md
- packages/itwinui-react/package.json
a user wants to import `package.json` for some reason, so adding it to `exports`.
tested that this import works:
```js
import { version } from '@itwin/itwinui-react/package.json';
```
n/a
> expose `package.json` in `exports`

- apps/website/src/components/HomepageBanner.astro
- apps/website/src/icons/RightArrowIcon.astro
- apps/website/src/pages/index.astro
Added new `HomepageBanner` component for announcing new updates. It's a simple link within an `aside`.
For now it just links to the migration guide, but I assume we will want to look to a proper page within the docs in the future.
Modified `RightArrowIcon` to support individually modifying the line and the caret, for hover effect (try hovering yourself, i won't spoil the effect).
See deploy preview: https://deploy-preview-1775--itwinui-previews.netlify.app/
Tested on narrow widths as well.
N/A
> add banner on homepage

- .changeset/healthy-windows-whisper.md
- packages/itwinui-css/src/menu/mixins.scss
Firefox 121 shipped with `:has` support but has a [nasty bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1874042) where `:has` breaks the other selectors used inside `:is` or `:where`. This bug specifically affected `MenuItem` which uses `:has` inside `:where` for focus outlines.
This PR moves the `:has` part out of `:where` which avoids the Firefox bug.
Verified that focus outlines appear correctly.
| --- | --- |
| <p>https://github.com/iTwin/iTwinUI/assets/9084735/1a9ec520-a4fb-415e-9ead-72ed8b203a47</p> | <p>https://github.com/iTwin/iTwinUI/assets/9084735/1a5b63fc-08a1-4132-a2a7-f8fdbfae9974</p> |
Bug can repro'd in live storybook using keyboard ([ComboBox](https://itwin.github.io/iTwinUI/react/?story=combobox--basic))
> fix menu item focus outline in firefox

- apps/react-workshop/src/Icon.stories.tsx
- Add missing `size='auto'` to `<Icon>`.
- Built locally and tested in the browser.
n/a
> Fix autoscale icon story

- .changeset/plenty-garlics-laugh.md
- .changeset/spicy-rocks-applaud.md
- packages/itwinui-css/src/utils/link-action.scss
Follow-up to #1762 where I ran into the issue of `LinkAction` overriding other styles when used with the `as` prop.
This PR is a "quick fix" that addresses the problem today by nullifying the specificity (thus giving priority to anything else).
A "proper" solution would likely involve using nested cascade layers to full control the order of styles, but that can happen in the future.
Tested that this code preserves `Anchor` styling:
```jsx
<LinkBox>
<LinkAction as={Anchor} href='#'>Hello</LinkAction>
</LinkBox>
```
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/d18719a3-3928-4499-b0e7-3042ab376cfd) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/455eb9c4-060a-4cf2-b6fc-7446e67550d3) |
N/A. Added changesets.
> decrease `LinkAction` specificity

- .changeset/purple-queens-divide.md
- .changeset/twenty-phones-dream.md
- apps/react-workshop/src/ComboBox.stories.tsx
- apps/react-workshop/src/InputGrid.stories.tsx
- apps/react-workshop/src/Label.stories.tsx
- apps/website/src/content/docs/inputgrid.mdx
- examples/FileUpload.wrappinginput.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxInputContainer.tsx
- packages/itwinui-react/src/core/InputGrid/InputGrid.test.tsx
- packages/itwinui-react/src/core/InputGrid/InputGrid.tsx
- packages/itwinui-react/src/core/LabeledInput/LabeledInput.tsx
- packages/itwinui-react/src/core/LabeledSelect/LabeledSelect.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
- packages/itwinui-react/src/core/utils/components/InputWithIcon.tsx
- packages/itwinui-react/src/core/utils/components/index.ts
If a user forgets to connect `Label`/`Input`/`StatusMessage` inside `InputGrid`, we will now handle it for them by cloning `children`.
Since `InputGrid` is also used internally in `LabeledInput`/`LabeledSelect`, I was able to remove some of the explicit id handling in those components.
Lastly, the `StatusMessage` being connected via `aria-describedby` is brand new functionality that we weren't handling before at all, so this is a net improvement for all uses of the `message` prop.
Implementation notes:
- Looping/cloning children is generally [discouraged](https://react.dev/reference/react/Children) and indeed can be quite brittle (breaks if there are wrapper divs anywhere), but it is still a very useful fallback and just a convenient thing.
- It helps ease the v2→v3 migration specifically …
> automatically associate inputs, labels and messages

- .changeset/silent-knives-search.md
- apps/website/src/content/docs/linkaction.mdx
- apps/website/src/content/docs/list.mdx
- examples/List.links.tsx
- packages/itwinui-react/src/core/List/ListItem.tsx
follow-up to https://github.com/iTwin/iTwinUI/pull/1762#discussion_r1443202152
N/A. The new component is a direct reference to the old one, so no tests needed.
Updated docs and added changeset.
> expose `ListItem.Action` to wrap `LinkAction`

- apps/website/src/content/docs/linkaction.mdx
- examples/LinkAction.nested.tsx
- examples/index.tsx
Another follow-up to #1762.
1. Updated the main example to make it look clickable (using `Anchor` which now takes priority, thanks to #1788). Addresses [this thread](https://github.com/iTwin/iTwinUI/pull/1762#discussion_r1440690501).
2. Added a live example to show secondary actions. This is achieved by simply nesting `LinkBox`es to create "holes"; no new component needed. Since `LinkBox` has `position: relative`, it appears above the rest of the content. Addresses [this thread](https://github.com/iTwin/iTwinUI/pull/1762#discussion_r1443149939).
N/A. No code changes.
See [deploy preview](https://deploy-preview-1793--itwinui-previews.netlify.app/docs/linkaction).
These *are* docs.
> update `LinkAction` docs to show secondary link

- .changeset/rude-rockets-occur.md
- packages/itwinui-css/src/surface/surface.scss
Fixes #1801 
The main change is removing `both-edges` from the value of `scrollbar-gutter`. It's fine on the right side, but we cannot rely on it for alignment purposes on the left side.
I've added a code comment with a more detailed rationale. Also see my comment on the linked issue.
Verified that the surface body and header stay aligned regardless of scrollbar visibility.
https://github.com/iTwin/iTwinUI/assets/9084735/8e838d05-6a81-4a01-b3df-fff164124ca7
> fix `Surface` alignment by not relying on `scrollbar-gutter`

- packages/itwinui-react/src/core/FileUpload/FileUploadTemplate.tsx
Based on https://github.com/iTwin/iTwinUI-migration-tool/pull/99#issuecomment-1875506489.
This small PR just adds a link to the [`FileUploadCard`](https://itwinui.bentley.com/docs/fileupload#fileuploadcard) docs site page in the `FileUploadTemplate` deprecation message.
N/A
N/A
> Include docs link in `FileUploadTemplate` deprecation message

- .changeset/nervous-nails-add.md
- packages/itwinui-react/src/core/Modal/Modal.test.tsx
- packages/itwinui-react/src/core/Modal/Modal.tsx
Addresses second point of https://github.com/iTwin/iTwinUI/issues/1368#issuecomment-1911812509
Added unit tests for new props.
Added changesets.
> add new props for customizing internal `Modal` elements

- .changeset/empty-geckos-joke.md
- .changeset/four-years-beam.md
- .changeset/moody-turtles-vanish.md
- apps/website/src/content/docs/linkaction.mdx
- apps/website/src/content/docs/tag.mdx
- packages/itwinui-react/src/core/LinkAction/LinkAction.test.tsx
- packages/itwinui-react/src/core/LinkAction/LinkAction.tsx
- packages/itwinui-react/src/core/Tag/Tag.test.tsx
- packages/itwinui-react/src/core/Tag/Tag.tsx
When working on demos for interactive `Tag`s (#1815), I realized that the type error when simultaneously using `onClick` and `onRemove` is not enough. The component still renders (no runtime error) with nested buttons. This has a risk of the developer suppressing the type error without giving it further thought.
This PR remedies that by conditionally using `LinkAction` only when both `onClick` and `onRemove` are passed. `LinkAction` will avoid invalid markup while preserving the same clickable area, i.e. clicking anywhere on the tag invokes `onClick` and clicking on the ❌ button invokes `onRemove`. I probably still wouldn't recommend this pattern, but it's better than before.
Also `LinkAction` itself has been updated to automatically render `<button>` (rather than `<a>`) by default when …
> use `LinkAction` inside `Tag`

- packages/itwinui-react/src/core/utils/hooks/useResizeObserver.test.tsx
I realized that my [changes](https://github.com/iTwin/iTwinUI/pull/1800/files#diff-111a171304fb0e2aad0260c14c55be12ba9eec60849ded2562386a1d16fa7948) in `useResizeObserver.test.tsx` from #1800 might not have been the correct way to fix the failing test. I confirmed this by adding a `console.log("HERE")` and noticing that this log was not printed.
<details>
<summary>Code</summary>
```diff
// Wait for one frame
requestAnimationFrame(() => {
+ console.log("HERE");
expect(onResizeMock).toHaveBeenCalledWith(newSize);
});
```
</details>
So, this PR `await`s a `Promise` instead of the old method from #1800. I confirmed that this works by adding the same `console.log` and confirming that it was printed in the console.
<details>
<summary>Code</summary>
```diff
// Wait for one frame
await new …
```
> Fix flaw in `useResizeObserver`'s unit test

- .github/workflows/changeset-release.yml
- package.json
- yarn.lock
After #1826, the changesets workflow broke (the one part I didn't think of testing before merging 🤦). https://github.com/iTwin/iTwinUI/actions/runs/7818098835/job/21327516305
Changesets includes a _lot_ of outdated dependencies, so instead of trying to fix it, I've removed the dependency altogether. I love changesets but it is starting to look like an unmaintained project, and its dependency management situation is unhealthy for the ecosystem at large. By excluding it, we're able to avoid unnecessary problems with shared transitive deps.
`@changesets/cli` will now be automatically installed on-demand using `npx`. Everything should work the same as before, other than maybe a small delay when running this command (can be worked around by installing globally if you care about this).
Tested …
> remove local dependency on changesets

- .changeset/violet-games-raise.md
- packages/itwinui-react/setupTests.ts
- packages/itwinui-react/src/core/Dialog/DialogMain.tsx
- packages/itwinui-react/src/core/Table/Table.test.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
- packages/itwinui-react/src/core/utils/components/Resizer.tsx
- packages/itwinui-react/src/core/utils/components/ShadowRoot.test.tsx
- packages/itwinui-react/src/core/utils/components/ShadowRoot.tsx
- packages/itwinui-react/src/core/utils/components/index.ts
This is a slight refactor of the `Resizer` component used in `Dialog`.
- It is now rendered inside shadow DOM, and its styles have been updated to use CSS grid for positioning. As an added benefit of shadow DOM, I was able to use a plain `<style>` here (vs inline styles) without causing performance issues.
- User-facing change: It now protrudes outside the edge of the dialog, as originally intended (before it was reversed in #1424 due to `overflow`, which was recently removed in #1795).
- Screenshot below visualizes the resizers (corners in hotpink, perpendiculars in wheat); the corner resizers appear on top using a higher z-index.
Internal change: Extracted out `ShadowTemplate` into a shared component and renamed to `ShadowRoot`. Updated the logic inside to correctly handle isomorphic …
> move dialog resizers into shadow dom

- .changeset/spotty-glasses-sell.md
- packages/itwinui-css/src/input-container/input-container.scss
Fixes #1849
Previously, `all: unset` was being used to undo focus outlines. In #1362 (v3), a global focus outline was added, requiring an explicit override for `:focus`.
The actual focus styling still shows up via the container's `:has(:focus-visible)`/`:focus-within` rules.
Somewhat difficult to test this locally, as the bug requires using multiple versions, but I was able to test the fix in the linked issue's sandbox by dynamically adding this style in devtools.
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/ef2f55d7-e416-4bb4-92b8-6ba8c5bc7aab) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/f361809d-9477-4a71-bf48-5bbc5c8388bc) |
> fix v2 SearchBox outline

- playgrounds/astro/src/pages/_layout.astro
- playgrounds/next/pages/_app.tsx
- playgrounds/vite/src/main.module.css
When testing #1828 by adding many input containers in a long vertically overflowing `Flex`, I realized that the overflow style was missing on the playgrounds' containers. So, I thought it would be good to add `overflow: auto` to all playgrounds, similar to #1752.
|Old|New|
|-|-|
|![image](https://github.com/iTwin/iTwinUI/assets/45748283/92247092-5afe-400e-b268-a76132fdaad3)|![image](https://github.com/iTwin/iTwinUI/assets/45748283/d752341e-8560-4a73-8bec-cd17410d608b)|
Confirmed that all playgrounds overflow correctly when the content overflows.
N/A
> Added overflow style to all playgrounds

- apps/website/src/components/LiveExample.astro
- apps/website/src/components/OpenInCodePen.astro
- apps/website/src/pages/_global.scss
- examples/index.tsx
Moves all live example demos into shadow DOM (using [declarative template syntax](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM#declaratively_with_html), with firefox fallback), so that the CSS selectors are automatically scoped. This helps address https://github.com/iTwin/iTwinUI/pull/1854#discussion_r1488609044.
Added basic handling of `.css` example files to be inlined into a `<style>` inside shadow DOM.
Tested that existing demos work fine. Also verified behavior by creating a `.css` example file (not committed). Further testing will be done in #1854.
N/A
> move live demos into shadow dom

- .changeset/four-hairs-hear.md
- .changeset/fresh-bananas-judge.md
- packages/itwinui-variables/src/index.scss
Added [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) at the entrypoint. This is similar to #1360 where [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) was added.
Motivation: Helps native elements fit better within the design system. (I recently discovered a rogue `<progress>` element in an application and it looked very out of place).
As for the value, the `--iui-color-border-accent` variable most closely matches what is already used in our components.
Can be tested manually in the vite playground by using native elements:
```jsx
<progress></progress>
<input type='checkbox' />
<input type='range' />
```
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/98e4aa83-52f2-403e-893b-78afa6be …
> add `accent-color` to global styles

- .changeset/sour-masks-sleep.md
- packages/itwinui-react/src/core/utils/icons/Svg.tsx
Added `width`/`height` attributes to svgs that are used within our components. Without them, the svgs depend on the CSS. If the CSS doesn't specify the size (or fails to load), then the svg fills up the entire container (sometimes the entire page). This is just a "nice" thing to do; very minimal impact.
Verified that the attributes appear in the output. No rigorous testing needed.
> add fallback size for inlined svgs

- .changeset/neat-walls-fix.md
- packages/itwinui-react/src/core/Select/Select.test.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
`Select` had a small (but significant) bug where it wouldn't respect `value={null}` and instead enter uncontrolled mode. This is annoying when trying to reset the value.
This PR fixes it by updating the logic to match the [`useControlledState`](https://github.com/iTwin/iTwinUI/blob/mayank/select-null/packages/itwinui-react/src/core/utils/hooks/useControlledState.ts) hook.
Tested in playground and added a unit test.
<details><summary>App.tsx</summary>
```tsx
import * as React from 'react';
import { Button, Select } from '@itwin/itwinui-react';
export default function App() {
const [value, setValue] = React.useState<number | null>(2);
return (
<>
<Select
value={value}
onChange={setValue}
options={[
{ value: 1, label: 'Option 1' },
{ value: 2, label: 'Option 2' },
{ value: 3, label: 'Option …
```
> `Select`: fix `null` value handling

- .changeset/sour-bears-applaud.md
- apps/website/src/content/docs/progressindicator.mdx
- packages/itwinui-react/src/core/ComboBox/ComboBox.test.tsx
- packages/itwinui-react/src/core/ProgressIndicators/ProgressLinear.test.tsx
- packages/itwinui-react/src/core/ProgressIndicators/ProgressLinear.tsx
- packages/itwinui-react/src/core/ProgressIndicators/ProgressRadial.test.tsx
- packages/itwinui-react/src/core/ProgressIndicators/ProgressRadial.tsx
- packages/itwinui-react/src/core/Select/Select.test.tsx
- packages/itwinui-react/src/core/VisuallyHidden/VisuallyHidden.test.tsx
- packages/itwinui-react/src/core/VisuallyHidden/VisuallyHidden.tsx
- packages/itwinui-react/src/core/utils/components/ShadowRoot.tsx
`ProgressRadial` and `ProgressLinear` are empty divs that do not hold semantics. This is fine for sighted users, since a visual loading indicator is a pretty well-understood pattern. However, non-sighted users do not get any indication at all.
This PR tries to remedy that by using a visually-hidden "Loading" message. Screen-readers will read this out just like any other regular text.
This visually hidden text is located inside shadow DOM. To make this work I had to change the `VisuallyHidden` component to include styles (global styles do not affect elements inside shadow DOM). This in turn required some changes in the `ShadowRoot` component.
**Note:** A much better solution would be to use the [`progressbar` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progre …
> add visually hidden "Loading" text to progress indicators

- examples/DatePicker.menu.jsx
- examples/DatePicker.withcombinedtime.jsx
- examples/DatePicker.withtime.jsx
Adds `Popover` elements to 3 `DatePicker` demos. These demos are the 2 Date + Time demos and the Usage demo. The usage demo was updated to show `esc` key functionality. Because the example did not previously use the popover element, the picker could not be closed with the `esc` key. This change fixes that. It also fixes an issue where the `DatePicker` page would scroll to the Date + Time section on load. This was being caused by the `TimePicker` component using the `scrollIntoView`(https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) method to make sure that the default values of the picker are displayed when the picker is rendered. This has the unintended effect of  scrolling the page if the picker is rendered on page load. Wrapping the picker in a popover button …
> Adds Popover elements to DatePicker demos

- .changeset/curly-ads-march.md
- packages/itwinui-react/src/core/InputGroup/InputGroup.test.tsx
- packages/itwinui-react/src/core/InputGroup/InputGroup.tsx
- playgrounds/vite/src/App.tsx
After-PR TODO from #1753 
Earlier, `message` was always wrapped in `<StatusMessage>`. This caused nested `<StatusMessage>`s when `message={<StatusMessage>}`. Nested StatusMessages could lead to double svgIcons:
<details>
<summary>Example code</summary>
```jsx
{/* ❌ Passing <StatusMessage startIcon={…} /> to the message of <InputGroup status="…" /> shows duplicate status icons */}
<InputGroup
label='Checkbox group'
status='positive'
message={
<StatusMessage startIcon={<SvgStar />} status='positive'>
Help message
</StatusMessage>
}
>
<Checkbox label='Select all' />
<Checkbox label='Football' />
<Checkbox label='Hockey' />
</InputGroup>
```
</details>
This PR now wraps `message` in `<StatusMessage>` only when `typeof message !== "string"`. This fixes the duplicate svgIcons issue.
As a result …
> Fix `InputGroup.message=<StatusMessage>` rendering two icons

- packages/itwinui-react/src/core/InputWithDecorations/InputWithDecorations.tsx
`InputWithDecorations`'s JSDocs refers a non-existent `InputWithDecorations.Icon` component. This PR replaces that with `Icon`.
I also noticed that the example in the JSDocs for InputWithDecorations was not formatted correctly. This PR also fixes this by replacing `@usage` with `@example`.
|Before|After|
|-|-|
|<img width="673" alt="image" src="https://github.com/iTwin/iTwinUI/assets/45748283/0d926104-0f33-4443-a260-b89e9e0c8957">|<img width="429" alt="image" src="https://github.com/iTwin/iTwinUI/assets/45748283/5a28b1a6-24fa-4600-a606-ea48dc78c851">|
* Confirmed that the example in `InputWithDecorations`'s JSDocs is now formatted correctly.
* Did a global search for `@usage` and found no other such issues.
* Did a global search for `InputWithDecorations.Icon` and confirmed that there are …
> Fix `InputWithDecorations` JSDocs

- apps/website/src/content/docs/flex.mdx
- apps/website/src/content/docs/progressindicator.mdx
- apps/website/src/content/docs/table.mdx
- apps/website/src/content/docs/toast.mdx
- apps/website/src/content/docs/tree.mdx
- apps/website/src/content/docs/typography.mdx
This PR fixes the `<Placeholder>` links on the docs site that should navigate to the `Basic` or first story for that component.
Ensured that clicking the story link in the placeholder navigates to the correct story.
N/A
> Fix `<Placeholder>` react stories' links on docs site

- .changeset/silly-rockets-sip.md
- packages/itwinui-css/src/avatar/avatar.scss
- packages/itwinui-css/src/header/header.scss
- packages/itwinui-css/src/side-navigation/side-navigation.scss
- packages/itwinui-css/src/slider/slider.scss
- packages/itwinui-css/src/tile/tile.scss
- packages/itwinui-css/src/tooltip/tooltip.scss
Ever since introducing layers, application styles always win and usually contain a box-sizing reset which overrides our layered styles. (This can even be seen in some of our playgrounds)
```css
/* This is zero-specificity but still wins over layered iTwinUI styles */
* {
box-sizing: border-box;
}
```
The correct solution would be for applications to put their resets in a lower-priority layer, but they might not even realize this needs to be done (even though it's [documented](https://github.com/iTwin/iTwinUI/wiki/Styling)), or it might be coming from third-party styles. Adding `!important` helps avoid these issues altogether, serving as a safeguard and reducing the onus on applications.
**Note**: `!important` is generally frowned upon because it is overused as a hack for specificity …
> reinforce `content-box` using `!important`

- .changeset/sharp-gorillas-search.md
- packages/itwinui-react/src/core/Table/Table.test.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
Fixes #1899.
The root cause was that the initial value of `lastPassedColumns` is `[]` so it was always resetting the columns. `[]` is never valid so I've added a simple check for it.
Tested in playground (using [linked sandbox](https://stackblitz.com/edit/github-y5zcvc?file=src%2FDraggableColumns.tsx)) and added unit test.
N/A
> fix Table `columnOrder` resetting incorrectly

- .changeset/hungry-hats-think.md
- packages/itwinui-react/src/core/InputGroup/InputGroup.tsx
This PR fixes an issue that @mayank99 noticed: some variables were added to `InputGroup`'s DOM as attribute-value pairs.
This was happening because in #1877, I was no longer deconstructing the variables passed to the new helper component, `BottomMessage`. Thus, the non-deconstructed variables were included in `rest` and added to the DOM.
This PR fixes that by properly deconstructing the props that shouldn't be in the DOM and then passing them down to the helper component (`BottomMessage`).
Confirmed manually that `BottomMessage` props are no longer showing up in the DOM.
I thought against having unit tests since this might be too specific. But I can add it if anyone feels differently.
<details>
<summary>App.tsx (vite-playground)</summary>
```jsx
import { SvgStar } from …
```
> No more incorrect rest props in `InputGroup`'s DOM

- .changeset/tame-foxes-deliver.md
- packages/itwinui-css/src/dialog/dialog.scss
Fixes #1904 by removing `whitespace: nowrap`, along with other redundant CSS declarations.
Tested by manually recreating the linked issue in playground.
N/A
> fix dialog title overflow

- package.json
Pnpm seems to require quotes when passing ambiguous arguments, or it will fail.
Works locally.
Not possible to test this specific workflow in CI until the PR merges, *but* we have used this exact command (with quotes) in CI in another place, where it works fine.
https://github.com/iTwin/iTwinUI/blob/28416c116f21989040d2fb5f67b29ab123867ab9/.github/workflows/build.yml#L78
N/A
> fix release command

- CONTRIBUTING.md
@AdamMeza-Bentley noticed some issues with running pnpm's `--filter` without an `=` inside of [`spawn`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options). This PR updates the `CONTIRBUTING.md` to use `=` in pnpm's`--filter`, to ensure the filtering always works.
Additionally, it uses `run` instead of having to use `--` to pass args to the inner script.
Tested the modified commands to ensure that they still work as expected.
N/A
> Fix commands with pnpm's `--filter` in `CONTRIBUTING.md`

- .github/workflows/changeset-release.yml
- apps/css-workshop/package.json
- apps/portal/package.json
- package.json
- packages/itwinui-css/package.json
- packages/itwinui-react/package.json
- pnpm-lock.yaml
- turbo.json
After lots of iteration and experimentation, this PR makes the following changes:
- Ignores `@itwin/itwinui-css` from `pnpm changeset version`, so that its version does not get bumped.
- Makes it `private` to prevent accidental publish (until major release is ready).
- Removes it from dependencies of all workspaces, and adjusts turbo pipeline to manually depend on it.
- This is necessary because `pnpm changeset` does not allow adding changesets to packages that depend on ignored workspaces.
As a result, the `main` branch can be used to add `major` changesets to `@itwin/itwinui-css`. When releasing, it will be ignored without blocking the normal release of other packages.
Only difference to regular workflow is that itwinui-css changesets now always need to be standalone, rather than being …
> setup partial premajor releases for css

- .github/workflows/changeset-release.yml
Updates release workflow to add manual checks for changeset files and release PR.
- To check for changeset files, [`changeset status`](https://github.com/changesets/changesets/blob/main/docs/command-line-options.md#status) is combined with a simple if-condition to exclude `@itwin/itwinui-css` (since it is supposed to be ignored).
- To check for release PR, [`git ls-remote`](https://stackoverflow.com/a/30524983) is used to find the `changeset-release/main` branch (well-defined name).
Based on the checks, two outcomes are possible:
- When a changeset file or release PR is found, let changesets create/update the release PR.
- If release PR does not exist, manually run `pnpm release`. This will publish to npm or do nothing if already published.
Fixes …
> add custom release step

- packages/itwinui-css/src/global.scss
- packages/itwinui-css/src/mixins.scss
- packages/itwinui-css/src/table/base.scss
Removes four sass mixins from the global mixins file in the css package. These mixins are:
- `iui-ripple`
- `iui-scroll-snapping`
- `pseudo-content`
- `iui-scrollbar`
In the cases where these mixins were used, their styles were placed instead. Therefore, there should be no changes to end users from this PR.
Ran css and react visual tests to make sure there were no visual changes from the removal of these mixins.
N/A
> Removes unnecessary global mixins.

- packages/itwinui-react/CHANGELOG.md
In #1877, I had made a mistake in the [changeset file](https://github.com/iTwin/iTwinUI/pull/1877/files#diff-c03ef64bfbfbe72b8b344d4a3469daa68af3d3590934b6b70c5e87761a6b019a) where I mentioned `LabeledSelect` instead of `InputGroup`. This PR fixes the changelog to correctly mention `InputGroup` in that bullet point.
I realized that I also would need to update the [v3.6.0 GitHub release](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.6.0). But before doing that, I wanted to confirm if this is alright by first having this PR and then changing the GitHub release. 
N/A
N/A
> Corrected `@itwin/itwinui-react@3.6.0` changelog

- .changeset/itchy-swans-jog.md
- packages/itwinui-react/src/react-table/react-table.ts
A user pointed out that we have an `includesSome` function in `defaultFilterFunctions`:
https://github.com/iTwin/iTwinUI/blob/84007fe670a9ca85f82f230c3458c0a73fd1b622/packages/itwinui-react/src/core/Table/filters/defaultFilterFunctions.ts#L119-L134
… but don't have `includeSome` in `DefaultFilterTypes`:
https://github.com/iTwin/iTwinUI/blob/84007fe670a9ca85f82f230c3458c0a73fd1b622/packages/itwinui-react/src/react-table/react-table.ts#L747-L755
This PR adds `includesSome` to `DefaultFilterTypes` so that users can get `"includesSome"`  as a type suggestion for the `filter` prop and udpates the list of possible values in the JSDocs accordingly.
Unrelated: Fixed the broken GitHub file link in the `filter` JSDocs.
Tested that passing `filter: "includesSome"` to a column even before this PR …
> Added `includesSome` to `DefaultFilterTypes` in Table

- .changeset/tricky-vans-jam.md
- packages/itwinui-react/src/core/ButtonGroup/ButtonGroup.tsx
When `overflowButton` is not passed to `ButtonGroup`:
1. Early return `children`
2. Don't attach `overflowRef` 
Fixes #1923
Recreated the sandbox from linked issue and verified that `children.length` is 4 (not 2) after clicking "Calculate overflow".
No tested added, since this is more of an optimization (the final result is correct even before this PR, because it eventually re-renders into correct state).
> ButtonGroup: conditionally run overflow logic

- .changeset/ten-mayflies-compete.md
- packages/itwinui-react/src/core/Table/columns/actionColumn.tsx
After column is resized and user enables/disables some column, will no longer scroll down to the action column
Did not add tests, this is pretty simple scenario
See https://github.com/iTwin/iTwinUI/pull/1946#pullrequestreview-1958154941 for repro code and testing results.
"N/A"
Issue: #1945
> fix: :bug: Do not auto-scroll vertically when enabling/disabling table columns

- apps/css-workshop/src/components/Badge.astro
- apps/css-workshop/src/pages/badge.astro
- apps/css-workshop/src/pages/tile.astro
- Created reusable `Badge.astro` with props for backgroundColor and status.
- Used it in main `badge.astro` (page).
- This required renaming the imported component to disambiguate between `badge.astro` and `Badge.astro`. (Workaround for bug in Astro)
- Used it in other pages: `tile.astro`
All existing tests should pass.
N/A
> create Badge component for css-workshop

- .changeset/modern-games-pump.md
- .changeset/warm-ravens-refuse.md
- packages/itwinui-css/src/table/base.scss
I noticed that the `iui-table-resizer` appears above the sticky header cells. This small PR fixes that.
<details>
<summary>Before/After</summary>
[Before](https://itwin.github.io/iTwinUI/react/?story=table--full2&theme=dark):
https://github.com/iTwin/iTwinUI/assets/45748283/3548b793-9848-4257-b7b5-c56fc10c3b5d
[After](https://itwin.github.io/iTwinUI/1943/react/?story=table--full2&theme=dark):
https://github.com/iTwin/iTwinUI/assets/45748283/dcf90a1f-6430-4ee5-b657-89046d1340b7
</details>
Confirmed that the table resizer now appears below the sticky header cells.
Added changesets.
> Fix `Table` resizer z-index

- .changeset/polite-apricots-prove.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
This essentially backports #1735 to v2. It's necessary for applications to incrementally migrate to v3 while maintaining a coherent look.
(I've already noticed a few places where theme v2 UI stays in light theme when application theme switches to dark)
Tested behavior in vite playground by installing `itwinui-v3` as an npm alias.
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/44cb9de7-c720-463a-a830-00d894c9512f) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/2d71fe41-c58b-49f6-81e7-4524b68152e9) |
<details><summary>main.tsx</summary>
```tsx
import * as React from 'react';
import { createRoot } from 'react-dom/client';
import styled from '@emotion/styled';
import { ThemeProvider } from '@itwin/itwinui-react';
import { ThemeProvider …
```
> v2: inherit theme changes from v3

- pnpm-lock.yaml
Fixes https://github.com/advisories/GHSA-rv95-896h-c2vc
`pnpm audit` passes locally and in [CI](https://github.com/iTwin/iTwinUI/actions/runs/8438641082/job/23111368907?pr=1952)
N/A
> bump `express` to `4.19.2`

- .changeset/great-news-beg.md
- .changeset/little-mugs-tap.md
- examples/Tabs.actions.css
- examples/Tabs.actions.jsx
- examples/Tabs.borderless.css
- examples/Tabs.borderless.jsx
- examples/Tabs.controlled.css
- examples/Tabs.controlled.jsx
- examples/Tabs.main.css
- examples/Tabs.main.jsx
- examples/Tabs.pill.css
- examples/Tabs.pill.jsx
- packages/itwinui-css/src/tabs/base.scss
- pnpm-lock.yaml
Adds `inline-size: 100%` to horizontal tabs wrappers. This change is meant to counteract an issue caused by this [PR](https://github.com/iTwin/iTwinUI/pull/1884), where adding `contain: inline-size` caused the tabs wrapper to change it's implicit width.
Ran css and react visual tests to make sure that there are no unintended visual changes.
Added patch changesets to both the react and css packages.
> Adds inline-size to horizontal tabs wrapper.

- packages/itwinui-react/src/core/utils/hooks/index.ts
- packages/itwinui-react/src/core/utils/hooks/useMediaQuery.ts
- packages/itwinui-react/src/core/utils/hooks/useSyncExternalStore.ts
[`useSyncExternalStore`](https://react.dev/reference/react/useSyncExternalStore) is a hook added in React 18 that makes it easier to subscribe to DOM APIs and support server-side rendering.
This PR adds a shim that makes it possible for this hook to be used in React 17 (falls back to simple `useLayoutEffect`/`useEffect`). This is adapted from [React's source code](https://github.com/facebook/react/tree/main/packages/use-sync-external-store) and has been shortened to remove unnecessary parts like warnings and comments. I wanted to use the published [npm package](https://www.npmjs.com/use-sync-external-store), but it only supports CJS :/
To start off, `useMediaQuery` has been updated to make use of this hook.
In future PRs, we can add it in other places for more useful things.
Tested that …
> add shim for `useSyncExternalStore`

- apps/react-workshop/.ladle/components.tsx
- packages/itwinui-react/src/core/utils/components/ShadowRoot.tsx
This is left over from #1962
Basically, in [strict mode](https://react.dev/reference/react/StrictMode), react executes all effects a bunch of times, so the shadow-root was getting cleared right after its content was mounted. The only way around this is to avoid clearing a shadow-root if the `shadowRoot` state variable has already been set.
I used this code in vite playground `App.tsx` to test manually in dev:
```tsx
export { Full2 as default } from '../../../apps/react-workshop/src/Table.stories.tsx';
```
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/2f4a6b24-c847-421e-bcb4-4690fbfbdd98) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/15253179-0022-4427-8844-f5d454dd8830) |
It isn't possible to write a reliable test for this, since …
> fix clearing of existing `shadowRoot` in strict mode

- packages/itwinui-react/.eslintrc.cjs
- packages/itwinui-react/src/core/Breadcrumbs/Breadcrumbs.tsx
- packages/itwinui-react/src/core/Dialog/DialogMain.test.tsx
- packages/itwinui-react/src/core/Header/HeaderButton.tsx
- packages/itwinui-react/src/core/Header/HeaderLogo.tsx
- packages/itwinui-react/src/core/LabeledSelect/LabeledSelect.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/NumberRangeFilter/NumberRangeFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/TextFilter/TextFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/customFilterFunctions.test.ts
- packages/itwinui-react/src/core/Tag/Tag.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
- packages/itwinui-react/src/core/utils/components/VirtualScroll.test.tsx
- packages/itwinui-react/src/core/utils/functions/dev.ts
- packages/itwinui-react/src/core/utils/functions/dom.test.tsx
- packages/itwinui-react/src/core/utils/functions/polymorphic.tsx
- packages/itwinui-react/src/core/utils/functions/react.ts
- packages/itwinui-react/src/core/utils/hooks/useDragAndDrop.test.tsx
- packages/itwinui-react/src/react-table/react-table.ts
Disabled the `no-explicit-any` lint rule.
typescript-eslint needs to chill out. Explicit `any` is totally fine when used in internal types and tests, as evidenced by the dozens of occurrences.
N/A
N/A
> lint: allow explicit `any`

- .changeset/fluffy-monkeys-protect.md
- packages/itwinui-react/src/core/utils/functions/dev.ts
Fixes https://github.com/iTwin/iTwinUI/discussions/1978
N/A. We do not use `jest` in this repo, so attempting to test this is futile.
> use `jest` without `globalThis` when detecting it

- .changeset/thick-years-shake.md
- .changeset/tricky-seas-appear.md
- apps/react-workshop/src/Table.stories.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DatePickerInput.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.tsx
- packages/itwinui-react/src/core/Table/filters/tableFilters.tsx
Resolves #1984 by forwarding the `showYearSelection` prop from `DatePicker`
Unrelated: also set `showDatesOutsideMonth` to `false` (the recommended value after #1822)
Added unit test.
Added changeset, updated story.
> expose `showYearSelection` from `DateRangeFilter`

- packages/itwinui-react/src/core/Select/Select.tsx
`LabeledSelect` forces a `styleType` even when it's disallowed for non-native Select. This PR ensures that it's handled correctly by `SelectButton`, rather than being passed to the `InputWithIcon` DOM element along with `...rest` props.
Tested that the prop doesn't appear in DOM
N/A. Too small of a change for changeset
> fix `styleType` being passed to DOM

- packages/itwinui-css/src/slider/slider.scss
This is the same change as https://github.com/iTwin/iTwinUI/pull/1963#discussion_r1546746144 but for vertical slider. I haven't inspected the minified CSS, but it's likely caused by improper minification in `esbuild`.
The simple work around is to split `::before` and `-track` into two separate rules.
| --- | --- |
| ![image](https://github.com/iTwin/iTwinUI/assets/9084735/feb1364e-170c-4460-b5fd-dc11032a9d2e) | ![image](https://github.com/iTwin/iTwinUI/assets/9084735/4c051879-2ae3-4d9d-bec4-f9b7b2955ba4) |
✅ [All (react-workshop) tests pass now](https://github.com/iTwin/iTwinUI/actions/runs/8634454402/job/23669968809?pr=1992#step:6:3750)
N/A. Users shouldn't encounter this change; it's mainly for react-workshop.
> work around incorrectly minified CSS in vertical slider

- .changeset/new-clocks-grin.md
- apps/website/src/content/docs/anchor.mdx
- packages/itwinui-react/src/core/Typography/Anchor.test.tsx
- packages/itwinui-react/src/core/Typography/Anchor.tsx
- packages/itwinui-react/src/core/Typography/Text.tsx
This is a follow-up to #1864. `Anchor`'s `underline` prop will default to `true` when used inside a `Text`. The implementation is done using a simple React context.
This change improves the accessibility, by adding an additional cue to differentiate links from surrounding text. See [Use of Color](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color). 
Added unit test + tested manually.
Added changeset + updated existing docs on `underline` to mention new behavior.
> underline `Anchor` inside `Text` by default

- apps/css-workshop/src/components/Blockquote.astro
- apps/css-workshop/src/pages/blockquote.astro
Adds `Blockquote` Astro component to `css-workshop`. Imported as `Blockquote_` in the `blockquote.astro` file.
Ran visual test to insure that adding this component caused no visual changes.
N/A
> Adds `Blockquote` Astro component.

- .changeset/thin-eagles-sparkle.md
- apps/react-workshop/src/Button.stories.tsx
- apps/website/src/content/docs/button.mdx
- packages/itwinui-react/src/core/Buttons/Button.test.tsx
- packages/itwinui-react/src/core/Buttons/Button.tsx
Simple rename of the (unreleased) `stretch` prop from #1971. `<Button stretched>` feels more appropriate as a declarative prop API.
Other options considered (which I think are worse):
- `isStretched`
- `fullWidth`
- `fullSpan`
- `fillContainer`
N/A
N/A
> rename `stretch` to `stretched`

- .changeset/lovely-pigs-chew.md
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
Fixes #2002, mainly by removing the `autoUpdate` function which was being executed even when the tooltip is closed. I also removed `floatingStyles` when the tooltip is closed, and memoized the `middleware` object to avoid recreating it on each re-render.
Manually tested that the performance issue is fixed, with 6x CPU slowdown in Chrome devtools.
<details><summary>Before</summary>
https://github.com/iTwin/iTwinUI/assets/9084735/34c602bd-4197-467a-939f-d8a62b918b83
</details> 
<details><summary>After</summary>
https://github.com/iTwin/iTwinUI/assets/9084735/77b9f38e-b179-4094-830e-57486e30c3b1
</details> 
> skip unnecessary calculations when `Tooltip` is not visible

- .changeset/gentle-seas-protect.md
- .changeset/lovely-pigs-chew.md
- packages/itwinui-react/src/core/Buttons/IconButton.test.tsx
- packages/itwinui-react/src/core/Slider/Slider.test.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
This addresses a user complaint about `Tooltip` staying in DOM even when not visible. This is normally necessary for ARIA to work, but since `IconButton` uses `ariaStrategy='none'`, we can remove the DOM element for this one specific scenario.
Manually verified in dev tools that the tooltip element is removed from DOM when it's not visible. Added a unit test for it too.
> remove `Tooltip` from DOM when ARIA is not used

- .npmrc
- package.json
This updates `pnpm` to latest (9.1.0) and prevents CI from failing when there is a new version of `pnpm` in the future.
N/A
N/A
> allow minor drift in `pnpm` versions

- .changeset/smart-flies-reflect.md
- packages/itwinui-react/src/core/Menu/MenuItem.tsx
- packages/itwinui-react/src/core/Popover/Popover.tsx
After PR TODO from #1942 (https://github.com/iTwin/iTwinUI/pull/1942#discussion_r1578323366).
To make the `safePolygon` work for even the non-last `MenuItem`s, looks like we needed to set [`blockPointerEvents: true`](https://floating-ui.com/docs/useHover#blockpointerevents). This PR makes that change.
This change is done in `usePopover` instead of `MenuItem` because `MenuItem` is the only component that has been using the hover trigger so far. So, making this change in `usePopover` is alright since it will not affect any other user component or our own internal component.
Additionally, to make it easier for users to hover over adjacent items instead of keeping the submenu open, [`requireIntent: false`](https://floating-ui.com/docs/usehover#requireintent) is removed …
> Floating UI `safePolygon` for non-last `MenuItem`s

- .github/workflows/build.yml
- package.json
- pnpm-lock.yaml
This is a follow-up to #2025 to fix failing CI (again) caused by a new version of `cypress` being available.
`13.8.1` is now pinned in main `package.json` resolutions and in `pnpx cypress install` step in CI.
CI passing. See [latest run](https://github.com/iTwin/iTwinUI/actions/runs/9003106576/job/24733030272?pr=2033).
N/A
> pin cypress binary version in CI

- packages/itwinui-react/src/core/ComboBox/ComboBoxMenu.tsx
This is a very small change in `ComboBox`, simply replacing `Menu` with `List` while keeping the `iui-menu` styling (necessary for surface, max-height, and overflow).
The reason this works is: `ComboBox` and `Menu` have very little in common. `ComboBox` even manages its own focus and keyboard navigation, so the extra logic from `Menu` is not necessary.
**Note**: This PR is not the end state; it is simply a small step towards our [larger plan](https://github.com/iTwin/iTwinUI/pull/1942#discussion_r1581201279). Hopefully it helps ease the implementation in #2021. One thing worth pointing out is that we still recommend using `MenuItem` with the [custom renderer](https://itwinui.bentley.com/docs/combobox#custom-renderer). This is because …
> use `List` instead of `Menu` in `ComboBox`

- packages/itwinui-react/src/core/ComboBox/ComboBoxMenu.tsx
- packages/itwinui-react/src/core/Select/Select.test.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
Similar to #2034, this replaces the `Menu` component which does not belong in `Select`.
Unlike `ComboBox`, this one was relying on the focus management and keyboard navigation from `Menu`, so I replaced those parts with [`Composite`](https://floating-ui.com/docs/composite) from floating-ui. I had to add a little bit of code to tell `Composite` which indexes are active and that it should automatically move focus when the Select is opened.
Manually tested all stories to make sure they're working as intended.
Had to slightly tweak a couple unit tests to make them pass.
N/A
> use `List` instead of `Menu` in `Select`

- packages/itwinui-react/src/core/ComboBox/ComboBoxInput.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
I stumbled upon some code in `Table.tsx` that seemed to be doing the same thing as our util function, `useLatestRef`. So, this PR replaces that code with `useLatestRef`. I also did a quick global search to make it in all other places I could find.
In `Tree.tsx`, after changing `flatNodesListRef` to use `useLatestRef`, I got a warning that `flatNodesListRef` should be added to the dep list of the adjacent `useEffect`. But I believe doing that will break the logic of the `useEffect`. Thus, I left that unchanged.
<details>
<summary>Relevant code from Tree.tsx</summary>
https://github.com/iTwin/iTwinUI/blob/f699eb774e74b1ee08a0edb7729f1e5446c2f8aa/packages/itwinui-react/src/core/Tree/Tree.tsx#L294-L313
</details>
All tests passing.
N/A
> Use `useLatestRef` internally

- internal/helpers/index.js
After #2024, @FlyersPh9 and I started noticing the below error when opening any docs site's pages with the path `/docs/…`
Seems like the `?url` in the import in LiveExample is causing some issue.
https://github.com/iTwin/iTwinUI/blob/f699eb774e74b1ee08a0edb7729f1e5446c2f8aa/apps/website/src/components/LiveExample.astro#L6
~This PR adds a [`resolve.alias`](https://vitejs.dev/config/shared-options.html#resolve-alias) for this import too.~ Instead changed the `resolve.alias` to be find and replacement rules (https://github.com/iTwin/iTwinUI/pull/2038#discussion_r1596099089).
Confirmed that the docs site's `/docs/…` pages open without any errors. Also confirmed that other workspaces continue working.
N/A
> Fix docs site import error when running the `dev` script

- examples/Input.separatelabel.css
- examples/Input.separatelabel.jsx
- internal/helpers/index.js
@FlyersPh9 pointed out that the alignment of the labels and the inputs in `Input.separatelabel.jsx` seemed incorrect ([link](https://itwinui.bentley.com/docs/input#standalone)):
This PR fixes that alignment by having one div with `display: grid` instead of two disjoint divs with `display: flex`:
Confirmed that the alignment of the labels and the inputs in `Input.separatelabel.jsx` now looks correct.
N/A
> Fix alignment in the `Input.separatelabel.jsx` docs site example

- .changeset/soft-peas-notice.md
- packages/itwinui-react/src/core/Surface/Surface.tsx
This fixes a small hydration error when using `Surface` with SSR environments like `next`/`remix`/`astro`.
**Before**:
```console
Warning: Prop `style` did not match.
Server: "null"
Client: "--iui-surface-elevation:;--iui-surface-border:"
```
**After**:
No more hydration error!
> use `undefined` instead of `''` in inline style

- testing/e2e/app/routes/DropdownMenu/spec.ts
- testing/e2e/app/routes/Table/spec.ts
Self-explanatory title. The lack of `await` makes tests randomly fail in CI.
See https://playwright.dev/docs/test-assertions
All tests continue to pass, hopefully more predictably now.
N/A
> add `await`s to e2e tests to reduce flakiness

- .changeset/quick-ligers-serve.md
- .changeset/tender-forks-visit.md
- apps/website/src/content/docs/tooltip.mdx
- packages/itwinui-css/src/tooltip/tooltip.scss
- packages/itwinui-react/src/core/Tooltip/Tooltip.test.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
When supported, [`popover=manual`](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API/Using#using_manual_popover_state) will be used to show the tooltip in the [top-layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer). In non-supported browsers, the attribute is ignored.
In addition to the `popover` attribute itself, there are only two changes:
- **JS**: Calling [`togglePopover`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/togglePopover) whenever the React state changes.
- This is guarded using `?.` for supporting older browsers.
- This also required adding a custom TS type, which can be removed in the future.
- **CSS**: Hiding the tooltip when [`:popover-open`](https://developer.mozilla.org/en-US/docs/Web/CSS/:popover-open) doesn't match.
I kept …
> use `popover` API in `Tooltip` if supported

- apps/website/package.json
- packages/itwinui-css/package.json
- pnpm-lock.yaml
1.24.1 → 1.25.0. See [release notes](https://github.com/parcel-bundler/lightningcss/releases).
This shouldn't change anything but we should try to be on the latest, since there are often bug fixes.
N/A
N/A
> bump `lightningcss` to `1.25.0`

- .changeset/happy-penguins-pump.md
- packages/itwinui-react/src/core/ComboBox/ComboBox.tsx
Very minor thing I noticed: `label` was showing up in DOM because we spread `...rest` props and weren't destructuring `label`.
| --- | --- |
| <img src="https://github.com/iTwin/iTwinUI/assets/9084735/eb5c0cc3-d913-4474-a825-2866d7fd35e3" width="350"> | <img src="https://github.com/iTwin/iTwinUI/assets/9084735/8a545300-5279-4c7f-b570-46a1435d8d01" width="350"> |
N/A
> remove `label` attribute from `ComboBox` options in DOM

- .changeset/light-jeans-cheer.md
- packages/itwinui-react/src/core/Table/cells/DefaultCell.test.tsx
- packages/itwinui-react/src/core/Table/cells/EditableCell.test.tsx
- packages/itwinui-react/src/core/Table/cells/EditableCell.tsx
I noticed that `EditableCell` was not merging the user's `className` and `style` properly with `cellElementProps`. As a result, when users would pass a `className` or `style`, it would override (instead of merging with) the `className` and `style` from `cellElementProps` and thus break the layout.
This PR fixes it by merging the user's `className` and `style` with `cellElementProps`, similar to [DefaultCell](https://github.com/iTwin/iTwinUI/blob/75a7a5ff70927059a14182021015822fcf5c6acf/packages/itwinui-react/src/core/Table/cells/DefaultCell.tsx#L79-L82).
Added unit tests for `DefaultCell` and `EditableCell` to confirm that the `className` and `style` are properly merged with `cellElementProps`.
Tested in the vite playground:
* [Current version …
> `EditableCell` properly merges user's `className`/`style` with inner props

- .changeset/shiny-trainers-heal.md
- packages/itwinui-react/package.json
Added explicit paths to support `"moduleResolution": "node16"` for `react-table`.
The change fixes #2072 
Can be tested with a consuming application using the specified module resolution. No tests should be required otherwise.
- None
> Added explicit import paths for 'react-table'

- packages/itwinui-css/src/field.scss
This is a very small CSS refactor of `iui-field` that incorporates the [cyclic space toggles](https://kizu.dev/cyclic-toggles/) technique to allow for easy switching between default vs hover vs disabled states.
Extracted out of #2076 for easier review.
Everything works exactly the same.
N/A.
> use cyclic state toggles in field CSS

- packages/itwinui-react/package.json
- pnpm-lock.yaml
Bumps [swc](https://swc.rs/) to latest version. Needed for #2100.
I had to add [`--strip-leading-paths`](https://swc.rs/docs/usage/cli#--strip-leading-paths) because the new version of `swc` was creating `esm/src/` and `cjs/src/` directories.
Verified that `pnpm run dev` continues to generate the correct output in `esm/` and `cjs/` directories.
N/A
> bump `swc`

- .changeset/itchy-insects-wink.md
- packages/itwinui-react/scripts/build.mjs
- packages/itwinui-react/src/core/Table/hooks/useColumnDragAndDrop.tsx
- packages/itwinui-react/src/index.ts
- packages/itwinui-react/src/styles.d.ts
- packages/itwinui-react/src/styles.js/index.mjs
- packages/itwinui-react/src/styles.js/vite.config.mjs
- packages/itwinui-react/src/utils/components/WithCSSTransition.tsx
- packages/itwinui-react/src/utils/functions/polymorphic.tsx
- packages/itwinui-react/src/utils/meta.ts
- testing/e2e/app/routes/_index.spec.ts
- testing/e2e/app/routes/_index.tsx
This PR creates a `meta` object containing two fields:
- `module`: This comes from a global `__module` var which gets [substituted by SWC](https://swc.rs/docs/configuration/compilation#jsctransformoptimizerglobals) into `"ESM"` or `"CJS"`.
- `version`: This is simply re-exported from the `styles.js` generated by Vite (see #2106).
- As a result of this, I had to change `styles` from a default export to a named export. This avoids issues in CommonJS where a default export would otherwise need to be accessed using `.default`.
This object is publicly exported to make it easier for consumers to debug version conflicts. In a future PR, I also plan to use this information for some basic runtime checks.
Verified that the `meta` object is created correctly.
Added e2e test to verify that the `meta` …
> export `meta` object containing version and module

- .changeset/heavy-adults-sit.md
- packages/itwinui-react/src/core/Tree/TreeNode.test.tsx
- packages/itwinui-react/src/core/Tree/TreeNode.tsx
Fixes #2109
Pretty simple change to `TreeNode` to accept props (and ref) in a standard way. Review with [whitespace diff turned off](https://github.com/iTwin/iTwinUI/pull/2111/files?w=1).
One interesting note: we use `nodeId` over `id` for some reason. Since it is difficult to accept arbitrary props and exclude `id` at the same time, I marked `id` as deprecated.
Added a simple unit test to verify that event handlers can be passed.
> allow `TreeNode` to accept arbitrary props

- .changeset/fast-windows-attend.md
- packages/itwinui-react/src/utils/meta.ts
Simply renames the module variable, because [`module`](https://nodejs.org/api/modules.html#the-module-object) is a built-in thing in CJS.
This fixes #2123. The same issue was also reported privately by another user ("SyntaxError: Identifier 'module' has already been declared").
N/A
N/A
> fix `module` variable in CJS

- .changeset/mean-hornets-attend.md
- apps/css-workshop/src/pages/fieldset.astro
- packages/itwinui-css/src/fieldset/fieldset.scss
- packages/itwinui-react/src/core/Fieldset/Fieldset.tsx
- packages/itwinui-react/src/utils/components/FieldsetBase.tsx
- packages/itwinui-react/src/utils/components/index.ts
1. Added a new base class that only resets default `<fieldset>` styles.
2. Created a private `FieldsetBase` component that uses this new class.
3. Updated `Fieldset` component to use this new component as a base.
The `FieldsetBase` component will be useful in other places (e.g. #2135) where we should use `<fieldset>` but feel limited by its default styles. In the future, we could potentially even expose this as a public component with some docs and improvements.
N/A. This is just moving things around so everything works the same.
Added CSS changeset since the new class is part of the public API and requires a breaking change.
Added light jsdocs. No React changeset needed, as this shouldn't affect anyone.
> create `FieldsetBase` component

- .changeset/cool-beds-hunt.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
This PR stores the package meta information in a `__iui` key under the global `window` object. It uses a JS `Set` to avoid re-adding the same version twice.
During development only, it detects multiple instances of the package (either multiple versions or different modules of the same version) and displays a warning along with a table listing out all the versions. This is done by patching the set's `add` method to run some extra code every time it's called.
Verified that warnings appear during development when simulating multiple versions (i.e. simply calling `add` multiple times with different args).
<details><summary>Code</summary>
```diff
(globalThis as any).__iui.versions.add(JSON.stringify(meta));
+ (globalThis as any).__iui.versions.add(JSON.stringify({ version: '3.14.0', module: …
```
> warn when multiple instances of the package are found

- .changeset/proud-hornets-itch.md
- packages/itwinui-react/src/core/Alert/Alert.tsx
- packages/itwinui-react/src/core/Breadcrumbs/Breadcrumbs.tsx
- packages/itwinui-react/src/core/ButtonGroup/ButtonGroup.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxEndIcon.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxInput.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxInputContainer.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxMenu.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxMenuItem.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxMultipleContainer.tsx
- packages/itwinui-react/src/core/ComboBox/helpers.ts
- packages/itwinui-react/src/core/ExpandableBlock/ExpandableBlock.tsx
- packages/itwinui-react/src/core/FileUpload/FileUploadCard.tsx
- packages/itwinui-react/src/core/Flex/Flex.tsx
- packages/itwinui-react/src/core/InputWithDecorations/InputWithDecorations.tsx
- packages/itwinui-react/src/core/LinkAction/LinkAction.tsx
- packages/itwinui-react/src/core/List/List.tsx
- packages/itwinui-react/src/core/List/ListItem.tsx
- packages/itwinui-react/src/core/Overlay/Overlay.tsx
- packages/itwinui-react/src/core/SearchBox/SearchBox.tsx
- packages/itwinui-react/src/core/Tabs/Tabs.tsx
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
- packages/itwinui-react/src/core/Tile/Tile.tsx
- packages/itwinui-react/src/core/Toast/Toaster.tsx
- packages/itwinui-react/src/core/TransferList/TransferList.tsx
- packages/itwinui-react/src/utils/components/ButtonBase.tsx
- packages/itwinui-react/src/utils/components/InputWithIcon.tsx
- packages/itwinui-react/src/utils/functions/polymorphic.tsx
- packages/itwinui-react/src/utils/hooks/useSafeContext.ts
Follow-up to #2131, all `displayName`s are now conditionally added only during development.
While this shouldn't make a big difference in the bundle size, the code is only useful for React developer tools, and does add up over time when there are lots of components, so it's good to not have it in the prod build.
Manually inspected the build outputs to verify that `.displayName` assignments are correctly present only in the dev build and removed from the prod build.
Added patch changeset.
> add development checks for `displayName`

- .changeset/few-candles-impress.md
- packages/itwinui-react/src/core/Overlay/Overlay.tsx
Ever since #2100, all code comments were stripped out from the build output. This had the adverse effect of removing the `/*@vite-ignore*/` and `/*webpackIgnore*/` comments in `useInertPolyfill` that were meant to be preserved.
In this PR, I've changed it to use [`Function()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/Function) so that it runs only in the browser, bypassing all static analysis by bundlers. This is perfectly ok to do because we explicitly don't want bundlers to touch this import (which is why we're using a CDN rather than an npm dependency), i.e. it should execute directly in the browser.
This fixes an issue that was reported in https://github.com/iTwin/viewer/issues/318#issuecomment-2194756091.
Unrelated: I also added …
> bypass bundler import for loading `inert` polyfill

- .changeset/two-lemons-end.md
- packages/itwinui-react/src/core/Table/columns/selectionColumn.tsx
- testing/e2e/app/routes/Table/route.tsx
- testing/e2e/app/routes/Table/spec.ts
Fixes a user reported issue in the react teams channel where the `toggleRowSelected` action type would not have a defined value. This was fixed by adding a Boolean parameter to the `row.toggleRowSelected()` function call, instead of relying on the default behavior.
Tested with this code in the vite playground to make sure this change worked: 
```tsx
import { Table } from '@itwin/itwinui-react';
import '@itwin/itwinui-react/styles.css';
import { useMemo } from 'react';
import {
ActionType,
TableInstance,
TableState,
} from '@itwin/itwinui-react/react-table';
export default function App() {
return <ExpandableSubRowsTable />;
}
const ExpandableSubRowsTable = () => {
const columns = useMemo(
() => [
{
id: 'name',
Header: 'Name',
accessor: 'name',
},
{
id: 'description',
Header: 'Description', …
```
> Fix `toggleRowSelected` action value for the `Table` `stateReducer`.

- .changeset/silly-bats-hear.md
- .changeset/swift-chairs-trade.md
- packages/itwinui-css/src/expandable-block/expandable-block.scss
Fixes #2144 
When using CSS grid, [grid blowout](https://css-tricks.com/preventing-a-grid-blowout/) is a common problem: the content inside the grid can become too wide, escaping the bounds of the intended grid layout. This is already bad enough as a default, but the problem gets compounded by the fact that we hide overflow in our expandable content. Adding `grid-template-columns: minmax(0, 1fr)` is the recommended way to fix this problem.
Verified that the linked issue is fixed by recreating it in vite playground
<details><summary>App.tsx</summary>
```tsx
import { Anchor, ExpandableBlock } from '@itwin/itwinui-react';
const lorem =
'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis …
```
> fix grid blowout in `ExpandableBlock`

- .changeset/quiet-kangaroos-teach.md
- packages/itwinui-react/src/core/Table/Table.tsx
- testing/e2e/app/routes/Table/route.tsx
- testing/e2e/app/routes/Table/spec.ts
Fixes the virtualized `Table` components `emptyTableContent` value. This is done by making sure that the `<div>` meant to wrap around the virtual items is only added when there is data being passed into the `Table`, since this `<div>` has a height of 0 when there are no virtual items, causing the `emptyTableContent` to not display.
Updated the e2e test for empty virtualized table to check for the `emptyTableContent`. Also tested with this code in the vite playground: 
```tsx
import * as React from 'react';
import { Table } from '@itwin/itwinui-react';
import { Column } from '@itwin/itwinui-react/react-table';
const App = () => {
type CustomStoryDataType = {
name: string;
description: string;
};
const columns = React.useMemo(
() => [
{
id: 'name',
Header: 'Name',
accessor: 'name',
},
{
id: …
```
> Fixes virtualized `Table` empty content

- packages/itwinui-react/src/core/ComboBox/ComboBoxMenu.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
- packages/itwinui-react/src/core/Table/TableRowMemoized.tsx
- packages/itwinui-react/src/core/Tree/Tree.tsx
- packages/itwinui-react/src/utils/hooks/useVirtualScroll.ts
This is a small follow-up to #2163. It simply reorganizes code, with no real changes. The shared CSS is now set by the shadow-root, and only the dynamic parts need to be set as inline `style`s. This makes it easier to make changes in all components that use `useVirtualScroll`.
I also updated the JSDocs to show the complete intended usage of the hook.
**Note**: I used `!important` for slotted item styles because these should always take priority over all other styles on the item. The virtualizer would simply not work if `position: absolute` wasn't used, for example.
N/A
N/A
> move shared CSS into `useVirtualScroll`

- .changeset/ten-carpets-accept.md
- packages/itwinui-react/src/core/Table/Table.tsx
The `Table` component calls the `useVirtualScroll` unconditionally, which results in the virtualizer being initialized even when `enableVirtualization` is not set. While this hook should probably be moved into a conditionally rendered component (similar to `VirtualizedTree`/`VirtualizedComboBoxMenu`), I've just set the [`enabled`](https://tanstack.com/virtual/latest/docs/api/virtualizer#enabled) option for now.
N/A
> disable `Table` virtualizer based on prop

- .changeset/lucky-goats-kneel.md
- packages/itwinui-react/src/core/Table/ColumnHeader.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
Adds a `ColumnHeader` component to the `Table` component. The primary purpose of this change is to make it possible to wrap the column resizing ref function in `React.useCallback` in order to prevent layout thrashing. This PR addresses an after PR TODO from #2092
Ran automated tests and confirmed that the new component did not add any visual changes. Compared performance and confirmed that the `Recalculate Style` task performs significantly better after this change.
Before:
After:
It should be noted that the overall performance of the virtualized `Table` component remains around the same on high levels of throttling. While the rendering itself has become inexpensive, the scripting for the `Table` component seems to take a very long time.
Added react patch changeset.
> Adds `ColumnHeader` component to `Table`

- .changeset/afraid-fans-push.md
- apps/website/src/content/docs/popover.mdx
- apps/website/src/content/docs/themeprovider.mdx
- apps/website/src/content/docs/tooltip.mdx
- packages/itwinui-react/src/core/Popover/Popover.test.tsx
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
- packages/itwinui-react/src/utils/components/Portal.test.tsx
- testing/e2e/app/routes/ThemeProvider/spec.ts
This builds upon #2173. Since `<Root>` can now be rendered outside of `<ThemeProvider>` (in the DOM tree), we can simply portal it to `<body>`.
This more closely resembles how the browser [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer) mechanism works, so it will be useful when we start using `popover` in more places (currently only in `Tooltip`). This change will be particularly useful for deeply nested `<ThemeProvider>`s (e.g. a v3 leaf node in a v2 app) which have multiple overflowing ancestors.
Updated affected unit/e2e tests that were previously expecting portaled content to be inside the `<ThemeProvider>`.
Manually verified in vite-playground that portaled elements show up inside the `<div data-iui-portal>` that is the direct child of `<body>`. 
I also …
> portal `PortalContainer` into `<body>`

- .changeset/ten-dryers-sleep.md
- packages/itwinui-react/package.json
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
- pnpm-lock.yaml
`useDelayGroupContext` is deprecated and the suggested replacement is the main `useDelayGroup` hook (see [docs](https://floating-ui.com/docs/FloatingDelayGroup#usage)).
While I'm here I also bumped to the latest version of floating-ui again, since we haven't released #2169 yet.
Confirmed that delay continues to work fine in ButtonGroup tooltips.
https://github.com/user-attachments/assets/a51f8dad-986b-4c07-ba56-3d0b4e181e36
Updated existing changeset for version bump.
> remove deprecated `useDelayGroupContext`

- .changeset/fair-cats-tickle.md
- apps/css-workshop/src/pages/menu.astro
- packages/itwinui-css/src/menu/mixins.scss
- Remove unused class `.iui-menu-item` from CSS.
- Add `data-iui-actionable='true'` to list items in menu CSS demo page to fix hover issue.
Checked hover state manually in both CSS and React demo pages.
n/a
> Fix menu item hover state in CSS demo page

- packages/itwinui-react/src/core/List/ListItem.tsx
- packages/itwinui-react/src/core/Menu/MenuDivider.tsx
- packages/itwinui-react/src/core/Overlay/Overlay.tsx
- packages/itwinui-react/src/core/Tile/Tile.tsx
- packages/itwinui-react/src/core/TransferList/TransferList.tsx
- packages/itwinui-react/src/utils/functions/polymorphic.test.tsx
- packages/itwinui-react/src/utils/functions/polymorphic.tsx
This removes the ability to call `polymorphic()` directly. All `polymorphic()` calls have been replaced with `polymorphic.div()`.
The main reason for this PR is to allow using `polymorphic()` for different capabilities (#2196). I'm still experimenting with it and might ultimately decide to go with a different API. Regardless, having `polymorphic()` be an alias to `polymorphic.div()` doesn't provide any real benefit and it's simpler to only have *one* way of writing it.
Removed the test for `polymorphic()`.
N/A. Fully internal change.
> remove direct `polymorphic()` calls

- apps/css-workshop/src/components/Radio.astro
In my previous [PR](https://github.com/iTwin/iTwinUI/pull/2191) regarding the Radio Astro component, I merged the PR before getting this error reviewed, which contained an issue of having wrong behavior when `labelPosition` is set to `right`. This issue is addressed in this PR.
Confirmed all tests passed.
N/A
> Fixed `if` condition when handling `labelPosition` in Radio Astro component

- .changeset/angry-bananas-attack.md
- .changeset/soft-eggs-drive.md
- apps/website/src/content/docs/button.mdx
- packages/itwinui-react/src/core/Buttons/IconButton.test.tsx
- packages/itwinui-react/src/core/Buttons/IconButton.tsx
- When `title` prop is passed, it will be rerouted to `label`. (related: #2182)
- When no `label`/`aria-label` is found, a dev-only warning will be shown.
This change helps nudge users to make their `IconButton`s more accessible. Ideally, the `label` prop would just be required, but that would be a breaking change, so this is the next best solution.
Manually verified the behavior in vite playground. `title` and `label` behave identically, and a warning is correctly displayed when there is no `label`.
Added unit test to verify that `title` is not present in the DOM.
Updated docs for `IconButton` to mention the `label` prop.
Added `patch` changesets for both code changes.
> encourage using the `label` prop in `IconButton`

- .changeset/late-avocados-speak.md
- packages/itwinui-react/src/core/List/List.tsx
- packages/itwinui-react/src/core/List/ListItem.tsx
- packages/itwinui-react/src/core/TransferList/TransferList.tsx
Instead of `<ul>`/`<li>`, we now use `<div>`s for both components. The semantics are added using `role`.
`<ul>`/`<li>` can be very error-prone and restrictive from a DOM perspective.
- You always need the ListItem wrapper to be `<ul>`/`<ol>` (which is easy to forget, as seen in our own [docs](https://dev-itwinui.bentley.com/docs/list#interactive-states)).
- You can not add a wrapper `<div>` around a `<li>` (but you can around a `<div role=listitem>`).
Using `<div>`s avoids these issues, and there is no downside when the appropriate `role`s are present. In fact, it makes it even easier for us to add things like [`group`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/group_role) and [`separator`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/se …
> render `List`/`ListItem` as divs

- .changeset/gold-dolphins-nail.md
- .changeset/silent-humans-leave.md
- packages/itwinui-react/src/core/Table/filters/BaseFilter.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.tsx
- packages/itwinui-react/src/core/Table/filters/FilterButtonBar.tsx
- packages/itwinui-react/src/core/Table/filters/NumberRangeFilter/NumberRangeFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/NumberRangeFilter/NumberRangeFilter.tsx
- packages/itwinui-react/src/core/Table/filters/TextFilter/TextFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/TextFilter/TextFilter.tsx
- packages/itwinui-react/src/core/Table/filters/index.ts
- packages/itwinui-react/src/core/Table/index.ts
Fixes #2200
1. `BaseFilter` now renders a `<form>` element.
2. `TextFilter` now renders `<input required>` for built-in browser validation.
3. `FilterButtonBar` now renders `<button type="submit">`.
Together, this prevents the filter from submitting when the text input is empty.
**Note**: `<form>` comes with built-in keyboard support ([`submit`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event) event is dispatched when <kbd>enter</kbd> is pressed), so I was able to remove explicit `keydown` handlers and related tests.
Confirmed that browser prevents submitting TextFilter with an empty value.
Also confirmed that all filters in the [Filters story](https://itwin.github.io/iTwinUI/2205/react/?story=table--filters&theme=dark) continue to work ok, both with mouse …
> use form validation in `TextFilter`

- .changeset/mighty-spiders-repair.md
- packages/itwinui-react/src/core/Breadcrumbs/Breadcrumbs.tsx
- packages/itwinui-react/src/core/Buttons/IconButton.tsx
- packages/itwinui-react/src/core/Menu/MenuItem.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
- packages/itwinui-react/src/utils/functions/dev.ts
- packages/itwinui-react/src/utils/hooks/index.ts
- packages/itwinui-react/src/utils/hooks/useWarningLogger.ts
Fixes https://github.com/iTwin/iTwinUI/pull/2202#discussion_r1729170659
I've converted `createWarningLogger` into a `useWarningLogger` hook, and made some changes along the way.
1. Immediately I noticed that warnings were showing up twice, so I added a workaround using `setTimeout` to only show them once.
2. I also noticed that `console.warn` doesn't allow looking at the stack trace, so I changed it to `console.error`. This also makes the warnings more prominent and better distinguishes them from the browser's own warnings.
3. I then noticed that the stack trace doesn't include the original component name that's calling our component, so I added some very cursed code to get the component name. I think it is fine because this code is only present during development and property access is …
> create `useWarningLogger` hook

- .changeset/spotty-comics-carry.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
Updated the CDN url to use the exact version number (which we now have after #2107).
Previously we were hardcoding `3`, which would always load the latest 3.x version.
Manually verified by forcing the fallback logic to run in vite playground. The CDN url in the Network tab contains the exact version number.
> fix fallback CSS version

- .changeset/happy-badgers-move.md
- packages/itwinui-react/src/core/Table/Table.test.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
- packages/itwinui-react/src/core/Table/cells/DefaultCell.test.tsx
- packages/itwinui-react/src/core/Table/cells/DefaultCell.tsx
- packages/itwinui-react/src/core/Table/utils.ts
~~Added validation if column id is present before checking for `Cell` property. If column has no id, we cannot know about the `Cell` property. As a result, not adding line clamp styling.~~
Fixed the column `id` check to use `instance.columns` instead of `props.column`. This ensures that columns always have ids (`react-table` generates a backup id if the user-specified column object does not have one).
This fixes an issue where a column with a `Cell` but without an `id` wasn't being detected properly.
Added unit test;
~~TODO: validate in storybook, failing local build for now.~~
N/A
> Dont add line clamp, if column id is not defined

- .changeset/hungry-rocks-matter.md
- packages/itwinui-react/src/core/ComboBox/ComboBox.tsx
- packages/itwinui-react/src/core/ComboBox/ComboBoxMenu.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
- **ComboBox**: Exposes the `portal` key under the `dropdownMenuProps` prop.
- **Select**: Exposes the `portal` key under the `popoverProps` prop.
This enables users to work around issues with the default portaling behavior (e.g. #2245).
Manually verified in vite playground that #2245 is fixed when overriding the `portal`.
```jsx
<Popover
content={
<ComboBox
options={[…]}
dropdownMenuProps={{ portal: false }}
/>
}
>
<Button>Open</Button>
</Popover>
```
<details>
<summary>Video</summary>
https://github.com/user-attachments/assets/48826a18-388c-481e-8de7-d772a0eeb3b9
</details>
Added `minor` changeset to document new prop customization.
> allow `portal` customization in `ComboBox` and `Select`

- .changeset/dull-colts-repair.md
- .changeset/shiny-lobsters-deliver.md
- packages/itwinui-css/src/code/code.scss
- packages/itwinui-css/src/information-panel/information-panel.scss
- packages/itwinui-css/src/slider/slider.scss
- packages/itwinui-css/src/stepper/stepper.scss
- packages/itwinui-css/src/tile/tile.scss
Some components were using `user-select: all`. I believe the original intention was to make it easier to select the entire label in a single click. However, this was often undesirable.
- Sometimes the end user just wants to select part of the text. This became impossible when using `user-select: all`.
- Sometimes the label is an actionable (clickable/draggable) element, which would lead to the text unnecessarily being selected when clicked. I noticed some consumers overriding `user-select` in their custom CSS to avoid this.
- Sometimes the consumer of our components wants to place multiple standalone elements inside the "label" portion.
Removing `user-select: all` has no downsides. The user can still select the whole text, either manually or by OS-specific shortcuts (e.g. triple click on …
> remove `user-select: all`

- .changeset/silent-news-press.md
- packages/itwinui-react/src/core/ProgressIndicators/ProgressLinear.test.tsx
- packages/itwinui-react/src/core/ProgressIndicators/ProgressLinear.tsx
Merges `style` prop with internal styles, so that `<ProgressLinear style={customStyles} value={50}>` doesn't break.
Added unit test.
> fix `ProgressLinear` to merge `style` correctly

- examples/ButtonGroup.input.jsx
- examples/ButtonGroup.overflow.jsx
- examples/Dialog.dismissible.jsx
- examples/Dialog.draggable.jsx
- examples/Dialog.main.jsx
- examples/Surface.elevation.jsx
- examples/Surface.headerfooter.css
- examples/Surface.headerfooter.jsx
This PR makes some very small changes to various examples:
- Fixed Surface Header example layout using `Flex` (previously was misaligned)
- Removed unused import comments in Dialog examples
- Fixed formatting for some copyright header comments
- Fixed missing keys/labels and overflow logic in ButtonGroup Overflow example (similar to #2269)
- Fixed missing `readonly` in ButtonGroup Input example
N/A
N/A
> fix small issues in examples

- .changeset/fuzzy-bikes-move.md
- packages/itwinui-react/src/core/Dialog/Dialog.tsx
- packages/itwinui-react/src/core/Dialog/DialogContext.tsx
This PR changes the default value of Dialog's `setFocus` from `false` to `trapFocus`. So it still defaults to `false` in isolation, but becomes `true` when `trapFocus` is also `true`.
This was done because `trapFocus` would otherwise have no effect, which causes user confusion. See https://github.com/iTwin/iTwinUI/issues/2094#issuecomment-2432779584
Manually verified that setting `trapFocus` also moves focus into the Dialog when `setFocus` is not explicitly set.
Updated JSDocs for both props to clarify usage.
Added `patch` changeset. But this will go in the next minor release, which is good because this is a behavioral change that might require users to adjust their code if they were relying on the old defaults.
> Dialog: update `setFocus` default value

- .changeset/forty-files-arrive-1.md
- .changeset/forty-files-arrive.md
- packages/itwinui-css/src/toast/toast.scss
This PR adds `!important` to `pointer-events: none` to ensure that it can't be overridden by consumers. This is a justified use of `!important` since we know it should never be overridden.
This is mainly needed to work around https://github.com/iTwin/appui/issues/1076. AppUI will investigate a proper fix in their next **minor**, but this should help in the meantime.
N/A. This doesn't change anything within iTwinUI in isolation.
Do see https://github.com/iTwin/iTwinUI/pull/2323#issuecomment-2454916449
Added `patch` changesets.
> ensure that toaster doesn't block clicks

- .changeset/curly-donkeys-press.md
- apps/css-workshop/src/components/selectTag.js
- packages/itwinui-css/src/select/select.scss
- packages/itwinui-react/src/core/Select/SelectTag.tsx
This PR takes a small step towards #907.
- **React**: Updated `SelectTag` component to use `Tag` internally and add extra classes on top of it.
- **CSS**: Removed the use of mixins in `select-tag`. Both `tag` and `select-tag` classes need to be present now.
- Also replaced the `select-tag-button-icon` class with a nested `svg` selector.
There are two important outcomes to these changes:
1. We are able to make use of the "remove button" code from `Tag` (which also handles some edge cases; see #1824)
2. We ship less CSS (mixins create unnecessary duplication).
All existing tests passing. No visual changes.
Added `major` CSS changeset for DOM structure changes.
Doesn't affect usage or behavior for React package consumers.
> reuse `Tag` in `SelectTag`

- packages/itwinui-css/src/select/select.scss
This PR adds a `::before` pseudo-element to the "❌" button of a small `SelectTag`. This pseudo-element uses a negative `inset` value to increase the hit target (clickable area) size of the button, helping satisfy [SC 2.5.8](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html). The `-5px` is a magic number, eyeballed until the size exceeded 24x24.
This is another small step towards #907.
Manually tested on the `select.html` demo page that the hit target size has been enlarged.
Not adding a changeset, since this is somewhat of an unreleased/WIP feature (it's not supported in React).
> increase hit target size for small `SelectTag` button

- .changeset/short-papayas-hunt.md
- apps/react-workshop/src/Select.stories.tsx
- examples/Select.truncate.jsx
- packages/itwinui-react/src/utils/components/MiddleTextTruncation.tsx
- testing/e2e/app/routes/MiddleTextTruncation/spec.ts
This PR improves the accessibility of the `MiddleTextTruncation` component. This component is meant for visual truncation and should not affect the accessibility tree because it would make the text confusing and nonsensical. While truncation in general should be avoided for even better accessibility, this is at least better than before.
The behavior of `MiddleTextTruncation` is now consistent with the browser's built-in `text-overflow: ellipsis` mechanism, so the same set of UX guidelines could be applied in both cases to tackle the truncation problem. Right now, there is no such UX pattern documented in the design system, but it's becoming clear that there needs to be one.
It might be easier to review the first three commits separately:
1. …
> MiddleTextTruncation: preserve original text in accessibility tree

- apps/react-workshop/src/Table.stories.tsx
According to @r100-stack's [comment](https://github.com/iTwin/iTwinUI/pull/2337#discussion_r1841007999) in #2337, `DropdownMenu` might propagate up to the main row which toggles row selection state. Currently, the proposed solution in this PR is to temporarily prevent propagation in the `Table` stories by using `e.stopPropagation()` in the `onClick` event handlers. This approach is a temporary measure until a more permanent solution can be implemented within the internal component code.
Confirmed that clicking row action items (such as "Edit" or "Delete") does not trigger single row selection.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/5cb8b5ad-e493-4462-b7be-d960f6d9286e" />|<video src="https://github.com/user-attachments/assets/57fccfb2-5260-4a99-ac3e-15 …
> Prevented propagation when `DropdownMenu` is present in `Table`

- apps/website/src/components/LiveExample.astro
This PR fixes a Safari-specific accessibility issue, where the content inside nested `display: contents` elements within shadow DOM is completely unreachable when navigating using VoiceOver. I noticed this in the live demos on every page.
Forcing `display: block` on the astro-island fixes (or rather, avoids) the issue.
(Worth emphasizing: This is a [bug in Safari](https://bugs.webkit.org/show_bug.cgi?id=283511). We shouldn't have to do this workaround, and yet here we are. Thankfully the bug has already been fixed, hopefully to be released in the next stable version of Safari.)
Tested on VoiceOver + Safari 18.1.1 (macOS 15.1).
| --- | --- |
| The live demo is skipped entirely. | The live demo is accessible. |
| <video …
> remove `display:contents` to fix live demos in Safari

- .changeset/clean-worms-destroy.md
- packages/itwinui-css/src/tooltip/tooltip.scss
This PR added a buffer of 4px to all sides of the `Tooltip`'s floating content so that when users slightly move their mouse outside of the content box, the tooltip is still visible.
Confirmed that the tooltip is still visible when the mouse moves outside of the border.
https://github.com/user-attachments/assets/718f75fd-a63f-451c-89bf-3962cb7cbb52
N/A
> Added buffer to all sides of `Tooltip`'s floating content

- apps/website/src/content/docs/tree.mdx
- packages/itwinui-react/src/core/Tree/Tree.tsx
This PR updated the `Tree` JSDoc and website documentation to mention the [issue](https://github.com/iTwin/iTwinUI/issues/2357) user reported. The issue discussed the requirement for the `Tree`'s `nodeRenderer` to return a component wrapped with `React.forwardRef`, ensuring proper application of styling and other props to virtualized small `Tree`.
All tests passed.
N/A
> Updated `Tree` JSDoc and website documentation

- .changeset/large-poets-begin.md
- packages/itwinui-react/package.json
Hi all, with Module Federation coming into use more and more we have fallen quite a few times into this pitfall of declaring peerDep version ranges with extra spaces.
The version resolution logic is quite complex inside MF sources and it does not seem to handle having extra spaces in the version range. We want MF to include shared bundle of react and react-dom as the peerDep for iTwinUI and would mean the peerDep has to be resolved with a "correct" version range.
Set of primitive operators are all declared without spaces: https://docs.npmjs.com/cli/v6/using-npm/semver#ranges
I am using a private repository to test this but the results are quite appearant:
Without spaces in the version range:
Bundles are shared like:
N/A
> Remove leading spaces in peer-deps for react deps

- .changeset/modern-pigs-mix-1.md
- .changeset/modern-pigs-mix-2.md
- packages/itwinui-css/src/tile/tile.scss
Fixes https://github.com/iTwin/iTwinUI/issues/2383 using `overflow-wrap: anywhere`.
Tested by recreating the sandbox from linked issue.
| --- | --- |
| ![No wrapping; the tile name overflows out of the tile](https://github.com/user-attachments/assets/cbd14642-1c31-4027-be67-5514bd3b93c3) | ![Wrapping properly](https://github.com/user-attachments/assets/5d3f0a0e-7d7a-44a9-8d1c-e2c464d6dd25) |
N/A
> force wrap long lines in `Tile.Name`

- apps/website/src/content/docs/anchor.mdx
- apps/website/src/content/docs/combobox.mdx
- apps/website/src/content/docs/inputgrid.mdx
Since the `Typography` doc page has been split into to `Text` and `Label` separate docs (https://github.com/iTwin/iTwinUI/pull/2393), there were links to these docs that were still under `typography.mdx` page (`/docs/typography/#text` or `/docs/typography/#label`). This PR replaced those links with the direct doc links to the components (`/docs/text` and `/docs/label`).
N/A
N/A
> Fixed doc links to `Text` and `Label`

- .changeset/many-eggs-chew.md
- packages/itwinui-react/src/core/Tabs/Tabs.tsx
Fixes #2400 by adding `value` to the dependency array of the Effect that recalculates the stripe position.
**Explanation**: The `value` is automatically calculated (in `LegacyTabsComponent`) based on the tab's index in the tablist. So when a new tab is added to an existing position, the existing tab gets shifted and gets a new `value` which forces a recalculation. The `isActive` state stays unchanged, which is why previously it wasn't recalculating.
I still think that consumers should probably remount the tabs when the tablist changes, but this fixes the bug on our end.
Confirmed that the issue is no longer reproducible by recreating the linked sandbox in local vite playground.
N/A
> Tabs: recalculate stripe position when `value` changes

- .changeset/cool-pants-greet.md
- packages/itwinui-react/src/core/Panels/Panels.tsx
`useId` hook from React is not available in react 17, for that purpose a custom hook exists, however; for some reason it is not used in Panels component (likely a typo). Fixes #2410 
Ensure Panels component works with react 17 app
N/A
> Fix missing useId import

- .changeset/four-bananas-appear.md
- packages/itwinui-react/src/utils/components/ButtonBase.test.tsx
- packages/itwinui-react/src/utils/components/ButtonBase.tsx
Fixes #2398. Form submissions are prevented by overriding `<Button type="submit" disabled>` to use `type="button"`.
(This is a workaround that allows us to keep using `aria-disabled` for more accessible disabled buttons.)
Added unit test + manually verified that the linked sandbox is fixed.
> set `type=button` on disabled buttons

- apps/website/src/components/OpenInCodePen.astro
This fixes the broken CodePen demos by updating the React version to 19. This was made possible by the recent release (#2417).
**Explanation**: After some investigation, I found that the issue was that CodePen was somehow loading two different versions of React. This might have been caused by the https://esm.sh CDN using the latest compatible React version for dependencies, or due to CodePen (being a browser-based tool) not correctly resolving "peer dependencies", or a combination of both. Either way, switching to React 19 makes it work correctly.
Verified that the CodePen demos render correctly, both locally and in the deploy preview. No more console errors.
N/A
> fix codepen demos

- apps/css-workshop/public/assets/demo.css
- apps/css-workshop/src/components/ThemeBridge.tsx
- apps/css-workshop/src/components/theme.js
- apps/css-workshop/src/pages/_layout.astro
- apps/react-workshop/.ladle/global.css
- packages/itwinui-css/src/all.scss
- packages/itwinui-react/src/styles.js/styles.module.css
This adjusts the layer order to allow the theme bridge to sit between foundations and component CSS from v5.
- The global styles and foundations are imported into the `foundations` sublayer.
- Everything else lives in the `v3` sublayer (split into `components` and `bridge` nested sublayers). This simplifies things a bit, as `v3` manages its own sublayer order.
Also updates `css-workshop` to conditionally render v5 `<Root>`. See [comment](https://github.com/iTwin/iTwinUI/pull/2438#discussion_r1956729880).
Made sure that stable parts are working correctly.
Testing the theme bridge is blocked by #2436.
Not needed, because this is only changing implementation details.
> reorder layers

- .changeset/young-hornets-end.md
- packages/itwinui-react/src/styles.js/styles.module.css
This is a follow-up to #2438. After testing the latest release of theme bridge, I found an issue if the consuming application sets up their own layer order (as [documented](https://github.com/iTwin/iTwinUI/wiki/Styling)). The `itwinui-v1` layer gets added _after_ the `itwinui` layer (because the `itwinui` layer was already defined by the application). This defeats the whole purpose of including it in our layer order, so this PR removes the `itwinui-v1` layer.
Originally, this legacy layer name was included to [support older codebases](https://github.com/iTwin/iTwinUI/pull/1412#discussion_r1263716496). The last v1 patch version renames `itwinui-v1` to `itwinui.v1` (see https://github.com/iTwin/iTwinUI/pull/1423), so everything should work correctly if applications are on the last patch. …
> remove legacy v1 layer

- .changeset/olive-taxes-sniff.md
- .changeset/weak-impalas-own.md
- packages/itwinui-css/src/expandable-block/expandable-block.scss
- packages/itwinui-css/src/utils/button-base.scss
Closes #2454.
A user reported a bug regarding the cursor behavior specifically for disabled expandable blocks. While the intended behavior of the cursor is `not allowed` when hovering over a disabled expandable block, it remained a `pointer`.
This PR addresses and fixes this bug.
N/A
N/A
> fixed cursor bug when disabled

- .changeset/beige-grapes-wait.md
- apps/css-workshop/src/components/ListItem.astro
- apps/css-workshop/src/pages/menu.astro
- packages/itwinui-react/src/core/Menu/MenuExtraContent.tsx
Noticed that `<MenuExtraContent>` was rendering a `<li role="presentation">` which was a remnant from  when `<Menu>` was rendered as `<ul>` (changed in #1530). This PR changes it to `<div>` to fix the invalid markup.
Also updated HTML demo pages to no longer use `<ul>`/`<li>` for menus.
> [!IMPORTANT]
> `<MenuExtraContent>` should not even be used. It was a mistake and should be deprecated. We can do that in a separate PR after creating an example showing how to achieve equivalent functionality with `<Popover>`.
Manually verified that the correct element is rendered.
Added `minor` changeset.
> change `MenuExtraContent` from `<li>` to `<div>`

- .changeset/plain-grapes-say.md
- apps/css-workshop/src/pages/side-navigation.astro
- apps/website/src/content/docs/sidenavigation.mdx
- packages/itwinui-react/src/core/SideNavigation/SideNavigation.tsx
This changes the `<SideNavigation>` component to render a `<nav>` element (instead of `<div>`), which creates a [navigation landmark](https://www.w3.org/WAI/ARIA/apg/patterns/landmarks/examples/navigation.html).
All existing tests pass.
Manually verified that `<nav>` is being rendered in stories and examples.
Added `minor` changeset.
Updated JSDocs and `/sidenavigation` docs page to mention the landmark. Since navigation landmarks should be uniquely labelled, I added a mention of how to do that.
> make `SideNavigation` render a `<nav>` landmark

- .changeset/fifty-monkeys-argue.md
- apps/react-workshop/src/DropdownMenu.stories.tsx
- apps/website/src/content/docs/dropdownmenu.mdx
- examples/DropdownMenu.basic.jsx
- packages/itwinui-react/src/core/DropdownMenu/DropdownMenu.tsx
- packages/itwinui-react/src/core/Tile/Tile.tsx
- testing/e2e/app/routes/DropdownMenu/route.tsx
- testing/e2e/app/routes/DropdownMenu/spec.ts
This builds upon #2452 to make the same functionality available as a new `closeOnItemClick` prop on `<DropdownMenu>`. The name is bikesheddable.
`<Tile.MoreOptions>` now directly sets this prop instead of using Context.
This prop currently defaults to `false` (to keep existing behavior) but should probably default to true in the future, because menus should almost always close when clicking an item. This also improves the DX slightly, as `menuItems` can now be a simple React fragment instead of a callback which accepts the `close()` function.
Added e2e test for this prop and updated Basic story to use this prop.
Updated Basic example to use this prop, and added a small note at the beginning of `/dropdownmenu` docs to mention this prop.
Added `minor` changeset.
> add `closeOnItemClick` prop to `DropdownMenu`

- .changeset/tender-women-train.md
- packages/itwinui-css/src/utils/line-clamp.scss
- packages/itwinui-css/src/utils/utils.scss
- packages/itwinui-react/src/core/Table/ColumnHeader.tsx
- packages/itwinui-react/src/core/Table/Table.test.tsx
- packages/itwinui-react/src/core/Table/Table.tsx
- packages/itwinui-react/src/core/Table/cells/DefaultCell.tsx
- packages/itwinui-react/src/utils/components/LineClamp.tsx
- packages/itwinui-react/src/utils/components/ShadowRoot.tsx
This PR started as an attempt to address #2444. After some investigation, I found that the one of issues was the use of [`flushSync`](https://react.dev/reference/react-dom/flushSync) in `ShadowRoot` (which gets rendered by every `DefaultCell`). Since a Table can have many cells, this ends up blocking the main thread for a long period, eventually leading to React throwing a "max depth" error. Removing the `flushSync` call allows React to yield to the browser in between rendering different components.
`flushSync` was previously added as a default to ensure that the content gets rendered as soon as the shadow-root is attached. This PR makes this behavior configurable so that it can be turned off for special cases like the `DefaultCell` where the performance cost outweighs the benefits of …
> don't flush shadow-roots in `Table`

- .changeset/better-ears-accept.md
- .changeset/free-lemons-laugh.md
- packages/itwinui-react/src/core/Dialog/Dialog.tsx
- packages/itwinui-react/src/core/Popover/Popover.tsx
- testing/e2e/app/routes/Toaster/route.tsx
- testing/e2e/app/routes/Toaster/spec.ts
This PR implements the approach outlined in https://github.com/iTwin/iTwinUI/pull/2450#issuecomment-2762461133. Instead of using the `portalContainer` prop (which is meant for consumers), `<Popover>` will now use `PortalContainerContext` to ensure all nested floating elements remain inside it.
This fixes #2449 because toaster only respects `portalContainer` (which is no longer set internally) and does not use the `PortalContainerContext`/`usePortalTo` helpers.
---
The same approach has also been used in `Dialog`. Previously, `Dialog` wasn't even changing the portal container. It was partially working because:
- it was relying on other floating elements using a higher `z-index` value.
- it was blocking clicks using a backdrop element.
However, this is not enough because: A modal dialog …
> override portal container in `Dialog` and `Popover`

- .changeset/fluffy-oranges-cough.md
- .changeset/short-knives-find.md
- .changeset/slimy-grapes-occur.md
- apps/css-workshop/src/pages/information-panel.astro
- apps/css-workshop/src/pages/tabs.astro
- apps/website/src/content/docs/tabs.mdx
- packages/itwinui-css/src/tabs/base.scss
- packages/itwinui-css/src/tabs/borderless.scss
- packages/itwinui-css/src/tabs/default.scss
- packages/itwinui-css/src/tabs/pill.scss
- packages/itwinui-css/src/tabs/tabs.scss
- packages/itwinui-react/src/core/Tabs/Tabs.tsx
- packages/itwinui-react/src/index.ts
This PR extracts out all the presentational/visual aspects of `Tabs.Wrapper` `Tabs.TabList` and `Tabs.Tab` into new components, which are exported as subcomponents of `unstable_TabsPresentation`. This makes it  possible to use Tabs in cases where the [ARIA Tabs pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) is not desirable.
**Use cases**
- A navigation list of anchors (see github's fake "tabs" on this very page).
- Tabs with close button (see https://github.com/iTwin/appui/pull/1190#issuecomment-2725326603)
The [four commits](https://github.com/iTwin/iTwinUI/pull/2493/commits) are isolated and can be reviewed individually.
- In the [first commit](https://github.com/iTwin/iTwinUI/pull/2493/commits/08b705de196b6c8fbeb720d4a428d5618b3ab972), the `iui-not-animated` class is removed …
> create `unstable_TabsPresentation` component

- .changeset/curvy-jeans-shine.md
- .changeset/ninety-buttons-pull.md
- packages/itwinui-css/src/table/base.scss
- packages/itwinui-react/src/core/Table/Table.test.tsx
- packages/itwinui-react/src/core/Table/cells/DefaultCell.tsx
- testing/e2e/app/routes/Table/route.tsx
- testing/e2e/app/routes/Table/spec.ts
This PR makes three changes to `Table` to improve the `selectRowOnClick` functionality.
- Increased hit target size of checkbox to cover the entire cell. This will prevent user frustration (they could lose their entire selection if the row is clicked instead of checkbox).
- Added wrapper element around cell text
- Increased hit target size by a few pixels to prevent accidental row click when selecting text.
- Stopped propagation of click events when this wrapper element is clicked, so that `onSelect` is not called when selecting text. (#2475)
Additionally, ShadowRoot is now always added to DefaultCell to preserve slotting behavior (see https://github.com/iTwin/iTwinUI/pull/2462#discussion_r2035844529).
Note: `onSelect` will still be called twice when clicking on the row (outside of text). …
> improve `Table` row selection

- apps/website/src/components/LeftSidebarContent.astro
- apps/website/src/content/docs/accessibility.mdx
Adds a top-level `/accessibility` page to the documentation website.
Starts with a superficial introduction, then goes on to describe the considerations related to Metadata, SPAs, Landmarks and Headings. The goal of these docs is to get applications to start thinking about accessibility and take baby steps towards delivering an accessible experience.
Correctly showing this page in the sidebar required a small change in the `LeftSideBarContent` component to make "Getting started" always the first page.
Tested that the page is appearing correctly and that links are working in the local preview and [deploy preview](https://deploy-preview-2516--itwinui-previews.netlify.app/docs/accessibility/).
For proofreading, the [github markdown view](https://github.com/iTwin/iTwinUI/blob/mayank/accessibil …
> create "Accessibility" docs page

- .changeset/nine-monkeys-lay.md
- packages/itwinui-react/src/core/Table/Table.tsx
Fixes #2513.
Destructs `scrollToRow` from `props` and uses it somewhere in the code to make use of that variable.
Confirmed manually that that console error no longer shows.
> Fix `Table` bug of trying to add `scrollToRow` to DOM

- .changeset/breezy-falcons-sleep.md
- packages/itwinui-react/src/core/Dialog/Dialog.tsx
- packages/itwinui-react/src/core/Dialog/DialogBackdrop.tsx
- packages/itwinui-react/src/core/Dialog/DialogContext.tsx
- packages/itwinui-react/src/core/Dialog/DialogMain.tsx
- packages/itwinui-react/src/core/Dialog/DialogTitleBar.tsx
Fixes #2522 by changing the portal element to `DialogMain` instead of `DialogRoot`. (This was a mistake from #2490).
`DialogContextProps` is being used in multiple places to create the public API, so I added `setDialogElement` in a separate internal type. After doing this, I was seeing some typescript issues in the return type of `useDialogContext`. Removing `|| {}` from the return value fixed the type errors but required using optional chaining (`?.`) in a few places.
Verified that a `Select` inside a `Modal` is interactable with mouse.
> fix `Dialog` portaling

- .changeset/bright-trains-jam.md
- apps/react-workshop/src/AvatarGroup.test.ts
- apps/react-workshop/src/Breadcrumbs.test.ts
- apps/react-workshop/src/Stepper.test.ts
- apps/react-workshop/src/Tooltip.test.ts
- apps/react-workshop/src/WorkflowDiagram.test.ts
- packages/itwinui-react/src/core/Stepper/Stepper.test.tsx
- packages/itwinui-react/src/core/Stepper/WorkflowDiagram.test.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.test.tsx
- packages/itwinui-react/src/core/Tooltip/Tooltip.tsx
The entry delay for `Tooltip` has been increased from 100ms to 200ms, matching the exit delay. The increased value should avoid more instances of accidental activation, and matching the exit value should avoid situations where multiple tooltips can appear at the same time and overlap.
Closes #2508
Needed to adjust the delays used in tests to make them pass.
Other than that, I did some rough manual testing in the vite playground to verify that tooltips don't appear simultaneously and don't overlap when moving the mouse from tooltip trigger to another.
**Note:** For the best experience, `ButtonGroup` should be used instead of manually grouping buttons, to take advantage of the delay group feature.
> adjust `Tooltip` delays

- .changeset/smart-pots-film.md
- .changeset/twelve-hands-guess.md
- packages/itwinui-css/src/button/base.scss
- packages/itwinui-css/src/field.scss
- packages/itwinui-css/src/menu/menu.scss
Set `color` property to match the existing `fill` property value of icons when they are used inside a menu item or field components. This ensures consistent icon colors, i.e. when a font icon is used. Additionally, it enables referencing the icon's color value using the `currentColor` keyword.
Tested by using the `WithIcons` story of `ButtonGroup.stories.tsx` and `WithStartIcons` of `DropdownMenu.stories.tsx`. I have added a text node together with an SVG icon. Since text and color values are similar, it is best to set/override the underlying icon color variable to notice that both the color and SVG fill values are referencing the same value.
New tests/stories could be added if deemed necessary i.e. `WithFontIcons`.
N/A
> Set `color` property to match `fill` of an icon

- .changeset/cute-tires-sniff.md
- packages/itwinui-react/src/core/ThemeProvider/ThemeContext.tsx
- packages/itwinui-react/src/core/ThemeProvider/ThemeProvider.tsx
- packages/itwinui-react/src/utils/providers/FutureFlagsProvider.tsx
- packages/itwinui-react/src/utils/providers/index.ts
This PR removes the `future` object from `ThemeContext` and moves it into a dedicated `FutureFlagsProvider`. Individual `future` flags can be accessed using a new type-safe `useFutureFlag()` hook.
```jsx
const themeBridge = useFutureFlag('themeBridge');
```
The name `useFutureFlag` is bikesheddable (maybe should be `useFutureFlags` or just `useFuture`)
Important points:
- ThemeProvider's `future` prop now accepts a boolean to enable all flags in one go.
- The `future` object is combined between Context and explicitly passed values.
Manually tested that theme bridge continues to work in react-workshop.
This PR is mostly changing internals, but added a changeset for the new `future={true}` option.
> create internal `FutureFlagsProvider`

- .changeset/clever-cycles-care.md
- packages/itwinui-react/src/core/ComboBox/ComboBoxMenuItem.tsx
- packages/itwinui-react/src/core/Menu/MenuItem.test.tsx
- packages/itwinui-react/src/core/Menu/MenuItem.tsx
- packages/itwinui-react/src/core/Select/Select.tsx
Two (and half) changes to `MenuItem` component:
1. Deprecated `value` prop.
2. Made `onClick` be called with the `event` arg when `value` is not passed.
2.5. Removed intermediate `handlers` object which only contains `onClick`.
There were also some very small changes in `ComboBox` and `Select`, both of which internally use `MenuItem`. These components no longer pass `value` to `MenuItem`. The `onClick` is not affected because we weren't really using the arg. There should be no changes needed on consuming side.
The prop types now use a discriminated union to determine the correct type of `onClick` based on `value`. This doesn't work perfectly, but is still acceptable.
- When `value` is passed, `onClick` is called with `value?: unknown` (same as before).
- When `value` is not passed, …
> MenuItem: deprecate `value` prop and expose `onClick` event

- .changeset/tricky-days-flash.md
- packages/itwinui-react/src/core/Tree/Tree.tsx
- packages/itwinui-react/src/core/Tree/TreeContext.tsx
- packages/itwinui-react/src/core/Tree/TreeNode.tsx
Fixes #2330 by setting an explicit width on the virtualizer root. This width is periodically calculated as the maximum width of all _mounted_ elements inside the virtualizer.
This is done inside the virtualizer's [`onChange`](https://tanstack.com/virtual/latest/docs/api/virtualizer#onchange) callback, which I had to debounce because otherwise it executes several times when scrolling. Layout reads/writes are expensive operations so we should try to minimize them. I'm also updating the style imperatively instead of using React state (which would require additional re-render each time).
Manually tested that the linked issue is fixed. Verified also that the Tree returns to its original width after a wider node is collapsed.
[Preview](https://itwin.github.io/iTwinUI/2633/react/?story=tree--virt …
> make virtual tree nodes equally wide
