- .github/ISSUE_TEMPLATE/config.yml
Added explicit link to the github discussions in issue template
> Add questions link in issue template

- src/style/theme.scss
- src/tooltip/tooltip.scss
- Added `iui-color-foreground-body-invert` variable.
Something like the below would have been ideal but I could not figure out how to make it work:
```
$iui-color-foreground-body-invert--light: Invert(t(iui-color-foreground-body--light));
```
> Add body invert color variable

- package.json
- yarn.lock
https://github.com/advisories/GHSA-43f8-2h32-f4cj
> Bump hosted-git-info

- yarn.lock
Addresses https://github.com/advisories/GHSA-w8qv-6jwh-64r5
> Bump browserslist to 4.16.6

- CHANGELOG.md
- backstop/tests/expandable-block.html
- src/badge/badge.scss
- src/expandable-block/block.scss
- src/file-upload/file-upload.scss
- src/inputs/radio-tile.scss
- src/inputs/variables.scss
- src/keyboard/keyboard.scss
- src/style/mixins.scss
- src/table/variables.scss
- src/tabs/pill.scss
- src/tabs/tabs.scss
- src/tag/tag.scss
- src/tile/tile.scss
- src/toast-notification/toast.scss
- src/tooltip/tooltip.scss
- src/user-icon/user-icon.scss
- src/wizard/wizard.scss
Fix DEPRECATION WARNING when using with Dart Sass #131
> Address sass division deprecation warnings when used in Dart Sass

- src/style/variables.scss
> Import space and baseline in variables.scss

- backstop/tests/file-upload.html
- src/file-upload/file-upload.scss
> Remove `>` and id from iui-browse-input

- CHANGELOG.md
- backstop/tests/table.html
- src/table/table.scss
- Added margin-right to filter icon
- Added iui-actionable class for cursor: pointer in header cells
- Added iui-icons-color fill for sort icon hover state
- Formatting fixes
> Fix table spacing, fill and cursor

- src/table/table.scss
- When a table row expands / collapses it animates.
- Fixed a bottom border of a selected expanded row.
- All row borders transition.
> Animate expandable table rows

- src/table/table.scss
Fixed typo that messed up the overflow-x too.
> Fix overflow in table body

- src/slider/classes.scss
- src/slider/slider.scss
Flattened nested structure of:
- iui-slider-rail
- iui-slider-thumb
- iui-slider-track
This reduces the specificity of these classes from 0-2-0 to 0-1-0 and should make it easier to customize them.
> Reduce specificity of slider classes

- backstop/assets/manifest.json
icons are in the same folder so path was wrong.
Fixes this error:
> Fix icon path in manifest.json

- backstop/tests/breadcrumbs.html
- src/breadcrumbs/breadcrumbs.scss
iui-button-borderless mixin is now included in css
> Remove iui-borderless from html

- CONTRIBUTING.md
- src/style/theme.scss
- Added mention of existing Sass variables
- Added link to themed mixin and improved example
> docs: Mention Sass variables and mixins in CONTRIBUTING.md

- .github/workflows/release-please.yml
- CHANGELOG.md
- Used regex to put date in the same line
- Change patch release headings from h2 to h3
- Updated release-please.yml workflow to use headings from old changelog
> docs: Update changelog format

- src/icon/mixins.scss
- src/icon/variables.scss
- src/progress-indicator/linear.scss
- src/progress-indicator/radial.scss
- src/style/variables.scss
- src/user-icon/sizes.scss
- src/user-icon/user-icon.scss
Exporting icon variables, closes #182.
> feat(Icons): size variables are now exported

- package.json
- yarn.lock
Dependabot found vulnerable package: https://github.com/iTwin/iTwinUI/security/dependabot/yarn.lock/set-value/open
https://github.com/advisories/GHSA-4jqc-8m5r-9rpr
> chore: Updated vulnerable set-value

- yarn.lock
https://github.com/iTwin/iTwinUI/security/dependabot/yarn.lock/semver-regex/open
> chore: Updated vulnerable semver-regex

- src/color-picker/color-picker.scss
Changed display to inline-flex in iui-color-picker
> fix: Color Picker inline-flex fix

- yarn.lock
Fixes https://github.com/advisories/GHSA-896r-f27r-55mw via https://github.com/joyent/node-jsprim/commit/017f74473e55872cf71113bec35ce46de74fbe17
> chore(deps): Bump jsprim to 1.4.2

- .stylelintrc.json
> chore: Reduce stylelint max selector depth to 5

- src/table/table.scss
> fix(Table): Add padding to last non-slot column

- src/inputs/classes.scss
- src/inputs/labeled-inputs.scss
> fix(Inputs): Icon alignment fix in input container

- backstop/tests/color-picker.html
- backstop/tests/slider.html
- scripts/generateHtml.js
- Use swap.svg in color picker.
- Use sound SVGs in slider.
> chore: Use latest web component icons

- src/popover/popover.scss
Fix for https://github.com/iTwin/iTwinUI-react/pull/536/files#r799813225
> fix(Popover): Incresed hidden attribute specificity

- backstop/assets/theme.js
New settings popup makes it easier to switch between the extra themes and will also allow easily adding more settings.
> chore: Add settings popup for theme switcher

- src/style/theme.scss
- Convert all HEX to HSL.
- Removed unused variables that were for our old `:focus` styling.
> chore(Theme): Convert HEX to HSL

- yarn.lock
https://github.com/iTwin/iTwinUI/runs/5637386294?check_suite_focus=true
https://github.com/advisories/GHSA-xvch-5gv4-984h
> chore: Updated vulnerable minimist

- .github/workflows/build.yml
Added back script for to have green check on test results after failure
> chore: tests deployment check fix

- .github/workflows/add-issues-and-prs-to-project.yml
Added action to automatically add PRs and issues to project.
> chore: Automate issues and prs addition to project

- package.json
- yarn.lock
> chore(deps): Updated vulnerable async package

- .github/workflows/build.yml
Added `github.head_ref` in deploy v1 check.
> chore: Fix V1 deploy

- CONTRIBUTING.md
- package.json
Added `yarn build-docker` to `CONTRIBUTING.md` as mentioned in issue #645
> docs: Added `yarn build-docker` to CONTRIBUTING.md

- packages/itwinui-css/backstop/tests/tile.html
Some buttons did not get updated to use the new data attributes.
> chore(Tile): Update buttons to use `data-iui-variant` and `data-iui-size`

- packages/itwinui-css/src/carousel/carousel.scss
> fix(carousel): Dots are centered

- packages/itwinui-css/src/global.scss
First step towards https://github.com/iTwin/iTwinUI-react/issues/967.
> feat: Add `.iui-root-background` to opt into setting background

- .github/workflows/changeset-release.yml
- Added GitHub Changesets token.
> Use PAT in changeset workflow

- .github/workflows/publish-npm.yml
Self-explanatory.
This is in prep for making a dev release with #1025 for #1005.
N/A
N/A
> Allow manually publishing react package to npm

- packages/itwinui-css/src/breadcrumbs/breadcrumbs.scss
- packages/itwinui-css/src/header/header-buttons.scss
- packages/itwinui-css/src/input/input.scss
- packages/itwinui-css/src/select/select.scss
- packages/itwinui-css/src/stepper/stepper.scss
- packages/itwinui-css/src/table/table.scss
- packages/itwinui-css/src/tabs/borderless.scss
- packages/itwinui-css/src/tabs/default.scss
- packages/itwinui-css/src/tabs/tabs.scss
- packages/itwinui-css/src/tile/tile.scss
- packages/itwinui-css/src/utils/input-container/input-container.scss
- packages/itwinui-css/src/utils/mixins.scss
Either removed `@at-root` completely (was redundant) or replaced with `:is` where needed.
This is in preparation of scoping v2 classes, because scoping will rely on nesting, and `@at-root` breaks nesting.
All tests should pass.
N/A
> remove all instances of `@at-root`

- apps/website/src/pages/docs/alert.mdx
> doc(Alert): Test of small text change.

- apps/website/src/pages/docs/avatar.mdx
> doc(avatar): Documentation changes

- apps/website/src/pages/docs/variables.mdx
Noticed that we don't have full list of variables in website.
Added missing values.
> website: Update variables page

- yarn.lock
Fixes yarn audit failing because of https://github.com/advisories/GHSA-hc6q-2mpp-qw7j
N/A
N/A
> bump webpack for audit

- apps/website/src/examples/ToggleSwitch.icon.tsx
- apps/website/src/examples/ToggleSwitch.inputgroup.tsx
- apps/website/src/examples/ToggleSwitch.labels.tsx
- apps/website/src/examples/ToggleSwitch.main.tsx
- apps/website/src/examples/ToggleSwitch.sizes.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/toggleswitch.mdx
- Add toggle switch demos for the different options.
- Update documentation, include adding hyperlinks to other mentioned components.
> website: Update toggle switch documentation & demos

- apps/website/src/examples/List.combobox.tsx
- apps/website/src/examples/List.links.tsx
- apps/website/src/examples/List.main.tsx
- apps/website/src/examples/List.subcomponents.tsx
- apps/website/src/examples/index.tsx
- apps/website/src/pages/docs/list.mdx
It's done! Documentation for List component from #1106 has been written from scratch with examples.
N/A. While testing examples, found this issue: #1201 
N/A
> add docs for List and ListItem

- .changeset/fluffy-kangaroos-sin.md
- .changeset/witty-ties-dream.md
- packages/itwinui-css/src/utils/input-container/input-container.scss
- packages/itwinui-react/src/core/FileUpload/FileUploadCard.tsx
- packages/itwinui-react/src/core/LabeledInput/LabeledInput.tsx
- packages/itwinui-react/src/core/LabeledTextarea/LabeledTextarea.tsx
- packages/itwinui-react/src/core/utils/components/InputContainer.tsx
- packages/itwinui-react/src/core/utils/hooks/useId.ts
I was getting this strange error when running jest.
To find the issue, I first had to add `displayName` to all subcomponents, and then I simply moved the setState inside a useEffect.
Tests run fine now. No more warning!
N/A
> fix setState call during render in FileUploadCard

- packages/itwinui-css/package.json
- packages/itwinui-react/package.json
- packages/itwinui-variables/package.json
Needed for npm publish after #1230
TBD
N/A
> add repository field to package.json

- .changeset/sharp-hairs-think.md
- packages/itwinui-css/backstop/scenarios/input.js
- packages/itwinui-css/backstop/tests/input.html
- packages/itwinui-css/src/input-container/input-container.scss
Added hover state and transition to iui-input-flex-container
N/A
N/A
> patch: Add hover to SearchBox

- .changeset/perfect-clouds-flash.md
- .changeset/wild-rocks-boil.md
- apps/portal/package.json
- apps/storybook/package.json
- apps/website/package.json
- packages/itwinui-css/package.json
- packages/itwinui-css/src/expandable-block/expandable-block.scss
- playgrounds/astro/package.json
- yarn.lock
- Declare the initial value of `--_iui-expandable-block-expander-icon-transform` at the root level. Closes #1375.
- Bumped astro and vite version numbers to pass audit.
Still has a border radius issue.
- Nested an expandable block within an expandable block on the HTML demo page.  I had to disable the JS on the page to test correctly.
N/A
> Fix nested expandable block expander icon rotation

- package.json
- yarn.lock
Fixes https://github.com/advisories/GHSA-j8xg-fqg3-53r7 via https://github.com/gkz/optionator/pull/46
N/A
N/A
> bump `optionator` for audit

- packages/itwinui-css/backstop/tests/variables.html
Added a page with most of the variables listed so our designer could have an easy access deployed page to look at when adding and editing colours in Figma design library.
This page can be removed later.
N/A
N/A
> Add temporary variables page in html tests

- package.json
- yarn.lock
fixes https://github.com/advisories/GHSA-p8p7-x288-28g6
> bump `@cypress/request`

- package.json
- yarn.lock
fixes https://github.com/advisories/GHSA-p8p7-x288-28g6.
n/a
n/a
> bump `@cypress/request` again

- CONTRIBUTING.md
Adding documentation that explains how to conduct and utilize the new a11y testing script to the Testing section of CONTRIBUTING.md. 
N/A
N/A
> Adding a11y testing documentation to CONTRIBUTING.md

- packages/itwinui-react/src/core/Toast/Toast.tsx
Changed ToastPresentation to use Polymorphic utils.
Removed CommonProps.
N/A
N/A
> Toast: polymorphic transformation for toast presentation

- .changeset/green-crabs-pump.md
- packages/itwinui-react/src/core/DatePicker/DatePicker.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DatePickerInput.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.test.tsx
- packages/itwinui-react/src/core/Table/filters/DateRangeFilter/DateRangeFilter.tsx
#1522 
- Created DatePickerLocalizedNames  type for the DatePicker localizedNames type;
- Exposed the localizedNames to the DateRangeFilter;
N/A
N/A
> Exposing DatePicker localizedNames to DateRangeFilter

- .changeset/moody-bottles-sniff.md
- packages/itwinui-react/jest.config.js
- packages/itwinui-react/src/core/ComboBox/ComboBoxDropdown.tsx
added back css file from tippy that was removed in #1415.
n/a
n/a
> fix missing animation in ComboBox

- .changeset/proud-suns-flow.md
- packages/itwinui-react/src/core/Table/SubRowExpander.tsx
- packages/itwinui-react/src/core/Table/columns/expanderColumn.tsx
Added `aria-expanded` attribute on expander button in table rows
> Add aria-expanded attribute to table expander button

- packages/itwinui-react/src/core/Tabs/Tabs.tsx
Noticed that the JSDocs for Tabs still mentions the non-existant `<Tabs.ActionsWrapper>`. So I removed it from the JSDocs.
Did a global search and found no more occurrences of "ActionsWrapper"
N/A
> Update/Fix Tabs JSDocs

- apps/react-workshop/src/FileUpload.stories.tsx
When working on https://github.com/iTwin/iTwinUI-migration-tool/pull/99, I noticed type errors in two `FileUpload` stories. This PR makes the necessary small fixes.
Confirmed that the type errors were fixed.
N/A
> Fixed type error in `FileUpload` stories

- apps/website/src/content/docs/themeprovider.mdx
Fixes typo in the path of `styles.css`.
N/A
N/A
> fix styles path in themeprovider.mdx

- packages/itwinui-css/README.md
- packages/itwinui-react/README.md
- resizes the logo images in README
N/A
N/A
> Resize the iTwin Logos in README's

- pnpm-lock.yaml
Fixes https://github.com/advisories/GHSA-f5x3-32g6-xq36
N/A
N/A
> bump `tar` to `6.2.1`

- apps/react-workshop/src/Select.stories.tsx
Noticed that `Item #3` was included twice in the `Select → Native` story. This small PR corrects that.
N/A
N/A
> Small correction in `Select → Native` story

- playgrounds/next/package.json
- pnpm-lock.yaml
This fixes audit failing because of https://github.com/advisories/GHSA-fr5h-rqp8-mj6g
N/A. CI passing now hopefully.
N/A
> bump `next`

- pnpm-lock.yaml
This fixes https://github.com/advisories/GHSA-grv7-fg5c-xmjg
N/A
N/A
> bump `braces`

- .github/ISSUE_TEMPLATE/bug_report.yml
Changed **Bug Issue** template to require the link to a minirepo as well as current version information from users.
Confirmed that the template turned out correctly.
N/A
> Updated Bug Issue template

- packages/itwinui-react/src/core/ProgressIndicators/ProgressLinear.tsx
Small fix in `ProgressLinear`'s JSDocs for its `indeterminate` prop.
i.e. the prop's default value is `true` when no `value` is passed and its default value is `false` when `value` is passed. ([sandbox](https://stackblitz.com/edit/github-ujbmpyyv?file=src%2FApp.tsx))
N/A
N/A
> Correction in ProgressLinear JSDocs
